### ISSUE TITLE
Separate (current) user metadata from users state (public profiles)

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyDapp#1002]
Currently, there is an overlap with the state in `currentUser` and `users`; this can be solved with the following approach:

```
Redux                         DDB                 Description
currentUser / userMetadata    userMetaDataStore   All the things that concern the CURRENT user
users                         userProfileStore    Everything that is publicly visible on a users profile
```

The crux of this is that `currentUser` should no longer contain a profile; the current user's profile will be one of many profiles in `users` state (we can use a selector to select the current user profile based on the current wallet address).

Additionally, this might be a good opportunity to explore merging getting the user metadata when logging in (creating the current user).

**Comment by rdig** [comment]
Closing this as we don't have a userProfileMetadata store, and we are actively working to remove redux state management.
