### ISSUE TITLE
Move colonyNetwork and pinion to /lib (or npm)

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyDapp#1209]
It doesn't make much sense for our submodules to live in the `src` directory. It messes with searches and all kinds of other things. They should actually live in a subfolder in the root directory. Current contestant for the name is `/lib`.

As soon as pinion is open sourced we can also distribute it via npm. That could even be done with the colonyNetwork as soon as we have an official release tag for _glider_.

**Comment by rdig** [comment]
Closing as we already did this. Also `pinion` is no longer in use.
