### ISSUE TITLE
Style Incosistencies - vol 1. 

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#1376]
1.  Cog wheel icon should has opacity reduced by default to 70% - it is too prominent right 
<img width="222" alt="Screen Shot 2019-06-16 at 10 29 56" src="https://user-images.githubusercontent.com/20819402/59771589-53d3dd00-92aa-11e9-954f-c3c89a09ac17.png"> 
plus add a hover state consistent to the style of other icons (like wallet or dashboard icon in top right area)

The right design:
<img width="964" alt="Screen Shot 2019-06-19 at 15 59 15" src="https://user-images.githubusercontent.com/20819402/59771983-36534300-92ab-11e9-8232-5cbd98fab9f1.png">

hover behaviour:
<img width="160" alt="Screen Shot 2019-06-19 at 15 59 34" src="https://user-images.githubusercontent.com/20819402/59771998-3f441480-92ab-11e9-9234-7336b6b07096.png">

2. Background of dropdowns is not consistent to what we have in style guide
<img width="181" alt="Screen Shot 2019-06-16 at 10 43 42" src="https://user-images.githubusercontent.com/20819402/59771729-9dbcc300-92aa-11e9-9218-b292b2d431ee.png">

How it suppose to look:
<img width="1107" alt="Screen Shot 2019-06-16 at 10 42 51" src="https://user-images.githubusercontent.com/20819402/59771760-add4a280-92aa-11e9-9a87-d7da59398daa.png">

3. The text buttons should be placed on a typographic baseline, see how they are floating 
<img width="422" alt="Screen Shot 2019-06-16 at 10 58 47" src="https://user-images.githubusercontent.com/20819402/59771775-b88f3780-92aa-11e9-90bd-7d1adf71dd39.png">

<img width="633" alt="Screen Shot 2019-06-17 at 16 20 40" src="https://user-images.githubusercontent.com/20819402/59772063-5e42a680-92ab-11e9-9903-e5ee7c56dbf9.png">

The right design
<img width="719" alt="Screen Shot 2019-06-19 at 15 57 47" src="https://user-images.githubusercontent.com/20819402/59771898-0441e100-92ab-11e9-827b-0e3266fbbd0e.png">

4. Incosistent buttons
- substitute ghost buttons in favour of blue text buttons
- improve labels of buttons - they are not optically centered
- use large buttons for main actions during onboarding
<img width="1403" alt="Screen Shot 2019-06-17 at 16 13 10" src="https://user-images.githubusercontent.com/20819402/59772114-75819400-92ab-11e9-9ee5-237b3bfd99b1.png">

the right design
<img width="735" alt="Screen Shot 2019-06-19 at 16 02 24" src="https://user-images.githubusercontent.com/20819402/59772222-aa8de680-92ab-11e9-93f1-4e416e95e4e2.png">

medium buttons
<img width="224" alt="Screen Shot 2019-06-17 at 16 21 03" src="https://user-images.githubusercontent.com/20819402/59772287-c98c7880-92ab-11e9-94f3-0794715a422b.png">

the right one:
<img width="809" alt="Screen Shot 2019-06-19 at 16 03 49" src="https://user-images.githubusercontent.com/20819402/59772322-d8732b00-92ab-11e9-9ffe-07456c64078d.png">

Figma med fi style guide: https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Med-Fi-Style-Guide?node-id=94%3A0

onboarding: https://www.figma.com/file/HRJD8xgIL2BcQsRQjFPGuP0C/Login-and-Colony-Contribute-MVP?node-id=1743%3A0

5. Ancient colors
Ancient colors - some headings have dark-gray color (47,47,47,0.7) - instead should be 60,68,77 - the best would be to check it with primary and secondary color from the style guide (figma)

<img width="451" alt="Screen Shot 2019-06-16 at 11 08 32" src="https://user-images.githubusercontent.com/20819402/59772445-0b1d2380-92ac-11e9-9d9a-580c06572028.png">

6. Wrong copy style on onboarding screens - use regular text instead of bolded one

<img width="576" alt="Screen Shot 2019-06-17 at 16 12 56" src="https://user-images.githubusercontent.com/20819402/59772845-d8bff600-92ac-11e9-8c9b-8358f05fedb4.png">

The right one:
<img width="705" alt="Screen Shot 2019-06-19 at 16 09 49" src="https://user-images.githubusercontent.com/20819402/59772853-dcec1380-92ac-11e9-8df3-45d1c9dad484.png">

7. Task feed logs - they utilize the wrong font size:
<img width="686" alt="Screen Shot 2019-06-16 at 11 27 18" src="https://user-images.githubusercontent.com/20819402/59772946-04db7700-92ad-11e9-842b-0fbadfef626d.png">

How should look like (12px and bigger line-height)
<img width="769" alt="Screen Shot 2019-06-19 at 16 12 39" src="https://user-images.githubusercontent.com/20819402/59772982-191f7400-92ad-11e9-901d-887b0718bc3a.png">

8. The wrong font weight for values. Instead of bold, please use regular:
<img width="576" alt="Screen Shot 2019-06-16 at 11 30 38" src="https://user-images.githubusercontent.com/20819402/59773069-4704b880-92ad-11e9-85c9-2c59091d3824.png"> 
+ check also question mark rendering

Regular:
<img width="633" alt="Screen Shot 2019-06-17 at 16 20 40" src="https://user-images.githubusercontent.com/20819402/59773082-4bc96c80-92ad-11e9-9580-eb1fd5d387fa.png">

9. Borders of a comment box in a task UI - please check figma designs
<img width="271" alt="Screen Shot 2019-06-16 at 11 28 19" src="https://user-images.githubusercontent.com/20819402/59778368-a3200a80-92b6-11e9-9d62-19377f553dcf.png">

Figma
Task workflow: https://www.figma.com/file/IsTzagr0TvzEMf3nwIcTthLm/Task-Workflow?node-id=3533%3A33
Style guide: https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Med-Fi-Style-Guide?node-id=94%3A0
Onboarding: https://www.figma.com/file/CGSZdfl2KbfKvG30jnoKSmtn/Onboarding?node-id=1373%3A22227
Admin: https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=701%3A2

**Comment by Karol-colony** [comment]
Up, what is the status of it?

**Comment by collinvine** [comment]
Still on hold, let's take this into consideration during the UX review.
