### ISSUE TITLE
Create Colony New Username UI Updates

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1381]
Hover state needs a wider width (it also has a weird pop-over "helper" if you leave your mouse there). 

Missing validation for username being available. 

Current Implementation:

<img width="1439" alt="Colony" src="https://user-images.githubusercontent.com/19378807/59793187-c6cd5b80-928a-11e9-8333-13a8b5562c02.png">

<img width="1439" alt="Colony" src="https://user-images.githubusercontent.com/19378807/59793410-583ccd80-928b-11e9-9fb5-cf2023bc73a7.png">

<img width="1437" alt="Colony" src="https://user-images.githubusercontent.com/19378807/59793650-e87b1280-928b-11e9-8a3d-1794c36efd06.png">

Figma Implementation:

![Tooltip_ unique ID](https://user-images.githubusercontent.com/19378807/59793298-08f69d00-928b-11e9-84d6-b5ed0f5561d7.png)

<img width="1439" alt="Colony" src="https://user-images.githubusercontent.com/19378807/59793436-6b4f9d80-928b-11e9-875c-160703520ab0.png">

![Tool tip_ use an ERC20 token](https://user-images.githubusercontent.com/19378807/59793678-faf54c00-928b-11e9-9a1c-db00573bd31d.png)

Tacos 🌮 🌮 🌮 🌮 :

"Hello" should be pushed over when copying an address. 

![Colony](https://user-images.githubusercontent.com/19378807/59793514-9f2ac300-928b-11e9-94fd-b9074ff93164.png)

Can we make the etherscan link clickable?

<img width="1439" alt="Colony" src="https://user-images.githubusercontent.com/19378807/59793759-30019e80-928c-11e9-95cd-ff43f487a9c2.png">

Add helper text to image upload. It was not there on the figma screens but someone put it on the "bring a token" screen and I think it is helpful and nice. Can we add it to the create token screen. 

<img width="1436" alt="Colony" src="https://user-images.githubusercontent.com/19378807/59793947-a43c4200-928c-11e9-9b70-d573826620ea.png">

<img width="1439" alt="Colony" src="https://user-images.githubusercontent.com/19378807/59793991-c209a700-928c-11e9-994c-b86bf04274e3.png">

**Comment by Karol-colony** [comment]
This might be considered to onboarding improvements as well
