### ISSUE TITLE
Create colony stuck after second transaction

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1501]
## Steps to reproduce

1. ???

## Expected behaviour

* Should be able to progress through the colony creation flow.
* Also we should improve the UI so that we have a processing spinner as long as the saga is running and not only as long the transactions are mined

## Actual behaviour

* stuck at step two, no indication of why.
![image](https://user-images.githubusercontent.com/8453294/61128027-e9fcbc80-a47e-11e9-91ef-7f2ad6cb7e18.png)

**Comment by sprusr** [comment]
Pretty certain we can close this, reopen if you think I am mistaken :)
