### ISSUE TITLE
Empty tasks in task list

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1608]
## Steps to reproduce

1. Hit the new task button
2. Navigate to another page before the task is done being created

## Expected behaviour

There should either be no change/new task created or a new untitled task is created.

## Actual behaviour

A new blank task is created that cannot be interacted with
![image](https://user-images.githubusercontent.com/8453294/61740179-fbd23f80-ad5b-11e9-9b05-c39bd242552b.png)

**Comment by rdig** [comment]
Closing due to not being able to reproduce, and more than two weeks have elapsed since then.
