### ISSUE TITLE
Check for valid token on colony creation (Goerli)

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/colonyDapp#1635]
## Steps to reproduce

1. Create a colony with an address that is not a valid token address on goerli

See https://qa.colony.io/colony/vitalik for an example of a colony already created with an invalid token address (and unfollow this colony to avoid slow loading in an unrealistic scenario).

## Expected behaviour

* An error is thrown, the user is not allowed to create a colony with an invalid token address

## Actual behaviour

* No error is thrown, the user is allowed to create a colony with an invalid token address

## Suggestions

* Currently we are checking token address only on mainnet using ethplorer ([see here](https://github.com/JoinColony/colonyDapp/blob/16f979bb63949b27f102b10b34af5b07e8015a3d/src/utils/external/index.js#L111)) when we should be checking based on the network that we are connected to.

_Note: This check is also currently slowed down by #1627 but the only way to check for a valid token is to see whether a token method returns `0x`._

**Comment by JamesLefrere** [comment]
It seems like Ethplorer only support mainnet: https://github.com/EverexIO/Ethplorer/issues/24

Unless there's another service, I would suggest attempting a call with the ERC20 ABI against the address, and assuming it's valid if the call works.

**Comment by chmanie** [comment]
Is this something we should prioritise at all? QA is strictly used by us only.

I wonder though what happens on mainnet with a token that is not listed in ETHplorer

**Comment by JamesLefrere** [comment]
Sorry, it isn't, I didn't notice this was iceboxed.
