### ISSUE TITLE
Dynamically refresh ETH balance in create account wizard

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1662]
### Story

When creating a new account and claiming my username with a new wallet, I want my ETH balance to dynamically update, so that I can see when a transaction sending ETH to my address goes through

### Description

On this screen, my ETH balance shows zero and doesn't update:

<img width="1792" alt="Screen Shot 2019-08-05 at 9 59 30 AM" src="https://user-images.githubusercontent.com/15755488/62481675-ec91bf80-b767-11e9-8098-a54815048ce9.png">

After I send eth to my address, I want this balance to update and the warning message to disappear so I know I can sign the TX.

### Suggestions

Have a refresh icon next to the balance which reloads just the balance (and not the whole page). That was @rdig's suggestion.

**Comment by sprusr** [comment]
Suggestion: use incoming block listener (gets called for each new mined block; if we don't already have such a function set up, we can set it up with ethers contract). Set up a counter so that every n-blocks (a sensible number of blocks) we refetch the balance and update redux.
