### ISSUE TITLE
Recovery for colonies created on-chain (only)

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1676]
### Story

As an owner of a colony created on-chain (but not via the dapp), I want to recover my colony, so that I can use it in the dapp.

### Description

todo

### Design (optional, might not be applicable)

todo

### This issue is complete when...

- [ ] I can recover a colony that was previously created but is not currently accessible in the dapp.

### Suggestions

todo

### Subtasks

todo

**Comment by JamesLefrere** [comment]
@chmanie Took care of this :clap:

**Comment by auryn-macmillan** [comment]
Nice! @ryanchristo does that mean we can use the CDEV colony in the dapp as well now?
