### ISSUE TITLE
New inbox empty state

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1679]
### Description

Passing off a design for an empty state in the inbox. It's pretty simple to start just a message that states:

"It looks like you don’t have any notifications. Don’t worry, we’ll let you know when anything important happens."

### Design

[Figma link](https://www.figma.com/file/OD53CoZpRKVqDdKsMYGldko8/Inbox?node-id=250%3A205)

![Inbox - empty state](https://user-images.githubusercontent.com/19378807/62587073-1f75a980-b875-11e9-980e-63b192001c20.png)

**Comment by rdig** [comment]
Bumped estimate to `3` to increase in scope
