### ISSUE TITLE
Add "Root" domain to the colony home screen and domain list

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1700]
### Story

As a *user interacting with domains*, I want to *be able to select the root domain from the colony home screen*, so that *I can filter by tasks in that domain*

### Description

Ok, that user story isn't very helpful. But we want to add the "root" domain to the colony home screen and the list of domains in the admin screen. This means a user will be able to see "all" domains or select "root" to just see the tasks in the root domain. 

### Design

Add "Root" to domains tab. This means the domain tab will never have an empty state. 
<img width="1439" alt="Colony" src="https://user-images.githubusercontent.com/19378807/62815275-37933600-bacc-11e9-814a-9997ae211750.png">

Add "Root" below "All" on the colony home screen.
<img width="1401" alt="Colony" src="https://user-images.githubusercontent.com/19378807/62815296-64474d80-bacc-11e9-8d43-dde9b5790d77.png">

**Comment by JamesLefrere** [comment]
We should probably also disable the 'Edit name' button (on hover) for the root domain in the domains list, and maybe also add a check in the command to set the name.

**Comment by rdig** [comment]
This was fixed by #1907

Closing
