### ISSUE TITLE
Task descriptions not displaying

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1740]
## Steps to reproduce

1. Create a task with a title and description.
2. Refresh

## Expected behaviour

The text description text should be visible.

## Actual behaviour

![image](https://user-images.githubusercontent.com/8453294/63372878-fc5af780-c354-11e9-9aa8-4802845da721.png)

Note: it is only on tasks that I created that I cannot view the description and I cannot reproduce this on QA.
Here is the task from the screenshot: https://colony.io/colony/speaketh/task/jGagdIUyHUgxxeaqu3WiG

**Comment by rdig** [comment]
Handed over to @chmanie since he implemented the original version of `useInitEditorState`
