### ISSUE TITLE
[new] Payment States

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#1744]
### Story

Example: As a *user who has payment*, I want to *see a visual indicator if payment is pending*, so that *I can inform recipient to stay patient*

### Description (optional, but useful!)

There are 4 states:
- draft (gray dot)
- pending (yellow dot)
- failed (red/dark pink dot)
- completed (without indicator)

Draft, pending and failed transactions are visible under "Open Tasks" option. On hover, tooltips appear. Completed payments are visible under "Completed". Copy available on Figma. Please check the descriptions. 

### Design (optional, might not be applicable)

[Figma link](https://www.figma.com/file/K4a0mjyfFFw4cvsk3fiuin/Payments?node-id=161%3A0)

[Image]<img width="1440" alt="Colony Home (1)" src="https://user-images.githubusercontent.com/20819402/63420026-2cae9e80-c406-11e9-86a4-9917bfe001a3.png">
<img width="1440" alt="Colony Home (2)" src="https://user-images.githubusercontent.com/20819402/63420028-2d473500-c406-11e9-8d43-8be3763fbb93.png">
<img width="1440" alt="Colony Home (3)" src="https://user-images.githubusercontent.com/20819402/63420029-2d473500-c406-11e9-9dad-91037cc557c0.png">
<img width="1440" alt="Colony Home (4)" src="https://user-images.githubusercontent.com/20819402/63420031-2d473500-c406-11e9-87b3-1239a7c1e1eb.png">

### Suggestions (optional)
If there are any problems with db or major issues, please create separate tasks. 
Taco for displaying "Retry" transaction for failed one (see on Figma).

**Comment by Karol-colony** [comment]
Does it overlap with any of suggestions issues @collinvine  ?

**Comment by collinvine** [comment]
Not that I can think of immediately. Do you have anything in mind?

**Comment by Karol-colony** [comment]
These little yellow and red dots? They are almost like a global pattern now.
