### ISSUE TITLE
Task created before 1.0.2 crashes the dapp

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1782]
## Steps to reproduce

1. As an admin a task that was created before v1.0.2, try to open a task that was created prior to v1.0.2

## Expected behaviour

Task should open and display as normal.

## Actual behaviour
The app crashes.
Video: https://drive.google.com/file/d/1gvEFLZsMNfyWlM4ZgDoiTP3SsjMRQNzT/view?usp=sharing
Link to the broken issue: https://colony.io/colony/speaketh/task/jGagdIUyHUgxxeaqu3WiG

**Comment by auryn-macmillan** [comment]
Hhhmm... it may not be just because the issue was created before the new version was pushed.
I just broke this issue by assigning it to an address: https://colony.io/colony/speaketh/task/e6itOeEldApDmUQkTpK2l

**Comment by rdig** [comment]
There's already a issue tracking this, and in progress #1777

**Comment by auryn-macmillan** [comment]
That seems to be the case for the second task I linked to, but the first task is not assigned to anyone.

**Comment by auryn-macmillan** [comment]
I also just noticed that tasks on the "my tasks" tab are not effected by this issue.
