### ISSUE TITLE
Interactive popover does is not displayed if there is no username

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1784]
**Issue**
For addresses that do not have a username, the interactive popover from #1715 does not show up.

This could occur for one of two reasons; the data has not loaded yet or an address has been assigned as an admin or worker but has not yet created a colony account.

In this case, I think we should still show the popover so that people can see the address.

_Originally posted by @auryn-macmillan in https://github.com/JoinColony/colonyDapp/pull/1715#issuecomment-526590976_

**Comment by rdig** [comment]
It may be that the address hasn't loaded either. 

But I'll investigate

**Comment by auryn-macmillan** [comment]
> It may be that the address hasn't loaded either.
I imagine it has to load the address in order to generate the blockie, no?

**Comment by rdig** [comment]
I'm already working on a handfull of fixes for the info popover in #1792

So I'll tackle this issue there as well.
