### ISSUE TITLE
Username coloring is wrong on InfoPopover

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1787]
## Steps to reproduce

1. Click a user's avatar and look at their @username

## Expected behaviour

* The @username is colored "pink" as per the issue #1656 

## Actual behaviour

* The coloring has been removed (see @jack in attached image)

![Screen Shot 2019-08-30 at 3 51 51 PM](https://user-images.githubusercontent.com/15755488/64054934-51a9bc80-cb3e-11e9-83cf-362e418fe61c.png)

**Comment by collinvine** [comment]
I'm also going to cc @Karol-colony to review the spacing on the info popover as I believe it is incorrect. 

@Karol-colony if the spacing is wrong (you can view this on the dapp now), then please open another issue for "fixes to the InfoPopover"

**Comment by rdig** [comment]
Closing in favor of #1792
