### ISSUE TITLE
Colony creation fails on step 6. Add OldRoles Extension to Colony

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1790]
## Steps to reproduce

1. Attempt to create a colony

## Expected behaviour

Transactions should be sucessful

## Actual behaviour

Transaction at step 6 fails.
https://etherscan.io/tx/0x82196a8e4a1980500f828d9af427df0c13caaf433a4246128aa1d13d3c7ff9a6
![image](https://user-images.githubusercontent.com/8453294/64059342-86dafc80-cb88-11e9-89f8-a5573c9c17c6.png)

**Comment by rdig** [comment]
I can't replicate this neither locally or on qa _(goerli)_

I'll try poking at it some more, but this might all have been due to some Metamask shenanigans.

**Comment by auryn-macmillan** [comment]
An interesting flow on effect from this is that the colony appears to work fine, but I cannot add/remove admins nor finalize tasks, because transactions 6-9 were never completed.

**Comment by auryn-macmillan** [comment]
@rdig looking through my transaction history, it appears that the Add OldRoles Extenstion to Colony transaction actually confirmed the first time, but for some reason the dapp did not recognize it. After which, I ended up trying to redeploy the contract several times in a row; failing each time because the contract returned `"colony-extension-already-deployed"`.
You can see the successful transaction [here](https://etherscan.io/tx/0x74df7e2cb84955445c78468d581ef2d6b0c31d0201d5034068c9a73dfc13a359), followed by several unsuccessful transactions ([1](https://etherscan.io/tx/0x74df7e2cb84955445c78468d581ef2d6b0c31d0201d5034068c9a73dfc13a359, [2](https://etherscan.io/tx/0x8f0856e52547a71badecb924896767397440f4c5d73cb2b85b4896f9a82dc3e9), [3](https://etherscan.io/tx/0x86899c67862a9e7b127e98ddd5c9e1323e3b3225c324a937ccc7217db295567a),  [4](https://etherscan.io/tx/0x7b767ae8c7af1a1d6ece853b1a111a46702513e6ae31c635ba11839ed5ef8faf), [5](https://etherscan.io/tx/0x2ee328322da5da86a85c6c7e83e92b771bc1bf75645d05ad0499076e5027a2a7))

So I guess the real question is, why didn't the dapp realize that the first transaction was successful?
I'm assuming it was probably a metamask issue.

**Comment by auryn-macmillan** [comment]
In this case, the error of my failed transactions we `"colony-extension-already-deployed"`, is there any chance we could check for that type of error on this transaction and progress onwards if this is the case?

**Comment by auryn-macmillan** [comment]
Also, I just wrote a help center article (with the help of @area) to walk people through manually completing the remaining transactions in such a case.
https://help.colony.io/hc/en-us/articles/360035670293-A-transaction-failed-midway-through-creating-a-colony-what-now-

**Comment by rdig** [comment]
This is no longer relevant, because as of `1.0.4` we are no longer deploying this contract extension when creating new colonies.
