### ISSUE TITLE
Add a copy and support jpg for tokens

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#1796]
### Story

As a *user creating a colony*, I want to *see a suggestion what is recommend file format to use for tokens*, so that *I know how to avoid wrongly rendered token icon*

### Description (optional, but useful!)

A single user was suprised that despite choosing a jpg file, it is not possible to render these files. Error was displayed after the fact. Our intention was not to allow uploading them at all to avoid errors as user cannot substitute image now. Nevertheless, to avoid a future requests like that we decided to support jpg and add extra copy that warns user about possible wrong rendering. 
Let's give users a choice. 

### Design (optional, might not be applicable)

[Figma link](https://www.figma.com/file/CGSZdfl2KbfKvG30jnoKSmtn/Onboarding?node-id=2519%3A175) // create a token

<img width="1440" alt="Create Token@2x" src="https://user-images.githubusercontent.com/20819402/64148644-1223ee80-ce24-11e9-826a-0e74dca9ecc6.png">

### This issue is complete when...

- [ ] it is possible to add jpg file as token logo
- [ ] there is microcopy added below the field

**Comment by ceolson01** [comment]
Check how we render images / how they're encoded.
