### ISSUE TITLE
Etherscan link on finalized task points to bad url

### ISSUE THREAD

**Issue by gichiba** [JoinColony/colonyDapp#1802]
## Steps to reproduce

1. Finalize a task

Upon finalizing a(n example) task, the link generated is: 
https://mainnet.etherscan.io/tx/0x78b1c08adbf86d24d8108ec3bfe9bff22a98b9d5e4093d7acea50b41a2abecd8

which does not resolve. 
removing 'mainnet.' from the string resolves to the correct transaction.

**Comment by rdig** [comment]
Weird. I thought I fixed this in #1684 

I'll investigate.
