### ISSUE TITLE
Address Format is wrong! on wallet screen

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1824]
## Steps to reproduce

1. Navigate to the wallet screen in the dapp

## Expected behaviour

* The wallet screen should display my wallet address

## Actual behaviour

* Rather than the wallet address, "Address format is wrong!" is displayed.

![image](https://user-images.githubusercontent.com/8453294/64722279-227b3f80-d49c-11e9-81ab-013439c3303d.png)

## Feedback portal link
https://help.colony.io/hc/en-us/community/posts/360034865834-Wallet-Screen-Bugs

**Comment by rdig** [comment]
This is about data not being loaded properly.

But I think it can be fixed with better defaults.

I'll investigate
