### ISSUE TITLE
For DLP, remove Architecture Subdomain role and add Recovery to the list

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1842]
### Description (optional, but useful!)

1. Remove Architecture Subdomain from the DLP table 
2. Add Recovery to the list of roles you can select

https://joincolony.slack.com/archives/C02R9SP3J/p1568717082023200

### Design (optional, might not be applicable)

https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=995%3A0&viewport=2142%2C-756%2C0.3652943968772888

**Comment by itspatch** [comment]
I think we can update the copy for the architecutre role from

"Set the administration, funding, and architecture roles."

to 

"Set the administration, funding, and architecture roles in any subdomain." 

I think that is what Alex is getting at when he said:

"Architecture subdomain is really just a quirk of how we implemented permissions on the contract level. It's only ever set in conjunction with Architecture in the setArchitectureRole command
(The quirk being a result of the fact that architecture in x lets you create a subdomain in x, but not modify permissions in x, only its subdomains)"
