### ISSUE TITLE
User with only root permission cannot see {colonyname}/admin

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1845]
## Steps to reproduce

1. log in with a user who has only the `root` permission in the colony.

## Expected behaviour

The user should have access to the colony's admin panel.

## Actual behaviour

The user cannot not access the colony's admin panel; neither via the settings icon nor via a direct URL.

**Comment by rdig** [comment]
@sprusr should a user with only `Root` permissions, actually have access to the admin panel ?

Ie: is this actually a bug, or is it by design ?

**Comment by auryn-macmillan** [comment]
I assume they should, since there are functions that require root that are only accessible via the admin panel. Perhaps @itspatch can clarify.

**Comment by itspatch** [comment]
Yes, a user with root permission should have access to admin panel. Good catch Auryn

**Comment by rdig** [comment]
Closes by #1816
