### ISSUE TITLE
Roles should show up in Subdomain

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1848]
## Steps to reproduce

1. Go to permissions table in a colony.
2. Switch to any other domain than root. 
3. No roles show up in this domain. 

## Expected behaviour

* Since permissions in a parent domain also are the same permissions in a child domain, anyone with a root permission, should also have the same permission in each domain. 

This means that the list of permissions in root domain should also be seen in the other domains plus any other users that have permissions in only that domain. 

## Actual behaviour

* The permissions do not show up in child domains. 

![Colony](https://user-images.githubusercontent.com/19378807/65182163-8b6f3400-da15-11e9-9d8e-853cbbbbf9bf.png)

<img width="1432" alt="Colony" src="https://user-images.githubusercontent.com/19378807/65182211-acd02000-da15-11e9-91e5-b0c09d5438b3.png">

## Suggestion

The hard part about this is the permission pop-over. You cannot remove a permission from a subdomain without removing it from the parent domain. Here we have a hover state design to educate the user on switching domains to edit their permission. 

![Switch to root domain](https://user-images.githubusercontent.com/19378807/65182562-6f1fc700-da16-11e9-8c4c-a7d11397b8f9.png)

**Comment by itspatch** [comment]
There is a chance I missed some decision along the way here so let me know if this doesn't make sense.

**Comment by rdig** [comment]
This should wait until #1816 is merged

**Comment by itspatch** [comment]
Right, I have this on my to-do list to try to figure something out (unless one of you have a great idea!). I'll post back in here with an update

**Comment by itspatch** [comment]
@sprusr here are the designs for adding a * to the permissions that were set in the parent domain like we talked about. 

We can add a link to this help center article for users to learn more: 

https://help.colony.io/hc/en-us/articles/360024588993-What-are-the-permissions-in-a-colony-

*designs*

![Permissions_](https://user-images.githubusercontent.com/19378807/65989844-4e586800-e43f-11e9-9b01-bd86c64a7ab1.png)

![Add Role_](https://user-images.githubusercontent.com/19378807/65989850-52848580-e43f-11e9-9954-e0802c3f3a0e.png)
