### ISSUE TITLE
Inbox Popover Broken Loading State

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#1855]
When loading new issues, the inbox popover loading state look _very_ broken:
- loading animation is not aligned
- see all link is not at the bottom

![Screenshot from 2019-09-19 16-46-16](https://user-images.githubusercontent.com/1193222/65249809-44f50480-dafd-11e9-9296-97cd8f1d5be8.png)

**Comment by rdig** [comment]
@JoinColony/product can you link us to the figma screen that has the correct designs for this ?

**Comment by Karol-colony** [comment]
@rdig  we would need to design that screen, I can prepare something for tomorrow

**Comment by rdig** [comment]
Take your time, it's not urgent.

But this should have been part of the original specs. Granted the developer who original worked on this, should have raised the issue while implementing it initially.

**Comment by rdig** [comment]
I fixed part of it in the branch I'm working in currently: #1679 

It now looks like this:

![Screenshot from 2019-09-19 17-32-58](https://user-images.githubusercontent.com/1193222/65253676-b0da6b80-db03-11e9-9032-50f5cc650513.png)

![Screenshot from 2019-09-19 17-33-11](https://user-images.githubusercontent.com/1193222/65253677-b0da6b80-db03-11e9-9b4d-8fe8391de3a1.png)

If you're ok with this, then you don't need to do anything else, and I'll just close this issue.

**Comment by Karol-colony** [comment]
Thanks, I would like to do additional exploration with preloader being visible, let's do not close it yet

**Comment by rdig** [comment]
>  preloader being visible

Preloader is visible in this case. It's the 3 small dots

I just took bad screenshots :)

**Comment by Karol-colony** [comment]
I know thanks, it is the kind of action that should be obvious and easy to see without need to focus on reading that.
 
Added design here: https://www.figma.com/file/OD53CoZpRKVqDdKsMYGldko8/Inbox?node-id=194%3A0 
use large preloader, as far as I remember it might appears on the onboarding / colony creation process 

![image](https://user-images.githubusercontent.com/20819402/65315086-c8fbca80-db97-11e9-8cd8-a3916296c3ef.png)
