### ISSUE TITLE
About and guidelines fields are not clickable on Firefox

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1857]
## Steps to reproduce

1. Log into the dapp on Firefox
2. Navigate to the admin panel for a colony
3. Try to edit the "about" or "guidelines" sections

## Expected behaviour

User should be able to edit these fields.

## Actual behaviour

These fields are unclickable and can only be reached using tabs.

## Feedback links
https://help.colony.io/hc/en-us/community/posts/360034963734-Fields-not-clickable-

**Comment by rdig** [comment]
This is very valid, but we don't support Firefox yet.

Note that even most login methods don't work on Firefox as of right now, so while this is a valid _(cross-browser, not functionality)_ issue, it will be closed for now.

**Comment by auryn-macmillan** [comment]
Thanks for clarifying that. Which browsers do we currently support?

**Comment by rdig** [comment]
Just Chrome

**Comment by rdig** [comment]
Even Brave, while Chromium-based, has been known to break parts of the dApp _(but mostly css styles, so not that big of a deal)_
