### ISSUE TITLE
Can't assign funding permission in subdomain

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1883]
## Steps to reproduce

1. Create a subdomain
2. Try to assign the funding permission in that subdomain to a user

## Expected behaviour

Permission should be assigned

## Actual behaviour

![image](https://user-images.githubusercontent.com/8453294/65908233-029cb480-e394-11e9-90fc-ebbf16cf616e.png)

**Comment by sprusr** [comment]
This will be solved by https://github.com/JoinColony/colonyJS/pull/442. The issue can be closed once that's merged and the dApp is using a colonyJS release which includes it.
