### ISSUE TITLE
Gas Station Dependencies for Group Permissions

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1899]
## Steps to reproduce

1. Edit permissions
2. Remove multiple permissions at one time
3. Transactions are dependent on each other but do not need to be

## Expected behaviour

* Adding or removing permissions do not need to be dependent on each other. The user should be able to sign multiple transactions without waiting for another one to end. 
* The only exception is when removing the root permission. Removing root should always come last and be dependent on the other transactions being done. This is because removing root may not allow the user to remove the other permissions (if they are removing permissions from themselves). 

## Actual behaviour

* Removing root comes first and blocks the user from removing other permissions. 

## Suggestions (optional)

* Permission contracts should not be dependent on each other except when removing root from your own user. (what an edge case!)

**Comment by itspatch** [comment]
@ceolson01 should be familiar with this issue.

**Comment by chmanie** [comment]
Is it really that important that the setting of permissions has a certain order (apart from the edge case you're describing). Because that's a lot of work to do for an unreasonable gain (I guess?). Putting the removal of the ROOT role to the end is easy to do though

**Comment by ceolson01** [comment]
Based on our testing & conversation about this, I think all that really matters is removal of `ROOT` being last 👍

**Comment by chmanie** [comment]
Cool, I did this in here: https://github.com/JoinColony/colonyDapp/pull/1907/commits/d0e1b8b550a4868ccc22eab6c59be43e4ebcca93
