### ISSUE TITLE
Can't finalize task funded with ETH

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1900]
## Steps to reproduce

1. Create a task funded with ETH
2. Try to finalized it

## Expected behaviour

Task should finalize and ETH should be received by assignee

## Actual behaviour

Cannot finalize task
![image](https://user-images.githubusercontent.com/8453294/66820585-f45fa400-ef0e-11e9-9e44-001a2a721cab.png)

Clickling the "retry" button has the same result.

**Comment by collinvine** [comment]
@auryn-macmillan are you sure you claimed the ETH into the pot? Can you show what your Token and TX screens look like in the admin page?

**Comment by auryn-macmillan** [comment]
I don't have admin permissions in that colony, so I can't see the tokens tab.
But I believe that [this](https://etherscan.io/tx/0x5e0bef900785218c4ea29d39b53374bcd99eef07c6fdc0a2e443f9a583e626b3) is the transaction that sent ETH to the colony and that [this](https://etherscan.io/tx/0x9648093430ece46d7e364b7eac691c26353eb1d3046230385c058fc35f161763) is the transaction that claimed the ETH.

Given that it has not been possible to move tokens between domains as of yet, I can only assume that that the root domain had enough ETH.

**Comment by chmanie** [comment]
This seems to be fixed in #1907
