### ISSUE TITLE
Colony Founder Info Fails to Load

### ISSUE THREAD

**Issue by lightnode** [JoinColony/colonyDapp#1901]
## Steps to reproduce

1. Go to: https://colony.io/colony/joy

## Expected behaviour

Colony Founder Profile Image, Name, and Address should load

## Actual behaviour

![founder-missing](https://user-images.githubusercontent.com/44594862/66939418-a333db00-f008-11e9-830d-76a0a9cf7db0.gif)

This just recently started to happen in the last couple of days. I'm hesitant to stage a number of new tasks I have queued up if going into `Recovery Mode` or something else may fix the issue.

**Comment by rdig** [comment]
While this is a valid issue, it's only applicable in the current version.

The new, upcoming version, `1.1.0`, no longer suffers from this issue:

![Screenshot from 2019-10-28 14-12-54](https://user-images.githubusercontent.com/1193222/67677585-159fa600-f98d-11e9-950a-6919c3d7cd1d.png)

So, in an effort to conserve dev resources, I'll close this issue.
