### ISSUE TITLE
Implement domain level permissions for tasks

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyDapp#1909]
### Story

As a user interacting with a task I want to see in what way I can interact with a task depending on my permissions/roles in the colony.

### Description

This issue might serve as a continuation of #1800. Currently we're somewhere in between states when it comes to task based permissions.We have to work out a logic for the particular interactions with a task based on the current user's permissions. At the moment we're just using the ROOT domain for all of the checks. Keep in mind that this is applicable to the current version of the task system (ddb + payments) only.

Following, when talking about permissions, we include the permissions inherited from parent domains.

Here's a list of things that need adjustments:

*Creating a task:*
- Because all of our permissions are domain based now a task must _always_ have a domain
- User creating a task has to have the `ADMINISTRATION` role in the target domain
- If the user does not have the `ADMINISTRATION` role in the domain selected on the left the buttons for creating a task are disabled
- For now: when clicking one of the "new task" buttons, the task is created in the domain that is selected on the left

*Adding / changing task funding:*
- A user can only add or change funding of a task if:
  - they have the `FUNDING` *and* `ADMINISTRATION` role in the domain the task is in

*Changing the domain of a task:*
- The domain of a task can't be changed or
- 🌮-bonus: the domain of a task can only be changed if (AND linked):
  - the funding is not set
  - the target domain is a domain the user has the `ADMINISTRATION` role in

*Setting the assignee*
- The assignee can be set by a person who:
  - Has the `ADMINISTRATION` role in the domain the task is in

*Setting the skill*
- The assignee can be set by a person who:
  - Has the `ADMINISTRATION` role in the domain the task is in

*Editing a task (title + description):*
- The person editing a task has to be:
   - A person having the `ADMINISTRATION` role in the domain the task is in

*Cancelling a task:*
- The task can be cancelled by a person who:
  - Has the `ADMINISTRATION` role in the domain the task is in

*Finalizing a task:*
- The task can be finalized by a person who:
  - Has the `ADMINISTRATION` *and* `FUNDING` role in the domain the task is in

I've also noticed some inconsistencies in the current implementation. Some things can only be done by the task manager (which presumably is the same person as the task creator currently). We should be more consistent here (maybe for now not differentiate between the two roles?)

In general we're trying to mimic the role for the actual task functions on the colony client for the ddb and also reflect that in the UI. This might be helpful: https://colony.io/dev/docs/colonyjs/topics-colony-roles#colony-client

*Open questions:*
- Should any (more) of the actions be limited to the task creator only?
- What if a user loses any of the permissions needed during the lifetime of the task?

### This issue is complete when...

- [ ] Checks for all of the above cases are properly implemented
- [ ] The UI uses these checks
- [ ] The checks using the old permissioning system are cleaned up (remove `isFounder`, `canAdminister` where applicable

**Comment by auryn-macmillan** [comment]
I tend to think that whether or not the user is the task creator is irrelevant and should not be checked for at all.

**Comment by collinvine** [comment]
> Adding / changing task funding:
> A user can only add or change funding of a task if (AND linked):
> * they are the task creator*
> * they have the ROOT or ADMINISTRATION role in the domain the task is in

I don't think this is correct. Changing funding requires `funding` permission in the target domain, and that's it.

**Comment by collinvine** [comment]
I also agree with @auryn-macmillan that being the task creator doesn't hold any special permission beyond the permissions we have already.

**Comment by collinvine** [comment]
> The task can be finalized by a person who (AND-linked):

Maybe we should look into this? I wonder if finalizing, which causes a movement of funds, requires `funding` permission. Does anyone know?

**Comment by lightnode** [comment]
Just tested.

I can create a task and add funding as with `Administration` permissions, but get this error when trying to finalize.

![finalize-payment](https://user-images.githubusercontent.com/44594862/67965096-643c8280-fbcf-11e9-969b-bac13d7ef31f.png)

**Comment by collinvine** [comment]
This isn't implemented yet so not testable, more so related to how the contracts function. We got an answer from Alex confirming this:

> Okay, so is this the way it works?
> - `administration` to create / manage
> - `funding` to add / edit / move funding
> - `admin` && `funding` to finalize

**Comment by auryn-macmillan** [comment]
> This isn't implemented yet so not testable
It is implemented at the root level though. So the permissions can be tested there.
I just tried it out on goerli and got the same result as chase, which confirms (somewhat redundantly) what you suggested earlier.

> Okay, so is this the way it works?
> 
> * administration to create / manage
> * funding to add / edit / move funding
> * admin && funding to finalize

**Comment by itspatch** [comment]
Movement of funds requires the funding permission. But once those funds are moved into the task pot, I do not believe you need the funding permission to finalize the task. The problem is, we are using a one transaction extension where we don't move the funds into the task pot, the extension does. 

To further complicate matters, the only point in time that permissions actually matter, is whoever finalizes the task needs to have the correct permission. And at the point in time when the task is finalized, the domain needs to have the correct amount of funding. 

I'm not sure what permission is needed to call the one transaction extension though. Does @kronosapiens or @chmanie know what permission is needed to finalize the task using the one transaction extension? Who is allowed to call that extension and where does the funding need to be?

**Comment by itspatch** [comment]
What is complicated here is that we are using the one transaction method, not the actual task. So technically, anyone can change the domain on the task while it's on the DDB. But not anyone can finalize the task.

**Comment by auryn-macmillan** [comment]
> The problem is, we are using a one transaction extension where we don't move the funds into the task pot, the extension does.

Good point.

> I'm not sure what permission is needed to call the one transaction extension though.

When I tested it in QA just now, I needed both the administration and funding permission to finalize the task.

**Comment by itspatch** [comment]
>When I tested it in QA just now, I needed both the administration and funding permission to finalize the task.

Is that because you first have to move funds?

**Comment by auryn-macmillan** [comment]
> Is that because you first have to move funds?
I assume so. The funds were already allocated on the dapp, but I guess no funds were allocated on chain yet. So the 1tx method needed to allocate funds and finalize the task.

**Comment by itspatch** [comment]
>So the 1tx method needed to allocate funds and finalize the task.

I thought the 1tx method had funding permission? So if _it_ is moving the funds, it shouldn't require the user to move the funds.

**Comment by auryn-macmillan** [comment]
> I thought the 1tx method had funding permission? So if it is moving the funds, it shouldn't require the user to have funding permission.

My assumption is that it checks the permissions of the user calling it.

**Comment by kronosapiens** [comment]
Part of the issue here may be that payments are currently stored off-chain in orbitdb, until the moment they're actually executed. As far as on-chain permissions are concerned, the only thing that matters is when the payment is executed, and then the person making the tx needs both `admin` and `funding` roles.

**Comment by itspatch** [comment]
@kronosapiens is that admin and funding role within the domain the task is in?

**Comment by itspatch** [comment]
This is definitely confusing. Because now we have these permissions that don't line up with how the task actually works :(

**Comment by kronosapiens** [comment]
@itspatch can you say more about that? Maybe I'm not appreciating the issue here.

_In general_
- `administration` for task operations (creating, finalizing, etc)
- `funding` for moving funds from A to B (including into a task pot)

_One Tx Payment_
- Since there's only one tx, which does all of the above ^^, it needs both permissions
- The contract needs permissions in the colony, but also it checks to see the user has the permissions.

**Comment by kronosapiens** [comment]
Also @chmanie `Changing the domain of a task` is no longer an issue -- domains are immutable from the start now: https://github.com/JoinColony/colonyNetwork/pull/713

**Comment by chmanie** [comment]
@kronosapiens it depends. In the dapp we used to have some sort of "draft-mode" which _will_ allow you to change the domain until it is commited to the blockchain. For now I'll disable this feature though.

**Comment by itspatch** [comment]
Right that's what I meant, we use draft mode in the dApp. And I think we let anyone with administrative permission create a task in draft mode. But they really need both administrative and funding permission to finalize the task. And we don't make that clear in the dApp.

**Comment by kronosapiens** [comment]
Yeah that makes sense. Sounds like also a legacy of when we had only the "Founder" and "Admin" roles -- it didn't matter then since `administrative` and `funding` always came together. It also sounds like the issue goes away if we move away from `OneTx`, since then there's no conflict with one person creating/finalizing the task and someone/something else funding it.
