### ISSUE TITLE
Users with inherited permissions aren't displayed

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1914]
## Steps to reproduce

1. Navigate to the permissions tab
2. Select a subdomain
3. Click on a user or the "add role" button

## Expected behaviour

All of the users with permissions, either direct or inherited, should be displayed in the list.

## Actual behaviour

Users with inherited permissions are not displayed until after you interact with the rolls modal.
![users appear after click](https://user-images.githubusercontent.com/8453294/68237877-16ac8500-ffd6-11e9-8c0b-15dc47e4478e.gif)

**Comment by rdig** [comment]
@chmanie I'm assigning this to you, as this will be closed by #1907
