### ISSUE TITLE
"assigned to you" and "created by you" show completed tasks

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1917]
## Steps to reproduce

1. Take a squiz at a colony with multiple tasks, some assigned to you, some created by you,, some completed, and some assigned and created by others,
2. Try changing the filters.

## Expected behaviour

The "assigned to you" and "created by you" filters should not show completed tasks.

## Actual behaviour

The "assigned to you" and "created by you" filters show completed tasks.
![completed tasks show up in wrong place](https://user-images.githubusercontent.com/8453294/68443300-8458dc80-01a1-11ea-88d3-a400ad237a0f.gif)

## Suggestions (optional)

While we're changing stuff here, I would also like to suggest some copy changes.
"Assigned to you" --> "Assigned to me"
"Created by you" --> "Created by me"

This would need to be approved by @itspatch or @collinvine first though. I haven't had a look through the rest of the application to see if this would feel inconsistent, but it would feel more personal in my opinion.
Asana is a good example of this.
![image](https://user-images.githubusercontent.com/8453294/68443629-83747a80-01a2-11ea-8cdd-a6d592d449e0.png)

**Comment by rdig** [comment]
Closed by #1927
