### ISSUE TITLE
Create new suggestions

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1920]
### Story

As a user of Colony, I want to add Suggestions to colonies I participate in, so that I can give feedback on how to improve that colony.

### Description (optional, but useful!)

Any user can add a new suggestion to a colony. To create a suggestion, the user hits `return` from the Suggestion input field. They should not be allowed to create an empty string (no error message needed, see how Slack handles this).

New suggestions are added to the top of the list (reverse chronological sorting).

Character limit at **90char**. If text  is too wide for screen, then text is truncated with an ellipses and shown on hover.

### Design (optional, might not be applicable)

[Figma link](https://www.figma.com/file/6UoE1xwGiEIiDyyxPpotqR/Community-Work-Platform-Sprint?node-id=531%3A36720&viewport=980%2C567%2C0.0989677682518959)

![Add Suggestion](https://user-images.githubusercontent.com/15755488/68617225-a8efd580-047b-11ea-8442-d0d3ffb8613c.png)

**Taco - add character limit, preferably re-use already existing feature in task title**

<img width="1440" alt="Add Suggestion@2x" src="https://user-images.githubusercontent.com/20819402/68924518-523b1200-0781-11ea-8e9f-7696bc80cc61.png">

### This issue is complete when...

- [ ] The user can click `return` from the input field to create a new suggestion
- [ ] The user cannot submit an empty string as a suggestion
- [ ] Title char limit is set to 90 (same as task)
- [ ] Long names are truncated with an ellipses
- [ ] Hover state on long names to show all text
- [ ] The list is sorted in reverse chronological order (new suggestions added to the top of the list)

**Comment by Karol-colony** [comment]
No character limit. The full string is shown on hover, and text is truncated with an ellipses. - I would consider to keep character limit 90 characters, same way as with task UI. It might be not consistent if we introduce task UI or conversion from suggestion to a task and generate bugs.

**Comment by collinvine** [comment]
> It might be not consistent if we introduce fullscreen UI or conversion from suggestion to a task. I see a risk for potential bugs being generated.

Good point, @Karol-colony
