### ISSUE TITLE
Change status of suggestion

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1921]
### Story

As an admin of a colony, I want to change the status of a suggestion, so I can provide feedback on its state.

### Description (optional, but useful!)

Users with the `administration` permission in a colony (domain) is able to change the status of a suggestion. The options are:

- Open (default)
- Not planned 
- Accept
- Delete (also available to the Suggestion author)

All suggestions are open by default. They can be changed by selecting an item from a menu.

`Not planned` can be changed to any other status.

`Accepted` cannot be changed to Open or Not planned. It can be deleted, though.

`Accept` and `Delete` require double confirmation. (Designs below).

`Accepted` and `Not planned` have labels on the card.

### Design

[Figma link](https://www.figma.com/file/6UoE1xwGiEIiDyyxPpotqR/Community-Work-Platform-Sprint?node-id=531%3A37139&viewport=632%2C849%2C0.157741978764534)

**Menu for admins**
<img width="1440" alt="Drop down to accept suggestion@2x (5)" src="https://user-images.githubusercontent.com/20819402/68835721-f7d67e80-06b8-11ea-93a0-03281f5a4fff.png">

**Menu for author**
If a user is an author && doesn't have `administration` permissions, then this is their menu:

![Screen Shot 2019-11-11 at 1 18 21 PM](https://user-images.githubusercontent.com/15755488/68621920-bf9b2a00-0485-11ea-8173-aee11a189354.png)

**Labels**
![Screen Shot 2019-11-11 at 1 17 16 PM](https://user-images.githubusercontent.com/15755488/68621845-97abc680-0485-11ea-9a1c-61a9a1936601.png)

**Double Confirmation - Conversion**
<img width="1440" alt="MacBook Pro 2 76@2x" src="https://user-images.githubusercontent.com/15755488/68978039-9c86b800-07ae-11ea-96d5-ba518e47a3f0.png">

**Double Confirmation - Delete**
<img width="1440" alt="Drop down to accept suggestion@2x" src="https://user-images.githubusercontent.com/15755488/68978068-a7414d00-07ae-11ea-88b2-04aab1860ca3.png">

**Regular user view - can't see dropdown anymore for accepted suggestion**
<img width="1440" alt="Drop down to accept suggestion@2x (3)" src="https://user-images.githubusercontent.com/20819402/68835345-1b4cf980-06b8-11ea-9cf7-30062b35c307.png">

**Admin view - limited menu after Accepted, only delete**
<img width="1440" alt="Drop down to accept suggestion@2x (4)" src="https://user-images.githubusercontent.com/20819402/68835440-61a25880-06b8-11ea-87ac-86ec0e90c59c.png">

**Admin view - menu after Not planned - possibility to reopen**
<img width="1440" alt="Drop down to accept suggestion" src="https://user-images.githubusercontent.com/20819402/68835420-53543c80-06b8-11ea-8cd4-cf611f50036e.png">

### This issue is complete when...

- [ ] The menu is implemented and visible for users with `administration` permissions
- [ ] The menu with `delete` option is visible to the suggestion author
- [ ] The menu is not visible to non-admins && non-authors
- [ ] The labels are displayed for either Not planned or Accepted suggestions
- [ ] Accept or Delete prompt a double confirmation
- [ ] Accepted suggestions cannot be changed to a different status (they can be deleted)

**Comment by Karol-colony** [comment]
_Disabled menu after Accepted_
I would suggest not to disable menu, but remove other actions. So, there would be only deleted, without accepted / not planned.

**Comment by Karol-colony** [comment]
@collinvine  review please

**Comment by collinvine** [comment]
Looks good, @Karol-colony but the dialogues need better copy. I'll add that to my to-do.

**Comment by Karol-colony** [comment]
Great thanks, please add a comment or adjust copy on Figma

**Comment by collinvine** [comment]
@Karol-colony done and re-uploaded the images.

**Comment by Karol-colony** [comment]
Thanks, copy is great
