### ISSUE TITLE
Upvote a suggestion

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1922]
#1598  Specification

### Story

As an end user, I want to upvote a suggestion, so I can give support to good ideas.

### Description (optional, but useful!)

Suggestions can be upvoted by any colony user. Clicking the upvote button adds an upvote and increments the counter. Clicking it again removes the upvote and decrements the counter.

Suggestions can be upvoted / un-upvoted no matter what the status is.

### Design

[Figma link](https://www.figma.com/file/6UoE1xwGiEIiDyyxPpotqR/Community-Work-Platform-Sprint?node-id=531%3A37334&viewport=2134%2C-6255%2C1)

**Upvote**
<img width="1440" alt="Upvote@2x (1)" src="https://user-images.githubusercontent.com/20819402/68651300-61268800-0527-11ea-9742-1320b53a98ca.png">

**Hover state** 
<img width="1440" alt="upvote@2x" src="https://user-images.githubusercontent.com/20819402/68651265-51a73f00-0527-11ea-9a55-cc6965ce10b2.png">

**Upvoted**
<img width="1440" alt="Upvote-Upvoted@2x" src="https://user-images.githubusercontent.com/20819402/68835799-28b6b380-06b9-11ea-9b90-eb6b75f3c8bf.png">

**Focus (accessability/keyboard support)**
<img width="1440" alt="Upvote - Focus@2x" src="https://user-images.githubusercontent.com/20819402/68835843-471caf00-06b9-11ea-8c45-99116e8b1c9a.png">

### This issue is complete when...

- [ ] Users can upvote a suggestion
- [ ] Users can remove their upvote
- [ ] The counter increases or decreases appropriately

**Comment by Karol-colony** [comment]
@collinvine  review please

**Comment by collinvine** [comment]
Looks good, @Karol-colony
