### ISSUE TITLE
Filter suggestions (🌮)

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1923]
### Story

As a colony user, I want to filter suggestions based on status, so I can make the list more readable

### Description (optional, but useful!)

_🌮 This can be optional. If you want, we can ignore any type of filtering to begin, and add this later!_

The user can filter by status:

- All (default view)
- Open
- Accepted
- Not planned

Choosing a filter will only show suggestions that match the selected status (in a given domain). 

### Design

[Figma link](https://www.figma.com/file/6UoE1xwGiEIiDyyxPpotqR/Community-Work-Platform-Sprint?node-id=531%3A37334&viewport=4005%2C-6201%2C1)

Not planned
<img width="1440" alt="Filter@2x" src="https://user-images.githubusercontent.com/20819402/68651671-283ae300-0528-11ea-9912-ea4626c52da0.png">

Accepted
<img width="1440" alt="Filter@2x (1)" src="https://user-images.githubusercontent.com/20819402/68651677-2a04a680-0528-11ea-8f64-5a8c8d8f078c.png">

All
<img width="1440" alt="Drop down to accept suggestion@2x" src="https://user-images.githubusercontent.com/20819402/68651679-2b35d380-0528-11ea-882f-70273f5d6522.png">

Open
<img width="1440" alt="Drop down to accept suggestion@2x (1)" src="https://user-images.githubusercontent.com/20819402/68651685-2cff9700-0528-11ea-8f7e-6bb1c7c6486d.png">

### This issue is complete when...

- [ ] The filter is implemented and filters suggestions that match the selected filter option

**Comment by Karol-colony** [comment]
@collinvine  review please

**Comment by collinvine** [comment]
Looks good, @Karol-colony
