### ISSUE TITLE
Some tasks show up in "my tasks" but do not show up in the colony view

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1934]
## Steps to reproduce

I'm not entirely sure how to reproduce this issue.
The tasks were showing up in the colony when I created them last week. Now when I log in to colony, those tasks are no longer accessible from the colony page.

## Expected behaviour

Tasks should remain visible in the colony.

## Actual behaviour

*sorry for the giant GIF*
![Peek 2019-12-02 08-47](https://user-images.githubusercontent.com/8453294/69964826-22aa3a80-14e1-11ea-8e1c-9c947aefe335.gif)

**Comment by auryn-macmillan** [comment]
The tasks display fine in version 1.0.5 of the dapp (the version currently deployed on staging).
![image](https://user-images.githubusercontent.com/8453294/69970360-1aa3c800-14ec-11ea-8ee7-f889c61198f7.png)

**Comment by rdig** [comment]
Is this a filtering issue still ? 

Or do they disappear completely _(Ie: you can't see them with any filters on: `Completed`, `Assigned`, etc...)_

**Comment by auryn-macmillan** [comment]
Can't see them with any of the filters.

**Comment by rdig** [comment]
Right. That means it's _(most likely)_ a permissions / domains issue.

I'll try to investigate it when I'll have spare moment.

**Comment by rdig** [comment]
I can no longer reproduce this on the current deployment of the dapp.

Closing this, but feel free to re-open it if the issue presents itself again.

**Comment by auryn-macmillan** [comment]
No worries, mate. I think it was caused by the same issue as #1996, so was probably fixed by https://github.com/JoinColony/A/pull/38
