### ISSUE TITLE
User without username can create tasks

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1935]
## Steps to reproduce

1. Assign admin permission to an address that has not claimed a username
2. Navigate to the colony where permissions were assigned and authenticate with the newly permissioned account
3. Click the "New Task"

## Expected behaviour

Users who have not created a username should not be able to create tasks (or write any other data to orbitDB)

## Actual behaviour

Accounts with the admin permission, but without an ENS subdomain, can create tasks in the colony where they are permissioned. If the account claims a username after the fact, then they can no longer see any of the tasks they created in their "my tasks" section.

*note: I have not been able to replicate this on QA as the dapp crashes whenever I paste an ethereum address into the "new role" selector.

**Comment by chmanie** [comment]
cc @JamesLefrere to have this fixed on the server
