### ISSUE TITLE
Cannot finalize task in domain 2

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1936]
## Steps to reproduce

1. Authenticate with a user that has all permissions in the root domain and none in any subdomains
2. Create a task in domain 2 of a colony
3. Try to finalize it

## Expected behaviour

You should be able to finalize the task since you have permissions in the root domain.

## Actual behaviour

You cannot finalize the task

![image](https://user-images.githubusercontent.com/8453294/70295539-663cc700-17b5-11ea-9a84-ff7ae26a583c.png)

![can't finalize tasks in domain 2](https://user-images.githubusercontent.com/8453294/70295554-705ec580-17b5-11ea-825a-0afc1551039a.gif)

The really weird thing is that I had no issues finalizing tasks in domains 3 and 4, only in domain 2.

**Comment by auryn-macmillan** [comment]
Another oddity to add to this one. I was able to finalize the task while logged in as another user that had identical permissions, minus the "arbitration" and "recovery" permissions.

**Comment by rdig** [comment]
I cannot replicate this with the in the current codebase. Everything seems to be working as expected.

![demo-finalize-task-in-subdomain-with-permissions](https://user-images.githubusercontent.com/1193222/72911387-a692dd00-3d42-11ea-9709-ecc1d249b320.gif)

Closing.

**Comment by rdig** [comment]
Please try to re-create the permissions on that user (remove then, then add them again), then try again

**Comment by auryn-macmillan** [comment]
Wait.... I'm an idiot. I had the admin permission in the sub-domain. Removed that and now everything is working as expected.
Sorry about that.

**Comment by rdig** [comment]
Don't worry about it.

Glad we got it sorted. :+1:
