### ISSUE TITLE
Can't create colony with external native token: Token Data Not Found

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1959]
## Steps to reproduce

1. Try creating a colony with a an external native token

## Expected behaviour

You should be able to progress through colony creation without issue

## Actual behaviour

When you enter the token address, you get this error message.
`Token data not found. Please type in token details`
![image](https://user-images.githubusercontent.com/8453294/72569701-009a2b00-3889-11ea-966d-200e91c5435d.png)

If you continue on, you are able to sign the first transaction, but the interface does not register when the transaction is confirmed and progress to the next step.

**Comment by chmanie** [comment]
I found the issue. The problem is that with an external token, the server is asked whether the token exists first. The server doesn't know about it, obviously. This is a bit of a problem that we have to solve. I don't know how external tokens should be created on the server and by whom.

**Comment by rdig** [comment]
FIY I created one manually when I recovered a colony

**Comment by auryn-macmillan** [comment]
> the server is asked whether the token exists first
Not sure what you mean by this.
Can't we just pull the token information from the contract?

**Comment by rdig** [comment]
> Can't we just pull the token information from the contract?

Not easily.

We can after the colony is created and we have access to that token via our `TokenClient`

However, this issue is solved by @chmanie 's #1961 along with us passing in an Ethplorer API key to the docker image on the next deployment

**Comment by rdig** [comment]
Actually not really.

#1961 is a minor part in this, but turns out that #1967 is the actual proper solution for this
