### ISSUE TITLE
Subdomain balances are not displayed in the Sidebar

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#1970]
Token balances are displayed in 'all domains' and 'root' but not in any subdomains.

![Peek 2020-01-14 15-23](https://user-images.githubusercontent.com/1193222/72686491-1d8b6400-3afe-11ea-8855-a978523d4833.gif)

Original place where it was reported: https://joincolony.slack.com/archives/C7HNTLE3T/p1579033561254600

**Comment by rdig** [comment]
This was fixed by @ceolson01 's af75c22 but didn't make it in production.

It will be picked up during the next deploy.

**Comment by auryn-macmillan** [comment]
@rdig eta for the next deploy?

**Comment by rdig** [comment]
There isn't one yet.

It will most likely be when we push _Suggestions_
