### ISSUE TITLE
DAI and other external tokens are not displayed in the dapp

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1978]
## Steps to reproduce

1. Send an external token (one that was not created by a colony) to a colony

## Expected behaviour

A transaction with the token should show up in the transaction feed. Once it has been claimed, the token should show up in the colony's balance.

## Actual behaviour

DAI and other external tokens are not displayed in the dapp at all. They can't be claimed in incoming transactions and and existing balances are not displayed.

My guess is that this is also related to #1967.

**Comment by rdig** [comment]
So this issue indeed exists, and I could successfully replicate it locally:

![Screenshot from 2020-01-22 19-29-18](https://user-images.githubusercontent.com/1193222/72918254-0773e280-3d4e-11ea-98f5-1c6345c8aaf7.png)

This will be solved by both #1967 and JoinColony/colonyServer#34 once they are deployed.

The issue arises when the specific token does not have an entry which the Dapp can pull information from.

As a quick patch until the above mentioned issues are fixed, I've manually added an entry with the DAI token, so your transaction will show up and you'll be able to claim it.

![Screenshot from 2020-01-22 19-36-40](https://user-images.githubusercontent.com/1193222/72918615-997beb00-3d4e-11ea-887a-2e953814c731.png)

**Comment by auryn-macmillan** [comment]
I still don't see incoming transactions in DAI for some reason, even though I can now see DAI balances in the colony.

Also, I noticed that there ETH now shows up twice, both in the Burn Signal colony and the screenshot you posted above.

**Comment by rdig** [comment]
> Also, I noticed that there ETH now shows up twice, both in the Burn Signal colony and the screenshot you posted above.

This is a separate issue that will be as well resolved when we refactor the way token logic works in #1967
