### ISSUE TITLE
Token balances not displayed in subdomains

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1979]
## Steps to reproduce

1. Create a colony with a subdomain
2. Send some tokens to the subdomain

## Expected behaviour

Token balances for the subdomain should be displayed in the right gutter where they are displayed for the "root domian" and "all domains"

## Actual behaviour

![balances not displayed](https://user-images.githubusercontent.com/8453294/72757539-39dedd80-3b9e-11ea-9e72-273ae9d563a0.gif)

**Comment by rdig** [comment]
Please don't re-open issues already reported: #1970

In this case, this is fixes, and will make it into production during the next release cycle.

**Comment by auryn-macmillan** [comment]
Ah, my bad. Didn't realize there was already an issue for it.
