### ISSUE TITLE
Make Suggestions the first tab in a domain

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1989]
### Description (optional, but useful!)

Make Suggestions the first tab, so that tab ordering is:

1. Suggestions
2. Tasks
3. Transactions

### Design 

![image](https://user-images.githubusercontent.com/15755488/72942242-d08ad600-3d27-11ea-9ac7-4d5a7ff242b6.png)

### This issue is complete when...

- [ ] The Suggestion tab is the first tab in each domain

**Comment by ceolson01** [comment]
Was completed via #1990. Was later reverted to have tasks first because of the mint tokens form after colony create.

Closing.
