### ISSUE TITLE
Non-existing colony just keeps loading

### ISSUE THREAD

**Issue by ExperimentsWithCode** [JoinColony/colonyDapp#2004]
## Steps to reproduce

1. Follow link: colony.io/colony/burnsignal
2. Redirects to colony.io/connect
    * Ensured sheilds are down
3. Asks how I would like to connect. Select Metamask (currently logged into  metamask)
4. Next page, asks if I would like to continue. Select continue. 
5. Metamak signature request pops up. I sign.
6. Brings back to colony.io/colony/burnsignal, but never gets past "loading"
7. Browser restarts and PC restarts did not resolve the issue

[Screenshot](https://imgur.com/a/ACW4dz7)

(Tried on both Brave and Firefox)

## Expected behaviour

* ~Expect to proceed past loading screen~ Expected to see some sort of error message that the colony was not found.

## Actual behaviour

* Stuck on loading screen.

## System info:
* Browser: Brave - Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
* Alt Browser: Firefox - Version 72.0.1 (64-bit)
* OS: Pop!_OS 19.10 (linux distro based on based on Ubuntu 19.10)

**Comment by chmanie** [comment]
The actual colony address for the burn signal colony is https://colony.io/colony/burn

Nevertheless the UX is pretty bad if a colony was not found. I'll change the title of this to make us handle this case properly (redirect to 404)
