### ISSUE TITLE
User with administration role lacks related ui controls

### ISSUE THREAD

**Issue by igorline** [JoinColony/colonyDapp#2021]
Hey, I'm testing the UI of the colony dApp, located at `https://qa.colony.io/` and seems like I'm stuck with goerli testnet.

## Steps to reproduce

1. Created new colony using metamask
2. Added new administration role in colony settings
3. Changed account to that new administrator address

## Expected behaviour

* User should be able to create new tasks and enter colony settings

## Actual behaviour

* User sees basic UI available to anybody

----

In the console I'm also receiving error `Error: GraphQL error: User with address '0x5....c' not found`

**Comment by auryn-macmillan** [comment]
https://qa.colony.io is the goerli version. If you want the mainnet version, try https://colony.io/connect.

**Comment by auryn-macmillan** [comment]
Turns out that `0x5....c` had not created a username/ENS domain, so they were unable to interact with the application.

**Comment by rdig** [comment]
> Turns out that 0x5....c had not created a username/ENS domain, so they were unable to interact with the application.

This is something I need to look into then
