### ISSUE TITLE
Add 'Community' tab with members list to each Colony

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#2022]
### Story

When contributor in a colony, I want to know what other users are in that colony, so my experience is more social and interesting.

As an admin of a colony, I want to see a list of members, so I can more effectively manage my colony.

### Description 
We want to surface a list of "members" within a colony. Right now, there's no way to see what other users—admins or contributors—are "in" that colony.

Do do this, we want to create a new **Community** tab (to the right of Suggestions, before Transactions) that shows a list of Members and their role:

- Founder (the user who created the colony)
- Admins (anyone with a permission in that colony)
- Members (anyone who has starred that colony and is not a founder or admin)

### Design

![image](https://user-images.githubusercontent.com/15755488/73697461-7416a780-4693-11ea-822d-bf20532e488c.png)

### This issue is complete when...

- [ ] The Community tab is implemented
- [ ] There's a list of users displayed
- [ ] Each user has their Role displayed on the list (`Founder`, `Admin`, `Member`)

### Suggestions

I'm not sure what the ideal ordering would be. Should the Founder and Admin be at the top of the list? Probably. 

If you're not a member, or not sure what that means, maybe we should provide copy saying something like "Star this colony to become a member" directly above the list (or elsewhere?). 

For an empty state we could have: "No members yet. Star this colony to become a member."

Here's a design as inspiration for that CTA when a user isn't a member yet:

![image](https://user-images.githubusercontent.com/15755488/73697914-a674d480-4694-11ea-92ea-f22275b44e93.png)

and after clicking:

![image](https://user-images.githubusercontent.com/15755488/73697974-c99f8400-4694-11ea-9739-8b2372c85d8a.png)

then it could disappear. These last parts are 🌮 by the way.

**Comment by rdig** [comment]
> For an empty state we could have: "No members yet. Star this colony to become a member."

We don't have an empty state. There's always at least a founder

**Comment by collinvine** [comment]
> We don't have an empty state. There's always at least a founder

I was thinking that but isn't there an edge case? What if that founder unsubscribe from the colony? 
Or would we always display admins and the founder regardless whether they are subscribed or not?

**Comment by rdig** [comment]
Hmmmm.... I'll check.

**Comment by rdig** [comment]
Turns out we prevent the founder from unsubscribing from his/hers colony.

So yeah, no empty state.

**Comment by rdig** [comment]
In the end... you were right, and I was wrong.

I chucked being unable to unsubscribe as a founder to an error I was experiencing locally...

So here's empty a empty state....

![demo-community-tab-empty](https://user-images.githubusercontent.com/1193222/73984646-d0065800-4941-11ea-80fb-f5aabcc048f4.gif)
