### ISSUE TITLE
Balance of colony not reflected in UI

### ISSUE THREAD

**Issue by czepluch** [JoinColony/colonyDapp#2027]
## Steps to reproduce

1. Send 1 DAI to my newly created colony (using the address provided by the UI)
2. Wait for tx to be mined
3. Check that the colony now has a balance of 1 DAI (but it doens't)
4. Check etherscan and see that the colony address does indeed have 1 DAI

## Expected behaviour

I expect that ETH or ERC20 tokens sent to a Colony will be reflected in the UI. Especially DAI as that's the example used in the intro.

## Actual behaviour

Balance of 0 DAI is shown in the UI

## More details
Let me know if you want the address of the colony or the txhash of the DAI transfer.

**Comment by rdig** [comment]
Hey there,

Tokens need to be claimed before they show up in the colony's pot balance. 

You can do that from the Colony home _Transactions_ tab.

**Comment by rdig** [comment]
You can find out more about funding your Colony in this knowledge base article: https://help.colony.io/hc/en-us/articles/360024589013-How-to-fund-your-colony

**Comment by czepluch** [comment]
Ah, clever. Makes sense. Not very intuitive though and I could have sworn that I already checked that tab once to see if the tx showed up there, but maybe not. Thanks for the swift response!
