### ISSUE TITLE
Add domain pot validation when clicking Finalize Task

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#2042]
### Story

When finalizing a task, I want to make sure I have enough money in the domain pot to pay out the task, so an error doesn't occur when completing the transaction.

### Description (optional, but useful!)

When finalizing a task in a domain that does not have enough funding, the transaction fails but with an uninformative error message:

![image](https://user-images.githubusercontent.com/15755488/74290788-c71dd980-4ce7-11ea-9c36-1fbc800ec1e2.png)

Instead, when clicking **Finalize Task**, we should check if the domain has sufficient funding in the pot to payout the task. If it does, proceed as normal! If it doesn't, throw up a modal letting the user know. 

### Design (optional, might not be applicable)

![image](https://user-images.githubusercontent.com/15755488/74290909-1bc15480-4ce8-11ea-8594-6835243f0527.png)

**Copy**

**Heading** Insufficient funds
**Body** There are not enough funds in the ${domainName} to payout this task. Please transfer funds into this domain before continuing.

**Comment by rdig** [comment]
This was already fixed by #2030 and it's in the pipeline for the next deployment.

Closing.
