### ISSUE TITLE
Can't assign task to ethereum address

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#2180]
## Steps to reproduce

1. Create a task
2. Try to assign it to an address that does not have an account in the dapp

## Expected behaviour

Task should be assigned to the address

## Actual behaviour

When you hit confirm, you are taken back to the task view, but nothing changes.
![Screenshot from 2020-06-02 16-43-31@2x](https://user-images.githubusercontent.com/8453294/83567828-3bc39080-a4f0-11ea-948b-7cdbebc13feb.png)

**Comment by xuhcc** [comment]
Thanks for creating this issue @auryn-macmillan 

It seems that the error comes from the server. My guess is that it happens when we try to subscribe a worker to notifications: https://github.com/JoinColony/colonyServer/blob/v1.3.0/src/db/colonyMongoApi.ts#L799

**Comment by chmanie** [comment]
Yes, I think you're on the right track there @xuhcc! This could be fixed on the server by implementing a check whether the assigned user has a username and only subscribe then. There's also another line where this needs to happen: https://github.com/JoinColony/colonyServer/blob/v1.3.0/src/db/colonyMongoApi.ts#L806
