### ISSUE TITLE
Coin Machine | Add "Learn More" link

### ISSUE THREAD

**Issue by ceolson01** [JoinColony/colonyDapp#2204]
### Description

When viewing the "Buy Tokens" page, we should add a link to help users learn more.

### Design

[Figma link](https://www.figma.com/file/fw2pDIUlkhCkJE79ZyTbjp/CoinMachine?node-id=327%3A3971)

<img width="1440" alt="Running Out@2x" src="https://user-images.githubusercontent.com/3052635/85307934-2c43c180-b476-11ea-99ec-41e1f5143a04.png">

### This issue is complete when...

- [ ] There is a link adjacent to the breadcrumbs which links to a "Learn More" page

**Comment by cobordism** [comment]
The link exists, but it only points back to the page itself. c.f. https://github.com/JoinColony/colonyDapp/issues/2737
