### ISSUE TITLE
Intermittently unable to activate tokens

### ISSUE THREAD

**Issue by willyogo** [JoinColony/colonyDapp#2600]
## Steps to reproduce

1. Connect wallet with inactive tokens and no tokens activated
2. Select any amount to activate
3. Approve tokens for transfer

## Expected behaviour

* After tokens are approved for transfer, user confirms a transaction to "activate" their tokens, and their tokens are activated

## Actual behaviour

* After tokens are approved for transfer, user is never prompted to approve the "activate" transaction and instead sees this error message: "Estimation error: The execution failed due to an exception."

![image](https://user-images.githubusercontent.com/26232238/125144194-55171300-e0da-11eb-8b11-7738d98956cd.png)

**Comment by willyogo** [comment]
Here is the address with the issue and the txid of 3 successful approvals, which I repeated while reproducing.

1. https://blockscout.com/xdai/mainnet/tx/0x923a9333954500b4a71b48928fefedded074d796dbd013b067dca6959bdfaac0
2.  https://blockscout.com/xdai/mainnet/tx/0x353e9641cd094c8a3f5bcf2cdc83abb003435912e151a9539935c4851a84589e
3. https://blockscout.com/xdai/mainnet/tx/0x0cfa7ed889b16985f3f737683e0e4113891d67628f3b1eb37de8d090c2611f46

**Comment by rdig** [comment]
Fixed by #2601
