### ISSUE TITLE
Force toggle is appearing on permissions modal

### ISSUE THREAD

**Issue by chadwittman** [JoinColony/colonyDapp#2619]
## Steps to reproduce

1. New Action
2. Manage Permissions

## Expected behaviour

* The absence of a force toggle on the permission modal

## Actual behaviour

* Screenshot: https://d.pr/i/dldFvM
* The presence of a force toggle

**Comment by rdig** [comment]
Is the Motions&Disputes extension installed?

If it is, then this is not a bug. It's expected behaviour.

**Comment by chadwittman** [comment]
Good question. Quick answer, it's disabled: https://d.pr/v/AmbI9y

More complicated answer:

* I did not spin up a new colony with a never-activated-motions/disputes-extension to test (I can, let me know)
* I did disable motions/disputes & tried making an expenditure, it acted as expected (no force toggle)
* I then recorded the video above, which showed a toggle for permissions (but not expenditures as an example)

**Comment by rdig** [comment]
Your video shows the Motion and Disputes extension as being enabled, in which case the toggle is correct in showing up.

Did you actually _uninstall_ Motions and Disputes or just _deprecate it_. Note that while _deprecated_ it's still available.

I think this is a case of miscommunication.

**Comment by chadwittman** [comment]
Good double check. I went ahead and spun up a brand new Colony on QA, which I did not enable the motions & disputes extension. In this state, I saw the force toggle. Screencast: https://d.pr/v/WaB1Ms

Seems probable this is a bug.

**Comment by rdig** [comment]
Seems so, yes.

What's the name of your colony ? _(In the future, please add it to your bug reports, as it makes tracking down or reproducing issues faster)_

**Comment by chadwittman** [comment]
Apologies, I didn't jot it down. I spun something up like Testing Permissions. I quick scanned my Chrome history, but the URLs are all generic — might be lost to history. Let me know if you'd like me to spin up a new one & share the name.

**Comment by rdig** [comment]
Don't worry about it, I'll try to find it myself
