### ISSUE TITLE
Whitelist extension - The template isn't helpful enough, should add example addresses

### ISSUE THREAD

**Issue by chadwittman** [JoinColony/colonyDapp#2625]
## Expected behaviour

* On https://qaxdai.colony.io/colony/test-whitelist
* The template should show a list as an example of how to format the whitelist addresses.
* Example: https://drive.google.com/file/d/1DUqVR1FHg9ZiBvchZOVpVFt6P0JlT_ST/view?usp=sharing

## Actual behaviour

* The template shows a single entry of "Whitelist Address", with no addresses listed.

## Suggestions (optional)

* Show a few addresses to give an example of what should be listed.
* Should we explicitly mention that we don't support .eth names? I checked this and it failed, but understand that is probably out-of-scope.

**Comment by chadwittman** [comment]
Looks like there's an ENS error upon submissions at the transaction level, that might resolve my 2nd comment regarding needing to mention it. Screen: https://d.pr/i/pch361

**Comment by ArmandoGraterol** [comment]
For the first point, this is something that should be brought up to Product as this is an improvement, not really a bug. They should be the ones to decide whether the template needs a few example addresses or not.

As for your second comment, that one _might_ be a bug but on the contract level, so I'll pass the info and screenshot you provided to Network. Thanks!

With that in consideration, I'll close the issue.

**Comment by ArmandoGraterol** [comment]
Got info back from Network. ENS, and therefore, `.eth` names don't exist on xDai. It's not supported, that's why you are getting an error.
