### ISSUE TITLE
Whitelist extension - Declined a valid whitelist csv

### ISSUE THREAD

**Issue by chadwittman** [JoinColony/colonyDapp#2626]
## Steps to reproduce

1. On https://qaxdai.colony.io/colony/test-whitelist
2. Upload a valid whitelist CSV https://drive.google.com/file/d/1DUqVR1FHg9ZiBvchZOVpVFt6P0JlT_ST/view?usp=sharing
3. Hit confirm

I also tested it with a file with no header in the template  https://drive.google.com/file/d/1f7w5hAgWiNaDP-GJIXljwM0tIm28S8gK/view?usp=sharing

Same result.

## Expected behaviour

* Transaction is completed

## Actual behaviour

* "Estimation error: The execution failed due to an exception." (screen: https://d.pr/i/TlFx5o)

**Comment by chadwittman** [comment]
Wanted to add that I tested this with the single input process & also getting same error.

I used these two xDai wallet addresses: 0x72d9e579f691d62aa7e0703840db6dd2fa9fae21 & 0xf1470817b5eA232dD9f96d7febe0717B0Fe6D75D

Is there an address or whitelist we can use for standardized QA? If not, can we use those two as the QA test?

Also, should the whitelist csv upload fail without a header row?

**Comment by rdig** [comment]
This is not to do with the addresses themselves. This something to do with the network contracts and transaction gas estimation.

If an address format fails validation, we show an error and prevent you from reaching the "send transaction" stage.

We're currently investigating this. Hang tight :)

**Comment by chinins** [comment]
I am closing this issue as it's resolved. After I reinstalled the extension in this colony it was all working fine.

My assumption is that the extension was enabled with Agreement only whitelist policy and in this case we can't upload any addresses, hence the error. There was another separate issue to modify UI to prevent this from happening which is in review right now.
