### ISSUE TITLE
Whitelist Extension - Accept ENS names as addresses.

### ISSUE THREAD

**Issue by cobordism** [JoinColony/colonyDapp#2629]
### Story

I wish to be able to add "aron.eth" as an address that has passed KYC.

### Description (optional, but useful!)

When I type "aron.eth" into the Whitelist extension as an address that should be on the whitelist, I am told "This is not a valid address"

[Screenshot](https://gateway.ethswarm.org/access/e3d544005aaa435417b6cae59fda0388e6fd6c49c70ad065e7b139a9c1f0673c)

**Comment by rdig** [comment]
We don't support ENS on XDAI

**Comment by cobordism** [comment]
Ah. ok.
I was thinking of ENS from mainnet - after all, isn't there supposed to be one global ENS namespace?
