### ISSUE TITLE
User profile not loading

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#2632]
The current user profile page `/user/username` is in an infinite loading state:

![Screenshot from 2021-07-30 12-51-00](https://user-images.githubusercontent.com/1193222/127639456-fee4274f-4dbb-45ff-ba84-0a98298d36c5.png)

However, the settings page, `/edit-user`, which uses basically the same logic in the background, loads fine.

This needs to be investigated as to what exactly is causing the infinite loader to show _(most likely a resolver not returning proper data)_, then fixed.

This fix should go directly into the `master` branch.

**Comment by thycommodore** [comment]
This appears to be resolved, I am unable to replicate it on product nor QA. Are we good to close this?

**Comment by rdig** [comment]
This is something I discovered developing locally, but I can't remember on which feature branch this was.

I would still like to keep it open, until we have had a chance to properly test it.
