### ISSUE TITLE
Update whitelistedUsers resolver

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#2639]
## Steps to reproduce

1. Install whitelist extension
2. Enable with KYC
3. Add user to the whitelist
4. Remove whitelist extension
5. Install one more time, now with agreement only
6. 

## Expected behaviour

* You shouldn't see old list of users (for agreement you actually shouldn't see any users

## Actual behaviour

* You will see old list of users (from old contract)

## Suggestions (optional)

* You need to use only those events connected to current installed whitelist contract address

**Comment by ArmandoGraterol** [comment]
Deprecated issue.

Tested it again following your steps, just in case, and yeah, it's fixed :+1:

Fixed by #2645
