### ISSUE TITLE
Example: Unable to log in with MetaMask wallet

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#2647]
## Steps to reproduce

1. Send tokens to a colony that you don't have permissions in

## Expected behaviour

* Should be able to claim tokens for the colony

## Actual behaviour

* Can't claim tokens
![image](https://user-images.githubusercontent.com/8453294/128793450-fe2e2e16-7026-415b-8099-d96de113471d.png)

**Comment by alicjakujawa** [comment]
To be able to claim you need to join colony AND has root permission, do you have root permission in this colony?

**Comment by auryn-macmillan** [comment]
Why would you need either of those two things?
On the contract it is a public function.
```solidity
function claimColonyFunds(address _token) public stoppable {...}
```

https://github.com/JoinColony/colonyNetwork/blob/b9806b6ea943dd860137be8248f35caecb398a63/contracts/colony/ColonyFunding.sol#L248
