### ISSUE TITLE
When new user is "joining" a colony, instead of redirecting to /landing after successful account create; send to the URL of the colony the user clicked "join" from

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2653]
### Story

As a user inviting someone to my colony, I want them to hit "join" & after creating their account be dropped back to our colony, so that it's not confusing for them. 

### Description (optional, but useful!)

Here's how the experience works today:

1. Inviter invites invitee to colony (via sharing the link)
1. Invitee creates an account on Colony
1. Invitee is then sent to /landing

Here's how the experience would work ideally:

1. Inviter invites invitee to colony (via sharing the link)
1. Invitee creates an account on Colony
1. Invitee is then sent to the URL they clicked join from

### This issue is complete when...

- [ ] When a user clicks "join" from a Colony, after they create their account, they are returned to the URL they clicked "join" from.

**Comment by thycommodore** [comment]
For future reference, this was sourced from here: https://colony.canny.io/bugs/p/joining-a-community-when-not-logged-in

**Comment by rdig** [comment]
This was already posted before, it's a duplicate. 

Here is the original answer I gave: https://github.com/JoinColony/colonyDapp/issues/2599#issuecomment-879083721

No new developments have come about in the mean time, I will still close this as it will not be relevant after we refactor the user creation flow _(as outlined above)_
