### ISSUE TITLE
Transaction failure when trying to annotate the Mint Tokens action

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2654]
## Steps to reproduce

1. Create a token called $UNIT
2. Mint tokens

## Expected behaviour

* If we can't handle this type of symbol, we should throw an error when creating your token symbol.

## Actual behaviour

* User is approved when creating the token symbol.

## Suggestions (optional)

* Another way to solve this quickly would be to add some copy about our expectations, but given the user is effectively stuck once they do this — we should probably prevent it from happening.

**Comment by thycommodore** [comment]
<img width="1440" alt="Screenshot 2021-08-19 at 19 52 35" src="https://user-images.githubusercontent.com/89165465/130130235-4134bb47-16e3-4f49-8680-c3d6349a1451.png">

**Comment by rdig** [comment]
This is nothing to do with the dollar sign symbol. The error you are seeing is for the "annotate" transaction, not the mint tokens ones. 

Notice the first two transactions being successful, meaning your tokens are already minted and claimed.

However, this is a valid bug nonetheless related to _(most likely)_ something going wrong with saving the annotation text to IPFS _(the IPFS hash then gets passed along to the transaction as an argument)_
