### ISSUE TITLE
Duplicate action is displayed and shows as "forced" when motion is finalized

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#2660]
## Steps to reproduce

Complete a payment via a motion

## Expected behaviour

One item should show up in the actions list, it should be listed as a motion.

## Actual behaviour

A duplicate item is shown in the actions list, listing the payment as forced.

![image](https://user-images.githubusercontent.com/8453294/130160273-46a6c7e8-e85d-4086-9907-807717805e0d.png)
https://xdai.colony.io/colony/clr

**Comment by rdig** [comment]
Closing this in favor of #2703 

Thank you for reporting it.
