### ISSUE TITLE
Update links on Profile, Choosing a Native Token & Unlocking Token

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2683]
There are a few links that need to be updated.

---

### 1) Unlock Token modal "Learn more" needs updating.

Screenshot: https://d.pr/i/E6FncT

- [x] Update the learn more to https://colony.gitbook.io/colony/manage-funds/unlock-token

---

### 2) Update the Learn More link on the "Choosing a Native Token" screen while creating a colony

- [x] Update the learn more to https://colony.gitbook.io/colony/create-a-colony/select-native-token

---

### 3) Update the link to Report a Bug (via profile avatar)

Screenshot: https://d.pr/i/0mBXgi

- [x] Update the link to Report a Bug on your profile from https://github.com/JoinColony/colonyDapp/issues to https://colony.canny.io/

---

### 4) Update the link to Help (via profile avatar)

Screenshot: https://d.pr/i/0mBXgi

- [x] Update the link to Help from the profile from https://help.colony.io/ to https://colony.gitbook.io/colony

**Comment by theobtl** [comment]
> ### 2) Update the Learn More link on the "Choosing a Native Token" screen while creating a colony
> Please update the link to: [working w/ Jack & Theo to get the link]
> 
> * [ ]  Update the learn more to [see above]

Please use this link: https://colony.gitbook.io/colony/create-a-colony/select-native-token
