### ISSUE TITLE
Incorrect token symbol rendering in action list

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2707]
## Steps to reproduce

View this action [this action](https://xdai.colony.io/colony/agaveswarm/tx/0xbf97bee35324867e3cde930bcc577b2aa122238d1f347f1300fb9aed795e9410) from within the action page, and on the action list.

## Expected behaviour

Should show up as xDai on the action list.

## Actual behaviour

Shows up as AGVE

**Comment by rdig** [comment]
This needs to be investigated (and reproduced locally)

**Comment by alicjakujawa** [comment]
@rdig its correct bug, i will be fixing it
