### ISSUE TITLE
Previous Sales box isn't updating

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2710]
## Steps to reproduce

1. Launch a coin machine sale
1. Purchase a token

## Expected behaviour

* Previous sales should appear within the "Previous Sales" box

## Actual behaviour

* The box stays empty with no new data

**Comment by rdig** [comment]
The previous sales table will only update after the sale period ends, not after each individual sale

**Comment by rdig** [comment]
This needs to be replicated locally to confirm that my assumption is correct (or wrong, whatever the case may be)

**Comment by alicjakujawa** [comment]
> This needs to be replicated locally to confirm that my assumption is correct (or wrong, whatever the case may be)

i will test it

**Comment by alicjakujawa** [comment]
@rdig previous sales doesn't show at all locally, so i will debug this further

**Comment by alicjakujawa** [comment]
@thycommodore Retested this locally, like Raul mentioned, data will show only after period will end, so it seems to be working fine.

**Comment by thycommodore** [comment]
@alicjakujawa what is a period? I'm assuming the cell that says "Time Remaining"?
![Screenshot on 2021-09-13 at 12-42-32 (1)](https://user-images.githubusercontent.com/89165465/133269913-054fb539-9a30-4d24-9a67-03322ff9af24.png)

I can try to replicate again, but that was the area that was not updating when we created this ticket.

**Comment by rdig** [comment]
> @alicjakujawa what is a period? I'm assuming the cell that says "Time Remaining"?

Yes, a period is when the time remaining, in a sale period, runs out. After that happens, and an event is emitted from the chain, a new entry shows up the in Previous Sales table.

**BUT**! Judging by your screenshot, you didn't transfer any tokens into your Coin Machine contract, meaning the sale hasn't yet started, no new periods are generated, and the timer just rolls over aimlessly. Give my previous presumptions, no new entries will show up in the table because **there is no sale going on**

**Comment by thycommodore** [comment]
If no tokens were sent into the Coin Machine contract, wouldn't the coin machine sale not be occurring? Isn't that the trigger? @jakzilla set this up officially, so I can't confirm if he did submit the tokens. 

fwiw I just went to the same token sale now (https://qaxdai.colony.io/colony/roadrunner/buy-tokens/) and bought a token. You can see in this new screen shot that the token quantity drops to 399 out of 400. 

![Screenshot on 2021-09-14 at 16-02-22](https://user-images.githubusercontent.com/89165465/133325992-82a35796-001f-4b43-bc2d-315c201f3be1.png)

I waited for another time period to pass and the token count reset to 400/400. Perhaps you're right that it's running... but that begs the question — should it be?

**Comment by rdig** [comment]
So I think this is related to the Subgraph as I don't think it's deploying the new handlers we wrote especially for the previous sales data.

And I think we just missed the fact that we were running the Coin Machine code with an old version of the Subgraph. 

I believe that once I get to the bottom of it and make it work, this will be fixed as well.
