### ISSUE TITLE
Comment Shadow Banning

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2711]
### Story

As an admin selling my token, I want the ability to delete spam/hate/trolls from the chat thread, so that I run the most successful token sale I can run.

### Description (optional, but useful!)

In the event a group of people (or even just one person) wants to derail a token sale, they can do so fairly easily without any recourse. The bad actor could spam their own alternative token sale, run a Metamask scam posing as an admin, say hateful things, generally cause havoc on the token sale. 

### Design (optional, might not be applicable)

Hopefully a simple X on the upper right hand area of the message sent is sufficient. 

### This issue is complete when...

- [ ] The administrator of the token sale sees an X on each message
- [ ] The administrator of the token sale can click the X and the message is deleted
- [ ] The message is removed from all viewers

### Suggestions (optional)

* We're guessing it's easier to just do a simple delete, but as you could imagine this feature could balloon to spam flagging & banning users. If there's an easier technical solution in regards to either of those, let us know.

**Comment by rdig** [comment]
This is a feature request which we need to discuss, as we don't have this ability server side, so we need to decide if this is worth the time investment to implement

**Comment by rdig** [comment]
Converted into a feature request which we need to decide how we act upon.

**Comment by rdig** [comment]
This is on hold until I finish working on the most pressing features from the Public Beta Release

**Comment by rdig** [comment]
Closing as it will now be split into multiple issues to track various parts being implemented, so this ends up being redundant
