### ISSUE TITLE
Switch the chat entry functions (CMD+Return = new line | Return = submit)

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2713]
Note: This is a UX bug, not a technical bug.

## Steps to reproduce

1. View a coin machine sale
2. Send a chat message

## Expected behaviour

* Hitting Return after typing feels like it will submit
* Hitting CMD+Return feels like it will do a new line

## Actual behaviour

* The opposite

## Suggestions (optional)

* Flip the functionalities so that:

- [ ] Hitting Return after typing submits your message
- [ ] Hitting CMD+Return after typing creates a new line

**Comment by rdig** [comment]
The keyboard shortcuts were @jakzilla 's picks, so you guys have. To decide amongst yourselves if you want this changed.

Also note that this will change will be dapp-wide and will affect both actions and motions

**Comment by rdig** [comment]
Converted into a feature request which we need to decide how we act upon.

**Comment by rdig** [comment]
Decided to change the inputs, so make sure that all places that use comments have these keyboard shortcuts changed, not just Coin Machine.

Also, make sure they are also reflected in the tip that shows up after entering 3 chars in the comment box.
