### ISSUE TITLE
Add Reward reputation to the Advanced part of the actions menu

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyDapp#2718]
Figma specs:

https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=3553%3A33886

**Comment by ArmandoGraterol** [comment]
The reward reputation and smite reputation sections were moved to their own menu called "Manage Reputation", and this section, with both the smite and reward one are being added here #2756 

Link to Figma file with the changes I mentioned above: https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=4445%3A70

Once #2756 is merged I'll close this issue
