### ISSUE TITLE
In the extension manager add a "copy" icon next to the coinmachine extension address as that's where funds need to be sent to start the sale

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2720]
### Story

As a user setting up a token sale, I want to easily & reliably copy the address where the funds need to be sent to start the sale, so that I know what to do & successfully do it.

### Description (optional, but useful!)

![Screenshot on 2021-09-14 at 15-37-47](https://user-images.githubusercontent.com/89165465/133322703-7b486060-452a-49c6-bcb9-8ca54bdc95a3.png)

### Design (optional, might not be applicable)

A little copy icon next to the contract address.

### This issue is complete when...

- [ ] There's a copy icon next to the contract address
- [ ] When clicking the copy icon the address is copied into your clipboard

**Comment by rdig** [comment]
This is actually a good improvement suggestions as I wanted to do this for a while just didn't have the time to come around to it.

Given the change won't require too much of our time, I'm putting in the to-do pile.

**Comment by rdig** [comment]
Oh, I thought this was about that, adding the copy functionality to the extension details page, on the right sidebar.

Shows how well I read the issue description...
🤦

**Comment by thycommodore** [comment]
Sorry guys, just walked through this from Step 0 and updated the screen.
