### ISSUE TITLE
"Estimation error: The execution failed due to an exception." when trying to buy tokens

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2721]
## Steps to reproduce

1. Create new colony
1. Install coin machine extension
1. Change period length to 0.1
1. Enable coin machine
1. Mint 10,000 tokens
1. Send 1,000 tokens to coin machine address
1. Go to Coin Machine
1. Buy 1 token

Screenshot: 
![Screenshot on 2021-09-14 at 15-57-21](https://user-images.githubusercontent.com/89165465/133325265-1aad03e2-5793-4834-83f0-f78157180b49.png)

## Expected behaviour

* Able to buy tokens

## Actual behaviour

* Estimation error

**Comment by alicjakujawa** [comment]
> ## Steps to reproduce
> 1. Create new colony
> 2. Install coin machine extension
> 3. Change period length to 0.1
> 4. Enable coin machine
> 5. Mint 10,000 tokens
> 6. Send 1,000 tokens to coin machine address
> 7. Go to Coin Machine
> 8. Buy 1 token
> 
> Screenshot:
> ![Screenshot on 2021-09-14 at 15-57-21](https://user-images.githubusercontent.com/89165465/133325265-1aad03e2-5793-4834-83f0-f78157180b49.png)
> 
> ## Expected behaviour
> * Able to buy tokens
> 
> ## Actual behaviour
> * Estimation error

@thycommodore can you please repeat those steps, but before buy tokens, "unlock colony token" from index modal

**Comment by cobordism** [comment]
I also encountered a gas estimation error just now as I was trying to "activate" my tokens.
https://blockscout.com/xdai/mainnet/tx/0x6cf2e9b7fd6f287f2c5a935c84462f4bf1edf4ddabc8631d978802670618343b

**Comment by rdig** [comment]
Cases like this were fixed by #2761

**Comment by cobordism** [comment]
I encountered it 5 minutes ago on https://qaxdai.colony.io/colony/topologic/buy-tokens
