### ISSUE TITLE
The price next sale copy should only show when the target has been reached (i.e. it should only show the green up arrow, or the rocket emoji when all sold out)

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2726]
## Steps to reproduce

1. Start a coin machine
1. Purchase a token
1. Wait for time period to proceed

## Expected behaviour

* The price next sale copy should only show when the target has been reached (i.e. it should only show the green up arrow, or the rocket emoji when all sold out)

<img width="243" alt="Screenshot on 2021-09-15 at 18-04-44" src="https://user-images.githubusercontent.com/89165465/133516054-7ee7290c-26fe-42d4-86f5-8011917e4579.png">

## Actual behaviour

* The price next sale copy appears with a grey arrow

![Screenshot on 2021-09-14 at 16-02-22](https://user-images.githubusercontent.com/89165465/133515804-903c5436-6aa1-4998-ac8a-656cbb8f3d4a.png)

**Comment by thycommodore** [comment]
@jakzilla can you take a look at this? 

@chinins & I were chatting this through... just wanted to double confirm that we want the following:

1. When the price is going to go up, do the green arrow
1. When the price is going to go down, show nothing (no text, no arrow)
1. When it's sold out, show the rocket ship

The assumption was that we would want to show the price is going down, but I'm assuming that we don't want to do that as it creates an incentive to not buy.

Sound right?

**Comment by chinins** [comment]
Talked to Jack and he confirmed the above.

The price status icon is also used in the Token Sales Table but there it should show all of the instances.

**Comment by rdig** [comment]
Was this fixed and not close @chinins ?

Either way, I think your #2868 supersedes this

**Comment by chinins** [comment]
Yes, it was fixed already. It just wasn't closed automatically.
