### ISSUE TITLE
Get error "Ooops, action not found" when creating a motion to upgrade.

### ISSUE THREAD

**Issue by cobordism** [JoinColony/colonyDapp#2727]
## Steps to reproduce

I created a motion to upgrade my colony from v7 to 8. I signed the transaction.

## Actual behaviour

As soon as I signed the transaction, I get to a page saying "Ooops, action not found". The only thing to click is "Return to colony".

A little while later I can see the motion listed under "events" but it is not clickable and I see no further indication that anything has happened.

I repeated the process and got the same results.

Example: https://blockscout.com/xdai/mainnet/tx/0x245cb4056b3df94c2655c16a26e9b9ab93df49c6480dde7b4cae32e91ce8b702

**Comment by rdig** [comment]
This needs to be investigated to determine what version of the contract was involved, as some unsupported versions might have gotten through.

Either way, this needs to be fixed.
