### ISSUE TITLE
On staking page "Share URL" link is broken

### ISSUE THREAD

**Issue by cobordism** [JoinColony/colonyDapp#2728]
## Steps to reproduce

Create a motion (in my case to create a new team).
On the top of the staking page it says:
**Motion requires at least 10% stake to appear in the actions list. Share URL**.
The string Share URL looks like a link, but clicking it does nothing.

## Expected behaviour

I assume it should give me options to share the URL of the motion with others.

## Actual behaviour

Clicking the link does nothing at all.

This was the URL https://qaxdai.colony.io/colony/topologic/tx/0x6a086a228b0cad69eff409a019861041de495d5926ce8277cc93dd7d4550e10a

**Comment by ArmandoGraterol** [comment]
Actually, when you click it the URL is copied to your clipboard, so I think this is more of a UX problem as you wouldn't know that the link is on your clipboard
