### ISSUE TITLE
Copy errors on "Wrong Network" notification modal

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2749]
<img width="623" alt="Screenshot 2021-09-28 at 14 03 37" src="https://user-images.githubusercontent.com/4774274/135092512-1594c5d8-def3-4589-aac9-078136bdb505.png">

Should read:

> Please connect to xDai chain. [Learn more.](https://colony.gitbook.io/colony/get-started/connect-metamask-to-xdai)

When Metatransactions is done we'll need to change this again.

**Comment by rdig** [comment]
Already was mentioned / tracked here: https://github.com/JoinColony/colonyDapp/issues/2740#issuecomment-924683816

But I'll make sure to include your proposed copy change
