### ISSUE TITLE
Missing error message when a motion cannot be finalized due to insufficient funds.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2762]
**Steps to replicate**
1. Create and stake a motion to pay tokens to a recipient.
2. Transfer funds away from the source pot.
3. Attempt to finalize the motion.

We need an error message here to tell the user "There are insufficient funds in the domain to finalize this transaction. Please add more tokens and try again."

**Comment by rdig** [comment]
I don't know exactly where this change lies. With us or with network. @area thoughts ?
