### ISSUE TITLE
Events are not rendering in subdomains.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2763]
1. Go here: https://xdai.colony.io/colony/swashbuckle/events
2. Choose Buccaneering. There should be events but there aren't.

Also, now I look at it, there are A LOT of transactions missing from the events feeds.

**Comment by rdig** [comment]
Cannot replicate: 

![Screenshot from 2021-10-03 12-57-11](https://user-images.githubusercontent.com/1193222/135748757-23d27666-79f4-473b-a113-adf511ae9cb9.png)

My guess lies with the graph either loading very slowly or not at all.
