### ISSUE TITLE
Motions are created in root despite the UI saying it's being created elsewhere.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2764]
1. Go to: https://xdai.colony.io/colony/swashbuckle
2. Go to buccaneering and create a payment, making sure you're creating the motion in buccaneering.
3. When the motion screen renders, the motion is in Root.

**Comment by rdig** [comment]
Can't replicate:

![Screenshot from 2021-10-03 12-54-32](https://user-images.githubusercontent.com/1193222/135748665-be46b97c-3eed-4e62-91c9-beeef2f55ef2.png)
