### ISSUE TITLE
Annotation transaction estimation error: invalid string value

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2769]
I'm not sure why this errored. Hopefully the image is self explanatory.
<img width="1536" alt="Screenshot 2021-10-02 at 00 22 50" src="https://user-images.githubusercontent.com/4774274/136052095-ba7f7509-2901-4e01-b4c2-721ead804aaa.png">

**Comment by ArmandoGraterol** [comment]
@jakzilla I think the image was not attached :(

**Comment by jakzilla** [comment]
Thanks @ArmandoGraterol!

**Comment by ArmandoGraterol** [comment]
Unfortunately, this is an issue with IPFS failing to upload the annotation, hence the `...Timeout reached trying to upload data to IPFS...` so right now we cannot do much about it until, in the future, we have a fallback for when this happens.
