### ISSUE TITLE
Reputation on all members list does not sum to 100% and does not, I believe, include all members.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2775]
<img width="931" alt="Screenshot 2021-10-06 at 19 04 49" src="https://user-images.githubusercontent.com/4774274/136259006-fcaa8844-af88-4741-b553-a93fd8010906.png">

**Comment by rdig** [comment]
This is a reputation miner issue. It didn't load reputation of all members (or failed), so the ones that are still loading, they are not displayed yet. (hence the missing reputation)

The only improvement that we can add here, from the dapp side, is to add some loading indicator (or error, in the case of the reputation miner failing), informing the user of that fact.
