### ISSUE TITLE
Coin Machine throwing an exception error on fresh deployment

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2786]
## Steps to reproduce

1. Create new Colony
2. Install Coin Machine
3. Enable Coin Machine (shortened the time durations + the price)
4. Attempt to buy tokens

## Expected behaviour

* User able to purchase tokens
* No exception error

## Actual behaviour

* https://share.descript.com/view/XPYUBjqdDxU

**Comment by rdig** [comment]
Coin Machine is not deployed to production, so you can change whatever copy you want.

The change I'm referring to is #2761

**Comment by thycommodore** [comment]
@rdig sounds good — won't add priority label to QA bugs
