### ISSUE TITLE
Add annotations to the Unlock Token modal

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#2815]
This is part of bringing the _Unlock Token_ modal in line with the rest by generating either an action, or a motion _(if the extension is enabled) from it.

This issue adds an annotation text box to the _Unlock Token_ modal, as well as wiring it in with it's saga.

There's already an `Annotations` core component for this, so you'll have to wire this up within the `UnlockTokenForm` component _(which is part of `UnlockTokenDialog`)_. For details on how to wire it up, search for instances where we already use it, and derive you code from them.

Once that's done, wire that data up with the `colonyTokenUnlock` saga. Again, search for examples in the other sagas that handle annotations, on how to do this.

Note that for this, you'll have to update the `COLONY_ACTION_UNLOCK_TOKEN` redux action type as well, in order for it to be aware of the data that's being passed in.

**Comment by rdig** [comment]
@arrenv what's the state of this? Are you still working on this?

If you aren't _(or never started)_, please un-assign yourself from it.

**Comment by arrenv** [comment]
@rdig thank you for following up on this, I have started it, but I was having environment issues at the time, that have since been resolved. I will prioritise it now.

**Comment by rdig** [comment]
Don't worry too much, it's low priority anyways.

I just wanted to know what's going on
