### ISSUE TITLE
UI - add `Banned` tag

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyDapp#2853]
First you need to add a new them to the Tag component & then add the `Banned` version that includes the emoji.

Figma spec:

https://www.figma.com/file/fw2pDIUlkhCkJE79ZyTbjp/CoinMachine?node-id=3195%3A36646

The story behind:

#2711

**Comment by agustif** [comment]
I think the padding on the banned tag is still off by 1px, at least on the members list page
<img width="1228" alt="Screenshot 2021-12-06 at 16 04 30" src="https://user-images.githubusercontent.com/6601142/145069861-1d3cee37-3857-4fcf-8e57-752afd10c29b.png">


Will look into it and open a PR with a fix.
