### ISSUE TITLE
Funds within a team that are paid out, do not update (visually?)

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2855]
## Steps to reproduce

1. Transfer funds into a team
1. Note the amount of funds within the team
1. Pay someone from that team's funds
1. Note the amount the funds displayed within the team

## Expected behaviour

* The funds number is updated & accurate

## Actual behaviour

* The funds do not update
* I'm not sure if the funds are actually updating, but it's a visual bug. I did run into an estimation error that might be preventing it. 
* Video: https://share.descript.com/view/aTm6iM2XmXZ

**Comment by thycommodore** [comment]
I came back to this team page ~5+ mins after & it was updated. So perhaps this is a caching (cron?) issue. I suspect this is already a known issue that's a byproduct of our infrastructure. If so, we can remove it.

**Comment by rdig** [comment]
This is a case of the events not being indexed fast enough
