### ISSUE TITLE
When doing an expenditure from a team budget, 10% of token value is being deducted

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2856]
## Steps to reproduce

1. Transfer funds to a team
1. Pay someone tokens (note the amount paid)
1. View the expenditure sent (10% missing)

## Expected behaviour

* The amount sent is the amount received

## Actual behaviour

* The amount is 10% lower
* The amount listed from the Action view is different (the originally sent amount) than the amount listed in the detail view
* Example: https://qaxdai.colony.io/colony/testkh11821/tx/0x1a3e5eaef7bee89647a006563747c6d6b904f43e5fb345028c7932205771fe6c
* ^ Jack was paid 1,000 tokens, but received 990.

**Comment by thycommodore** [comment]
I'm an idiot, this is 1%.

**Comment by alicjakujawa** [comment]
@thycommodore cost of transactions? 🤔

**Comment by thycommodore** [comment]
@alicjakujawa apologies for the confusion here, it was 1%; not 10%. This is as expected and thus closed.
