### ISSUE TITLE
Comments from a different motion appear temporarily on wrong motion

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2861]
## Steps to reproduce

1. Create a Team as a motion (I suspect this is any motion) [Motion A]
1. In a different tab, comment on a different motion [Motion B]
1. Return to [Motion A]
1. View the comments

## Expected behaviour

* Comments from Motion B do not appear on Motion A

## Actual behaviour

* Comments from Motion B appear on Motion A (temporarily)

## Example

* Theo commented on this Motion ([link](https://discord.com/channels/@me/862274530856009739/908030525334233189))
![image](https://user-images.githubusercontent.com/89165465/141153656-efecaa0e-67e1-46d7-b22f-a66bd3437887.png)
* Commodore viewed this on an unrelated Motion ([link](https://qaxdai.colony.io/colony/testkh11821/tx/0x5702cd40fa4abc5d50ab405ed342b9c207ea304c979ada4ea11db02d1a19e5a5))  
![image](https://user-images.githubusercontent.com/89165465/141153849-b49609c3-f8ef-4d88-92f2-5b5a4656c3ea.png)
* After some period of time (5 mins?) the comments disappear from the incorrect Motion

**Comment by theobtl** [comment]
Here's an issue that's probably related to the same cause:
The comment box displays a comment _and_ the default message for when there aren't any comments.

![Screenshot 2021-11-16 at 22 05 31](https://user-images.githubusercontent.com/12872797/142065783-53768cf1-7eca-4a8c-b89c-1030a7945487.png)
