### ISSUE TITLE
Sending native tokens to another colony doesn't not appear in their treasury

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2863]
## Steps to reproduce

1. Create a colony (colony A) w/ a new native token
2. Add colony A's native token to colony B's managed tokens
3. Create an expenditure sending to a different colony's address (colony B)
4. View colony B's treasury

## Expected behaviour

* The funds sent from colony A to colony B should appear within the treasury

## Actual behaviour

* The UI in colony B suggests the total is zero
* The blockscout transaction says the funds did transfer ([ref](https://qaxdai.colony.io/colony/roadrunner/tx/0x3b3ed2a6e130224bfe68586ad682c87877a7901ff08a09e01b9ba0a54aa2e210))

Note: Recipient colony ([link](https://qaxdai.colony.io/colony/testkh11821))

![image](https://user-images.githubusercontent.com/89165465/141195622-5e5a353f-fc16-4d50-b07c-ca29229f41dc.png)

**Comment by rdig** [comment]
This is not a bug. It will only show up in the other's colony tresure if that colony actively tracks the token.

You can do that by going to New Action -> Manage Funds -> Manage Tokens and add said token via it's contract address

**Comment by thycommodore** [comment]
@rdig I will triple check, but this is reporting the issue even with said token added.

**Comment by thycommodore** [comment]
@rdig this might be an index issue, but I just ran through this set of actions & replicated it at least from a UX perspective.

1. Colony B ([link](https://qaxdai.colony.io/colony/test123stakedtokens)) added Colony A's ([link](https://qaxdai.colony.io/colony/testkrausehouse111621)) native token via Manage Tokens action.
2. Colony A sent 1,000 (990 after fee) to Colony B

Colony B's UI shows 0 Colony A's tokens ([screen 1](https://d.pr/i/mGxWRM)) ([screen 2](https://d.pr/i/yRy2em)). However, via Blockscout it does show that Colony B has 990 tokens ([ref](https://blockscout.com/xdai/mainnet/address/0x8fc3abFb753874e7D7d539A4FdEd42608791c0dB/tokens)). 

This might be an index issue, but what I went back and did was looked at the original transaction that triggered this original issue ([ref](https://qaxdai.colony.io/colony/testkh11821)) to see if enough time passed to catch up on the indexing — which the UI still shows 0 MEEP ([screen](https://d.pr/i/DTKlIF)) yet Blockscout shows the correct amount of MEEP ([ref](https://blockscout.com/xdai/mainnet/address/0xacd843C465FD72624Acb40F42135847Df81e5789/tokens)).

**Comment by chinins** [comment]
@thycommodore, Have you tried claiming the tokens? I went and checked and  I can see that there are some tokens to claim.
Try claiming and check if the tokens appear.

<img width="1163" alt="Screenshot 2021-11-17 at 17 39 05" src="https://user-images.githubusercontent.com/34057551/142242855-1e30112e-8e6c-44aa-b2ca-717fa83e2df5.png">

<img width="1211" alt="Screenshot 2021-11-17 at 17 39 42" src="https://user-images.githubusercontent.com/34057551/142242957-e2ba4fc2-cdf0-48ce-be76-64faa42a9319.png">

**Comment by thycommodore** [comment]
@chinins didn't realize you needed to do that... 😩 

That doesn't make intuitive sense to me, but I'm assuming there are good reasons for this to work the way that it does. Yes, considered this closed — especially given the funds are actually in the contract according to Blockscout. 

@theobtl this might be another thing to note in the GitBook (not urgent).

**Comment by chinins** [comment]
> @chinins didn't realize you needed to do that... 😩
> 
> That doesn't make intuitive sense to me, but I'm assuming there are good reasons for this to work the way that it does. Yes, considered this closed — especially given the funds are actually in the contract according to Blockscout.
> 
> @theobtl this might be another thing to note in the GitBook (not urgent).

@thycommodore, I know - I made the same mistake at some point and was going crazy why it was not working :) I do agree that it's not very intuitive. I wonder why it's on the `Events` page, maybe be it would be easier if it were on `Actions` page but maybe there is a good reason for that.
