### ISSUE TITLE
Add "Total sold / available" section to Coin Machine.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2868]
The lack of this feature is a considerable irritation during testing which I worry is going to cause complaints.

We've tried to make the change minimally disruptive to the rest of the UI. I hope it's okay!

Please note:

1. Number font size in both sold vs available boxes should have a max of 18pts and scale down to fit on a single line when the numbers get big.
2. Numbers should be to 5 sig figs. i.e. have no decimal places if the number is 5 figures or larger.
3. New titles on each card in the new three-card layout.
4.  Changed location of the "Price next batch" notification which is shown when the target is reached.

![Running Out@2x](https://user-images.githubusercontent.com/4774274/141312359-bbd4707d-49f0-472f-918d-2ab2fc765b2c.jpg)

**Comment by rdig** [comment]
It will be done :)
