### ISSUE TITLE
Fix whitelist extension not showing as enabled

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#2873]
## Steps to reproduce

1. Create a colony
2. Install the whitelist extension
3. Enable it using any policy

## Expected behaviour

* The UI shows the extension as enabled, without even reloading the page 

## Actual behaviour

* Even after the transaction is completed, the UI shows the extension as disabled, even if you reload the page, and you can't enable it again because it's actually enabled in the "background"

![FireShot Capture 477 - Colony - localhost](https://user-images.githubusercontent.com/18473896/141370356-d933c54f-4d85-46a3-8808-d9aadeb60446.png)

**Comment by rdig** [comment]
Already done
