### ISSUE TITLE
Cannot activate purchased tokens in RC.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2887]
This issue appears confined to RC. I was able to purchase and activate in Swashbuckle
<img width="1553" alt="Screenshot 2021-11-15 at 20 54 24" src="https://user-images.githubusercontent.com/4774274/141852413-26fc0cad-a726-4a80-b226-e5b8d8eca07b.png">

**Comment by rdig** [comment]
I don't really want to go chasing this down the rabbit if only happens in my test colony.
