### ISSUE TITLE
Update unban and restore comment actions with new icons and labels

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#2890]
### Story

With comment moderation, there should be the option to unban and restore comments.

### Description (optional, but useful!)

The menu entries have already been created for them, the new icons have been provided by product. Extract the icons from the provided Figma, add the icons, and update the name of the menu entries.

### Design (optional, might not be applicable)

[[Figma link](https://the-link-to-the-design-on-figma)](https://www.figma.com/file/fw2pDIUlkhCkJE79ZyTbjp/CoinMachine?node-id=3453%3A35195)

![restore-unban-comments](https://user-images.githubusercontent.com/33682027/141937242-c342896e-bb58-45aa-970b-3f10c54237d1.png)

### This issue is complete when...

- [ ] Extract SVG icons from Figma and optimise for web
- [ ] Update menu entries with new icons and correct names

**Comment by rdig** [comment]
Have you started work on this yet? _(Ie: a PR)_ otherwise, I'll take over

**Comment by rdig** [comment]
I'm taking over this, as discussed with Arren

**Comment by rdig** [comment]
Done via bfa28ef7b1d4a793dedb79c58b400c7c9f751fa5
