### ISSUE TITLE
Chatting in one colony's coin machine sale impacts other colony's sale

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2896]
## Steps to reproduce

1. Find or create a Coin Machine sale (does not need to be active, just chat window accessible)
2. Find or create a 2nd Coin Machine sale
3. Leave a comment in one chat
4. Then leave a comment in the other chat
5. Alternate between the two observing the experience

If you want two handy ones: https://qaxdai.colony.io/colony/testkh11821/buy-tokens & https://qaxdai.colony.io/colony/roadrunner/buy-tokens/

## Expected behaviour

* Chatting in one colony has no impact on a different colony's chat

## Actual behaviour

* When a user comments in Colony A, it appears in Colony B's chat.
* The comment made in Colony A will be visible in both Colony A & B's chats.
* If someone then comments in Colony B, the comment for Colony A will disappear and Colony B's chat will look correct.
* However, if you go back to Colony A — you'll now see Colony B's chat thread.

Raul had asked if the two colonies had the same contract address for coin machine. In the case of my replication, this was not the case:

`0x75b1CD01bC2c6DDB31C365704aaBCE8582c287Fc`
`0x664482C576278C931FCDafb25Dc97F24528A1a88`

## Suggestions (optional)

* It appears that the chats are being correctly stored on the correct Colony's chat view, but there is a display problem between the two. I suspect this applies to all concurrent chat experiences.

**Comment by theobtl** [comment]
Here's an issue that's probably related to the same cause:
The comment box displays a comment _and_ the default message for when there aren't any comments.

![Screenshot 2021-11-16 at 22 05 31](https://user-images.githubusercontent.com/12872797/142065928-6bcf879d-9375-4ec5-8c6c-01e31f30dcb1.png)

**Comment by rdig** [comment]
So does this applies to motions as well, or just coin machines ?

**Comment by rdig** [comment]
I have a feeling that resolving this will also resolve #2861 and vice versa

**Comment by rdig** [comment]
Also @ArmandoGraterol let me know if have problems tracking down the issue here, and I'll take over.
