### ISSUE TITLE
Text items overlapping in Whitelist extension

### ISSUE THREAD

**Issue by theobtl** [JoinColony/colonyDapp#2897]
## Steps to reproduce

1. Install and enable Whitelist extension
2. Choose either "Agreement only" or "KYC or agreement"
3. Fill "Paste agreement" text field with less than 100 characters 

## Expected behaviour

* If the text field is empty or if the field is not empty, but has <100 characters, it should return an error message anywhere but on top of the default message "This agreement will be displayed during whitelisting process modal."

## Actual behaviour

* The default message and the error message are displayed on top of another.

![Screenshot 2021-11-16 at 20 34 09](https://user-images.githubusercontent.com/12872797/142054167-76630a60-3fad-42a7-857f-87e0d2d14c91.png)
![Screenshot 2021-11-16 at 20 34 22](https://user-images.githubusercontent.com/12872797/142054174-065fb2d8-accb-49e4-b4d0-699647bcdb3c.png)
![Screenshot 2021-11-16 at 20 34 39](https://user-images.githubusercontent.com/12872797/142054175-2d8b40b6-dc19-487a-8c09-50eb77383013.png)

**Comment by rdig** [comment]
Fixed by the above commit
