### ISSUE TITLE
Tokens are erroneously staked when creating a new colony

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2899]
## Steps to reproduce

1. Create a new colony
2. Look at your individual token balance within your colony

## Expected behaviour

* The user should see 0 tokens

## Actual behaviour

* The user sees 123.2442 tokens staked

![image](https://user-images.githubusercontent.com/89165465/142063597-d5bf8da6-568c-4a55-b9cb-6ed981577acd.png)

**Comment by rdig** [comment]
This is new... and weird.

I think it's unrelated to the dapp _(either subgraph or the endpoint)_, but will investigate nonetheless

**Comment by rdig** [comment]
As the log entry shows, this was fixed by 60eeda01a1b792b6d8062e7b2c97c940edd94a2b
