### ISSUE TITLE
When Coin Machine's field "Per user purchase limit" set to >100% or "Window Size" <1, it passes validation but tx throws an exception

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2900]
## Steps to reproduce

1. Install Coin Machine
2. On the field "Per user purchase limit", set to 200%
3. Confirm the settings

AND

1. Install Coin Machine
2. On the field "Window Size", set to 0.2
3. Confirm the settings

## Expected behaviour

* Receive a validation error that the "Per user purchase limit" cannot exceed 100%.

AND

* Receive a validation error that the "Window Size" cannot be less than 1.

## Actual behaviour

* For 'Purchase Limit`, user receives an exception on the transaction: `Estimation error: Reverted 0x636f696e2d6d616368696e652d6c696d69742d746f6f2d6c61726765`
* For `Window Size`, user receives an exception on the transaction: `Estimation error: invalid input argument (arg="_windowSize", reason="invalid number value", value="0.2", version=4.0.47)`

**Comment by rdig** [comment]
Fixed by the above commit

**Comment by thycommodore** [comment]
@rdig I just discovered a related issue — if you set `Maximum Per Period` < `Target Per Period` it passes validation, then receives an `Estimation error: Reverted 0x636f696e2d6d616368696e652d6d61782d746f6f2d736d616c6c`

I'm assuming it would be better to re-open and address here than open a new issue.

**Comment by thycommodore** [comment]
@rdig maybe I'm mistaken, I'm running into this estimation error all over my colony. I'm going to try to spin up a new colony to replicate. But the new issue _probably_ remains given there's no front-end validation for that configuration and I'm assuming it won't work at the contract level.

**Comment by rdig** [comment]
Don't. It's fixed, not deployed. See the above commit I was mention, was pushed just 30 mins ago

**Comment by thycommodore** [comment]
@rdig I saw your commit, but looks like the validation is for `windowSize` & `userLimitFraction`, this "new" issue is for 'targetPerPeriod' & 'maxPerPeriod'. I'll leave it to you to organize as you see fit.

**Comment by rdig** [comment]
Never mind, I think it's a case of mis-communication

**Comment by rdig** [comment]
The latter part of this is fixed by e3de8e7794a3c9c5cd5adf22fdc28b8e91a85636
