### ISSUE TITLE
Coin Machine temporarily showing a wrong confirmation message after user bought tokens

### ISSUE THREAD

**Issue by theobtl** [JoinColony/colonyDapp#2901]
## Steps to reproduce

1. Open coin machine in any colony on qaxdai.
2. Buy tokens and sign in MetaMask
3. Wait for confirmation message

## Expected behaviour

* The user should see the amount of tokens they bought, if any.

## Actual behaviour

* At first, the user is informed that they could only buy a partial amount, but a few seconds later the page changes to the original amount and the usual success page (screen-recording available upon request).
* Note from @jakzilla: "I have a hunch that the quantity you see having been able to purchase immediately after you’ve made a purchase is in fact the amount the last person to buy before you bought, then a few moments later you’re shown the actual amount you bought."

**Comment by thycommodore** [comment]
One additional thing to note, is that this message states the token as CLNY (before disappearing).

**Comment by rdig** [comment]
Fixed by the above commit
