### ISSUE TITLE
Coin Machine - Microcopy for Synaps Pre-Loading 

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#2903]
### Story

As a *user who wants to get whitelisted*, I want to *understand why KYC module is loading*, so that *I can check pending transaction in my wallet*

### Description (optional, but useful!)

Please include microcopy below the loading circle as on attached URL. 
Currently, someone might not get a clue that has to open metamask, especially while scrolling page down. 

Make sure to align preloader to the middle (taco). 

### Design (optional, might not be applicable)

[Figma link](https://www.figma.com/file/fw2pDIUlkhCkJE79ZyTbjp/CoinMachine?node-id=3516%3A35286)

Check copy with Jack: "Sign transaction with your wallet" (suggested one)

![image](https://user-images.githubusercontent.com/20819402/142219951-9fb0ba28-ee93-4875-b429-eec7ca15be03.png)## Implementation

### This issue is complete when...

- [ ] The activity indicator for the `TransactionStatus` component is shown during any and all async waiting

**Comment by jakzilla** [comment]
Is this really necessary? I am not aware of users experiencing this pain.

**Comment by agustif** [comment]
> Is this really necessary? I am not aware of users experiencing this pain.

Not for me to judge but will work on other more pressing bugs like #2980 until someone else chime's in
