### ISSUE TITLE
When setting the Token To Be Sold to xDAI and the Purchase Token to xDAI, confirm button does nothing (same w/ xDAI to native token)

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2904]
## Steps to reproduce

1. Enable Coin Machine
2. Set the `Token To Be Sold` to xDAI
3. Hit `Confirm`

OR

1. Enable Coin Machine
2. Set the `Purchase Token` to the native token
3. Hit `Confirm`

## Expected behaviour

* If the Coin Machine can handle this configuration, then it should successfully `confirm`.
* If the Coin Machine can not handle this config, then validation should have prevented it.

## Actual behaviour

* `Confirm` button spins without any action.

**Comment by rdig** [comment]
@ArmandoGraterol I've already fixed this via de6c96bc49ad68f103b173f65b99ecf7bac24cd0

**Comment by rdig** [comment]
So de6c96bc49ad68f103b173f65b99ecf7bac24cd0 closes this
