### ISSUE TITLE
After selling out of the token (entirely), Previous Sales window incorrect

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2906]
## Steps to reproduce

1. Enable Coin Machine
2. Send 100 tokens to Coin Machine
3. Buy all 100 tokens
4. Refresh page

## Expected behaviour

* Previous Sales window stays as is

## Actual behaviour

* If you don't refresh the page, you'll see a validation error of "The amount must be less or equal to 0"
* Tokens remaining will be inaccurate (will show the variables during setup)
* If you refresh, then the Previous Sales table will show 0/0 for tokens sold for all time periods:

![image](https://user-images.githubusercontent.com/89165465/142271820-7ddd5cd4-2e33-4032-b097-bed7068d9384.png)

**Comment by rdig** [comment]
I cannot trust this yet. The whole previous sale logic runs off subgraph events, and the subgraph has been dropping data all day :(

Tommorow we're rolling our own, so this will have to be re-tested

**Comment by thycommodore** [comment]
@rdig sounds good, will do another round on this category of issues

**Comment by rdig** [comment]
I can replicate this locally as well, it's not a case of the subgraph, so this is valid.

Taking it out of hold and putting it in the queue.
