### ISSUE TITLE
There are previous sale results in a fresh install of Coin Machine

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2933]
https://qaxdai.colony.io/colony/fr/buy-tokens/

![Screenshot 2021-11-20 at 16 12 08](https://user-images.githubusercontent.com/4774274/142733361-1c5a390f-1046-40ec-98bc-597c516562f3.png)

**Comment by rdig** [comment]
This might not be the case, but periods pass even without tokens put in the coin machine, so if you leave coin machine running long enough, you'll see empty periods

**Comment by rdig** [comment]
Unless these showed up the second you installed coin machine

**Comment by jakzilla** [comment]
Yes they are from a totally fresh install.

This is another fresh install before any tokens have been sent to Coin Machine.

![Screenshot 2021-11-20 at 16 56 12](https://user-images.githubusercontent.com/4774274/142734683-9fe334d5-da00-4970-84de-678d516776d6.png)

**Comment by jakzilla** [comment]
I refreshed and it changed to this:

![Screenshot 2021-11-20 at 16 58 33](https://user-images.githubusercontent.com/4774274/142734775-2cc897b3-5f00-4bea-b7e5-11eabd2000e0.png)

However, from the perspective of the user, previous sales should not be showing up for periods during which there are no funds in CM.

**Comment by rdig** [comment]
> However, from the perspective of the user, previous sales should not be showing up for periods during which there are no funds in CM.

We talked about this, and it's not that easy to achieve. Remember the subgraph limitations, and how we have to calculate all this data in the client ?
