### ISSUE TITLE
Maximum per person purchase limit is not enforced.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2934]
I enabled Coin Machine with a 10% of the total supply. However, I was able to buy 100%.

When I bought them I was given the message that I tried to purchase 100 but someone beat me to it.

The params I installed:
![Screenshot 2021-11-20 at 16 22 07](https://user-images.githubusercontent.com/4774274/142733790-8f63330a-bdae-456d-9500-dd4f652da6a2.png)

I then funded Coin Machine with 100MEEP.

My purchase of 100 MEEP.
![Screenshot 2021-11-20 at 16 24 25](https://user-images.githubusercontent.com/4774274/142733794-aaf6da77-7f96-4114-84d3-5103c123f2c1.png)

**Comment by rdig** [comment]
Does the contract allow you to send that transaction ?

If it does, then something's up with the initialization param

**Comment by area** [comment]
That parameter only applies if you were using a whitelist. Were you?

**Comment by kronosapiens** [comment]
For context, the reason why the limit does not apply without a whitelist is to remove an incentive to create sockpuppet accounts -- if there is no whitelist, then a per-address restriction is trivially circumvented.
