### ISSUE TITLE
Price appears still to be progressing despite CM having run out of tokens.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2936]
I bought all the tokens at $0.1. After that was done, the purchase no longer shows up and the price continues to decrease.

![Screenshot 2021-11-20 at 17 13 57](https://user-images.githubusercontent.com/4774274/142735246-84872ac2-319f-4263-ad23-af6ff0dc2d1c.png)

**Comment by rdig** [comment]
This is just visual and is related to the fact that this logic had to be re-implemented locally.

But this will be fixed by #2933 where _(I'll try at least)_ we'll filter out the no token periods
