### ISSUE TITLE
Add loading state indicator(s) for `ColonyActions`

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#2945]
This component has 4 data sources loading, which get merged into a single list:
- one transaction payment events
- rest of events (that are not the above one)
- motions
- comment counts

They load from different queries, at different times. and at different rates.

So this issue requires us to improve that.

First, merge all the queries that come from the subgraph into a single one (onetx payment events, rest of events, motions)

Second, add different loading states (`MiniSpinnerLoader` at the top of the component) for each query that is begin called, and keep that loading state active until data (including the parsed one from the transformer and filters) is ready to be used by React _(not just when the `loading` check from the query is `false)_

This is add some much needed quality of life to the loading state of (for the majority) the first page of the dapp that the users see

**Comment by chinins** [comment]
We have subscriptions in ColonyActions component and subscriptions can't be combined in one. So this is closed.
This is the reference for the graphql:

https://github.com/graphql/graphql-js/blob/261b99b0a643561ccfb217fe8ac0c2ac16b2c5d3/src/validation/rules/SingleFieldSubscriptions.js#L22-L26
