### ISSUE TITLE
Coin Machine numbers render funny in some instances when too low.

### ISSUE THREAD

**Issue by agustif** [JoinColony/colonyDapp#2951]
## Steps to reproduce

1.  login, create a new colony, enable coin machine extension
2.  create a new coin machine token sale, and set a super low number at conversion rates 

Context: I got burned on my first QA colony MARS, which I just enabled with defaults, and then couldn't buy my own tokens. So I created a new MOON colony with a much cheaper conversion rate to xDai, so I was sure
I could buy afterwards (I don't know how many decimal zeros I added, but too many it seems)

## Expected behaviour
I don't think we want to set hard boundries, but maybe the UI should handle better cases where a lot of decimals are involved. Although MetaMask was faulty in these too, when doing very small transactions will show gladly 0.00 in some parts of the UI. Hopefully they will fix it too.

## Actual behaviour

Some parts of the UI don't handle this nicely, and shows exponentials

<img width="256" alt="Screenshot 2021-11-20 at 00 22 36" src="https://user-images.githubusercontent.com/6601142/143031612-cd5966fc-d132-4476-9b18-10de372c36e3.png">

## Suggestions (optional)

Handling this better, either showing the last digits instead of the first, or scrolling, or a hover popup or whatever, but best for design / product to suggest fixes I guess!

**Comment by rdig** [comment]
Those numbers are not funny, that is called Scientific Notation, and it's expected.

We'll refactor the numbers system at some point in the future, but for now this is fine.
