### ISSUE TITLE
Misaligned menu with colony name and menu

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#2954]
## Steps to reproduce

1. Access the Dapp

## Expected behaviour

* Menu and colony name and colony menu should be aligned left.

![menu-alignment-design](https://user-images.githubusercontent.com/33682027/143085247-a99f9020-c47d-4939-b76d-53376094367d.png)

## Actual behaviour

* Alignment of the menu is currently off to the right

![menu-alignment-actual](https://user-images.githubusercontent.com/33682027/143085265-92d21a1a-6b32-4c2c-b7a9-5a40e95c53c6.png)

**Comment by rdig** [comment]
Even though the fima spec says so, it was decided that the current implementation is fine.

Closing for now
