### ISSUE TITLE
In available vs. sold tokens widgets format numbers to split into 2 lines after the font-size was set to 10 & they still don't fit in the widget

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyDapp#2955]
This is another part of the issue #2868

**Comment by arrenv** [comment]
I managed to get the following, however, I used a more crude approach to the 10px font-size.

![number-new-line-2](https://user-images.githubusercontent.com/33682027/143303167-a93e8988-f3a7-4047-92f7-785ea5cdb3e0.png)
![number-new-line-3](https://user-images.githubusercontent.com/33682027/143303171-ddc4a3d8-f333-4e7d-9179-1f3e2abb5ca6.png)
![number-new-line](https://user-images.githubusercontent.com/33682027/143303172-b7562e50-a2c1-48dc-885b-e919cc624b86.png)

**Comment by rdig** [comment]
Was this done by #2868 then ?

**Comment by chinins** [comment]
> Was this done by #2868 then ?

yes. Sorry, I should have mentioned it here.

**Comment by rdig** [comment]
Cool, I'll close this
