### ISSUE TITLE
On /inbox no button to get back to colony overview

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2979]
## Steps to reproduce

1. Go here: https://xdai.colony.io/colony/meta/
2. Click the letter icon in upper right
3. Click "See all notifications"

## Expected behaviour

* Page should have back arrow in upper left

## Actual behaviour

* No way to navigate back

## Suggestions (optional)

* There have been conversations of removing this entirely. Should we remove notifications until if/when we have a resolution?

**Comment by agustif** [comment]
Should I add a back button in the top left of the inbox page for now that uses something like router.history.back() or whatever similar?

**Comment by rdig** [comment]
> Should I add a back

Add back implies that it was once there.

No, we haven't decided what route to take here, but if it's this, there's a route layout that automatically adds that button to a page, without the need to specifically re-implement it.

**Comment by agustif** [comment]
> > Should I add a back
> 
> Add back implies that it was once there.

Add a "back" button, not add back a button, sorry for the messy way of putting it, it leads to confusion.

> 
> No, we haven't decided what route to take here, but if it's this, there's a route layout that automatically adds that button to a page, without the need to specifically re-implement it.

I will wait to see what gets decided to be done, and if it's adding the button and I get to work on it will use the one already available.

**Comment by rdig** [comment]
Closing this as not currently relevant, until we figure out what we'll do with notifications
