### ISSUE TITLE
Add Colony icon as favicon

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2986]
I've noted the colony icon doesn't appear in tabs, rather we have the default globe icon which looks a bit amateurish.
![Screenshot 2021-12-01 at 11 34 16](https://user-images.githubusercontent.com/4774274/144227545-4ed4895c-db7d-479a-912c-ab978884b7b3.png)

**Comment by agustif** [comment]
Investigating this, seems to be an issue with webpack when deployed.

In localhost I can see the favicon properly, but not on any of our envriroments (qaxdai, xdai, prod)

Will investigate further, a possible solution would be to add them more explicitly like in the landing page as a link in our app's head or something like that? Prob need to handle apple-touch-icon too there

**Comment by rdig** [comment]
This is a problem from the devops side, this cannot be solved from the dapp.
