### ISSUE TITLE
'Per user purchase limit' is being enforce on the batch instead of total sale

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2995]
## Steps to reproduce

2. Setup whitelist extension w/ agreement option enabled
1. Setup a fresh Coin Machine
2. Select a `Per user purchase limit` of 10%
3. Set `Target per period` to 50
4. Set `Maximum Per Period` to 100
5. Set `Period Length` to 0.1
6. Send funds to Coin Machine to start sale
7. Attempt to purchase `Max` amount
8. Attempt to purchase `Max` amount in next batch

## Expected behaviour

* The user should be capped against the total token sale quantity

## Actual behaviour

* The user is capped against the batch's quantity 

This is a critical problem because the batches are smaller than the total tokens sold, which means we're restricting them on a % basis on a fraction of our intended cap.

**Comment by area** [comment]
> The user should be capped against the total token sale quantity

This is not the spec we were [given on the contracts side](https://github.com/JoinColony/colonyNetwork/issues/952), which was that the maximum should be applied to the total number of tokens _already sold_. I believe the justification was, in principle, whoever is running the sale does not know if  coinMachine will be topped up in the future, we do not know if we will be ending the sale early, and even if we did, we want no person at any point, even mid-sale, to own more than whatever the limit is.

For clarity, of course, there is a wrinkle at the start of the sale - no tokens have been sold and so only allowing users to buy some fraction of 0 would not allow anyone to buy any tokens. Therefore, at the start of a sale, if the total number of tokens sold is less than the target per period, we assume that the total number of tokens sold is equal to the target per period.

In your example,  I believe the behavior you'll be seeing is:

> Attempt to purchase Max amount

User successfully purchases, I believe, 5.5555555.... tokens

> Attempt to purchase Max amount in next batch

User is unable to buy anything. The total sold (5.55555...) is still less than the target per period (which is 50), and so the user has bought their entire allowance. Once the total tokens sold is greater than 55.55555, they will be able to start buying tokens again (taking them up to 10% of the tokens sold each time).

**Comment by thycommodore** [comment]
Thanks for weighing in on this @area, I see what you're saying here in these early batches.

I'll try to say that back — while the tokens sold are low (as compared to the tokens sent to coin machine), the user may run into this case as they try to acquire into their capped %. While the tokens sold are high, the user is less likely to run into this case. 

I'm probably making some user behavior / economic assumptions here, but perhaps generally speaking this may be true?

**Comment by jakzilla** [comment]
I think there has been a miscommunication here. I appreciate that this is a satisfying solution mathematically, but this is a very problematic solution from a user perspective as it makes the UX of buying tokens extremely annoying. Unless we can fix this before the sale I don't see any solution other than making the cap either very high or removing it altogether.

**Comment by area** [comment]
What does 'fixed' mean?

**Comment by rdig** [comment]
@alicjakujawa I've unassigned you from this, since the fix for this requires contract changes, after which I need to build a new `colonyJS` client, release it, then do a new deployement

**Comment by area** [comment]
The new behaviour is now available on QA.
