### ISSUE TITLE
Overlapping banner on motions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#2996]
## Steps to reproduce

1. Create a motion
2. Ensure page length is long enough to scroll

## Expected behaviour

* Banner should be pinned to top of the content area and not overlap scroll bar.

## Actual behaviour

* Banner is overlapping the content and the scrollbar

![motion-banner-overlaps](https://user-images.githubusercontent.com/33682027/144486546-5661c2d2-bf46-4212-b7e6-bbc5ec513daf.png)

## Suggestions

* Banner should not be fixed,
* Should be fixed to the top of the screen on scroll, or
* Have the main top header stay fixed at the top of the screen along with the banner

**Comment by rdig** [comment]
Thanks for opening this @arrenv 

I have reserved this for an external collaborator

**Comment by danbr** [comment]
Bug discovered in QA:
Padding missing when Motions and Disputes extension is not enabled

https://qaxdai.colony.io/colony/cooldao/tx/0x7bdb3439874d3cf012b0c005b85f6b32323f76c10b5196d4699291dd242d8b71
https://qaxdai.colony.io/colony/roadrunner/tx/0xc1fd6ebf9fa031076def2cc3010aaff31b20d2d73bd5753511bcf8eb74c17e1c
