### ISSUE TITLE
"Report Bugs" in the top right dropdown menu still links to Canny.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#3001]
SHould be linking to: https://portal.productboard.com/colony/1-colony-portal/tabs/4-bugs

**Comment by arrenv** [comment]
Confirming, this should now link to the same location as the 'We {heart} feedback!' link in the bottom right.
i.e. https://portal.productboard.com/colony/1-colony-portal/tabs/4-bugs

**Comment by thycommodore** [comment]
@arrenv correct!

**Comment by thycommodore** [comment]
@arrenv I hopped in and resolved the issue w/ a commit, will wait for the merge

**Comment by rdig** [comment]
> @arrenv I hopped in and resolved the issue w/ a commit, will wait for the merge

Link it to this issue then with one of the supported keywords: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

Also, very nice for taking the initiative and opening a PR :100:
