### ISSUE TITLE
"Members: All Teams" doesn't show wallets with accrued reputation

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3002]
## Steps to reproduce

1. Check out Swashbuckle's view ([link](https://qaxdai.colony.io/colony/roadrunner/members))
2. Switch to Root view 

![image](https://user-images.githubusercontent.com/89165465/144626580-bbd83bf6-d724-4327-aa77-7c01ea238f1b.png)

![image](https://user-images.githubusercontent.com/89165465/144627317-b016820d-e352-4186-bcaf-fdc23770987f.png)

## Expected behaviour

* All Team's view shows all users who are watching + users with reputation (basically hybrid of Root + All)

## Actual behaviour

* Appears to only show users, not wallets

## Thoughts

* If a member is part of the root view, they should most likely be in the All view.
* The reason this leads to a potential issue is that the reputation doesn't add up to 100% within the All view, which is nonsensical from a UX perspective.

**Comment by rdig** [comment]
This is not a "bug" per se, this is an improvement, as this is what we decided at the time the implementation will look like _(the members page did not get a lot of love)_

There's so much more to actually improve here:
- per item loading state (until the reputation fetching call finishes)
- until the reputation fetch finishes we don't display the user's username / display name, only the address

I think there's more, that's just what I remember from the top of my head.

**Comment by arrenv** [comment]
If I am touching up the members page, would it be worth looking into sorting by reputation at all? Considering @rdig's comments in https://github.com/JoinColony/colonyDapp/pull/2981 regarding it all having to be done client-side.

**Comment by rdig** [comment]
I mean yeah, this issue is actually relevant, "all teams" should be subscribed users + users with reputation in root, sorted by reputation
