### ISSUE TITLE
Buying last available tokens at the end of the batch presents incorrect experience

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3003]
## Steps to reproduce

1. Enable Coin Machine (set time period to like `0.2`)
2. Send in a small amount of tokens (like 100)
3. Buy the max tokens available near the very end of the batch (like 10 secs remaining)

![image](https://user-images.githubusercontent.com/89165465/144632528-acdd1b65-1055-4bcb-988c-27b08bba8f66.png)

## Expected behaviour

* Successful purchase
* OR if unsuccessful then unsuccessful UX (ie not CLNY as the default token listed, note the purchase above was in MEEP)
* No red box or text "Next sale starts in" if the sale is over

## Actual behaviour

* In this case, it was a successful sale (see below). But the UI says it was unsuccessful and says CLNY.

![image](https://user-images.githubusercontent.com/89165465/144632983-a60fad5c-ff47-4c84-aa8e-8f65b99b3bb6.png)

**Comment by arrenv** [comment]
@thycommodore I have been attempting to replicate this in the local dev environment. Although, I have not been able to do so yet. Originally, I thought it may be due to loading speeds, however I have tested buying every second up until the last second, as well as dev tools network throttling.

I will try a few other things and check if anyone else has been able to replicate.

Regardless the failed purchase screen can be fixed here.

**Comment by thycommodore** [comment]
@arrenv this is an annoying one to replicate. Thinking through it, try doing the 1st transaction at the near end. It does seem that the following transactions seem to perform better — but I can try again on QA branch.

**Comment by area** [comment]
The difference between dev and production might be that transactions are mined straight away in dev, but not on production. You can toggle that behaviour via the [`miner_start`](https://geth.ethereum.org/docs/rpc/ns-miner#miner_start) and `miner_stop` RPC commands, and explicitly mine blocks with the ganache-specific [`evm_mine`](https://geth.ethereum.org/docs/rpc/ns-miner#miner_start).

Specifically, try sending the transaction before the window expires, but the block only being mined afterwards.
