### ISSUE TITLE
Previous Coin Machine sale data populates in "Previous batches" box in a redeployment of a Coin Machine sale

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3006]
UPDATE: This might be working as expected. I'm realizing the replication may have not uninstalled, which means this is operating on the same contract — which would mean this is working as expected. Working to replicate...

## Steps to reproduce

1. Setup a Coin Machine w/ `period length = 0.2`(note your settings)
2. Send 100 tokens to start Coin Machine
2. 1st batch, buy 1 token
3. 2nd batch, buy 1 token
4. 3rd batch, buy 98 tokens
5. Uninstall Coin Machine
6. Reinstall Coin Machine w/ same settings
7. Send 100 tokens to start Coin Machine
8. View "Previous batches" table
9. Wait until the time period passes at least twice

## Expected behaviour

* "Previous batches" table remains blank

## Actual behaviour

* "Previous batches" starts out blank, but upon the reset it seems to pull the previous deployment of Coin Machine's prior data. 

## Priority (optional)

* I'm not sure how important this is due to the low probability of this case being played out. But if the data persists over longer periods of time it could be potentially a more important challenge. Additionally, I'm making the assumption this is a visual bug. I need to test if the old data is impacting the pricing — in that case it would be an important issue.

**Comment by arrenv** [comment]
@thycommodore were you experiencing this recently? This recent PR #2970 should have fixed this.

**Comment by rdig** [comment]
Yes, it did fix it, it was just not deployed.

**Comment by arrenv** [comment]
Is this after a redeployment of the extension? I have just tested locally on the latest.

![clearing-previous-batches](https://user-images.githubusercontent.com/33682027/145201096-b25d78d9-2887-41ca-8a4b-4478ad956847.gif)

**Comment by area** [comment]
It was after a redeployment, yes. What is 'the latest'?

**Comment by arrenv** [comment]
The latest at the time was [`17d8a43`](https://github.com/JoinColony/colonyDapp/commit/17d8a43d748fdf3c45e12a119eb727cae948fa1a), which looks to be the same as yours :)

**Comment by area** [comment]
Did you fast-forward through several periods?

**Comment by area** [comment]
I mean in the newly deployed CoinMachine.

**Comment by arrenv** [comment]
No forced fast-forwarding in the new CoinMachine, the gif above is pretty much real-time.

**Comment by arrenv** [comment]
Unless it is happening and I am not aware of it. Or, I am misunderstanding something.

**Comment by arrenv** [comment]
After testing this with Alex over video, I have been able to replicate this issue.

1. Ensure there is data in an existing CoinMachine.
2. Depreciate and Uninstall CoinMachine.
3. Set up new CoinMachine with the default settings and fund it.
4. Don't purchase any tokens and fast-forward the chain by a few hours. You can do so with the following command, running it in your terminal a few times.

`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600],"id": 1}' localhost:8545 && curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[]}' localhost:8545`

5. Refresh the page, the previous CoinMachine data will be present.

Additional steps:
1. Buy some tokens.
2. Fast-forward the chain by another hour.

`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600],"id": 1}' localhost:8545 && curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[]}' localhost:8545`

3. Refresh the CoinMachine page. You should see the correct take sale data.
