### ISSUE TITLE
Coin Machine batches when price is not progressing have the wrong price.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#3010]
These should really say 50 rather than 0.

![Screenshot 2021-12-06 at 22 43 59](https://user-images.githubusercontent.com/4774274/144934777-3104650c-3df8-4d63-a98d-1ff9d1f5caf7.png)

**Comment by rdig** [comment]
So which one is it? 
- The wrong price of the initial batches
- Don't show if the price doesn't progress

**Comment by rdig** [comment]
This will be fixed by #2938 when I fix [the initial price](https://github.com/JoinColony/colonyDapp/issues/2938#issuecomment-975307170)
