### ISSUE TITLE
Local state issue with commenting

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3013]
## Steps to reproduce

1. Navigate to two different instances where comments are used in the Dapp within different browser tabs. E.g., two different actions, or an action and the coin machine.
2. Comment in one tab and switch to the other tab to see comment appear.
3. Comment in this tab, switch back to the previous tab and notice comments have changed to other tab.
4. Reloading both pages shows correct comments in each respective location.

## Expected behaviour

* Each comment section should only show the relevant comments for their respective location.

## Actual behaviour

* Comments are pulled from a single state.

![comments-between-tabs-progress](https://user-images.githubusercontent.com/33682027/145037065-dce6f06c-c769-4bbf-a15f-8d749d37beb6.gif)

**Comment by rdig** [comment]
This was fixed and was deployed yesterday into production.

Where did you replicate this?

**Comment by arrenv** [comment]
This was just locally, in the past hour. I will double check I have the latest version and try again. And test QA and production.

**Comment by rdig** [comment]
Make sure to run `npm run provision` since the fix for this was added server side

**Comment by arrenv** [comment]
Thank you, that was it, works great by the way. Closing now.
