### ISSUE TITLE
AvatarDropdown error if user is not signed up to or hasn't visited a Colony

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3014]
## Steps to reproduce

1. Open a browser instance with a clear cache.
2. Navigate to https://qaxdai.colony.io/landing, without visiting a Colony
3. Create a new user account
4. Click on the Avatar in the top right

## Expected behaviour

* Should open the AvatarDropdown menu

## Actual behaviour

* Blank error screen

![no-colonyName-indropdown-check](https://user-images.githubusercontent.com/33682027/145055873-e005419c-5aa6-4ef5-ae2b-c4a4df198f10.gif)

**Comment by rdig** [comment]
Fixed by da1db9e513c846319d7b2c3c6882a3aea3d15bff...1959dfb15c5ff2b38c760d73e0441695a10d0f17
