### ISSUE TITLE
Coin Machine chat is disabled incorrectly

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3018]
## Steps to reproduce

1. Start a coin machine
2. View the chat
3. Send funds to start the coin machine
4. View the chat

## Expected behaviour

* The chat should be enabled on (4)

## Actual behaviour

* The chat continues to be disabled

![image](https://user-images.githubusercontent.com/89165465/145128774-89d0a14b-4c5b-4292-bec3-8bfa2c2297ef.png)

**Comment by rdig** [comment]
This is not a bug, nor a feature.

There is no actual logic related to this. We just manually, hardcoded, the chat to be disabled. This was only supposed to be deployed into production, but I guess I ledt the production code on QA as well
