### ISSUE TITLE
Incorrect CoinMachine batch Sold out message when reloading page

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3024]
## Steps to reproduce

1. Enable CoinMachine and fund it.
2. Purchase a portion of the available batch
3. Reload the page.

## Expected behaviour

* Refreshing the page should not cause the batch to be sold out when it is not.

## Actual behaviour

* Batch is incorrectly marked as sold out after reloading the page.
* Even after refreshing again, or letting the next batch start it is still marked as sold out.
* The only way to fix it is to re-fund the CoinMachine.

![soldout-after-refresh-cant-fix-until-funding](https://user-images.githubusercontent.com/33682027/145557719-470f41cc-8dec-474d-8f82-4e33e74365bb.gif)

I can easily replicate this in my local environment (I have not tested in QA, currently under maintenance), however, let me know if localised to me or a symptom of the local dev environment.

**Comment by ArmandoGraterol** [comment]
I can also replicate it in my dev env using the params that are in your gif. Will investigate further!

**Comment by rdig** [comment]
I've fixed this live, while the Token Sale was ongoing, here are the changes:
- https://github.com/JoinColony/colonyDapp/commit/1cace0fa0a252998afb3c83b3abaade6e09c6336
- https://github.com/JoinColony/colonyDapp/commit/a9b06af4d8f60116728bee720f341cfb5f06f4f2
- https://github.com/JoinColony/colonyDapp/commit/02d818d6b0479bfec56f035a416cb5188a51bbf5
