### ISSUE TITLE
Add a UI element if a token is locked

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyDapp#3034]
In the "funds" view, adding some UI element (such as a lock icon) on tokens which are locked would be helpful.

**Comment by arrenv** [comment]
@kronosapiens do you mean something like the in the following screenshots.

![locked-token](https://user-images.githubusercontent.com/33682027/146212907-c342dc05-34b7-4162-a845-bd0a8d8df6e6.jpg)

![locked-token-2](https://user-images.githubusercontent.com/33682027/146212910-3ba416f8-cfa3-44c2-b0b5-403704b6a59e.jpg)

**Comment by kronosapiens** [comment]
Yes exactly!

**Comment by rdig** [comment]
Was this first agreed with product before you started working on it @arrenv  ?

**Comment by arrenv** [comment]
@rdig Yes, this was discussed with Karol. He also mentioned adding in a tooltip. I am about to put a post in product to confirm all locations it may be beneficial to include in.
