### ISSUE TITLE
Extensions container breaks out of content container

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3035]
## Steps to reproduce

1. Navigate to an extensions page.
2. Notice horizontal scroll and highlight the extension container

## Expected behaviour

* Extension pages should fit within its container.
* It should not cause a horizontal scroll on only extension pages.

## Actual behaviour

* Extension pages overflows out of its containers.

![extensions-sidebar-overflowing](https://user-images.githubusercontent.com/33682027/146009419-3d20fd1b-88db-429e-bd0f-f79d141206e1.jpg)

**Comment by ArmandoGraterol** [comment]
@arrenv What's the screen size that you are using in the screenshot? I've managed to replicate it but I want to be sure

**Comment by arrenv** [comment]
@ArmandoGraterol the screenshot is at around 1500 x 920px, however, on my end the overflow starts at 1600px.
