### ISSUE TITLE
Dynamic page titles throughout Dapp routes

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3036]
**IMPORTANT**: This is only a suggestion at the moment, this will need to be raised with Product.

## Steps to reproduce

1. Navigate to any page and view the page title.

## Expected behaviour

* Each page route should have a dynamic page title, with Colony's name and route title.

## Actual behaviour

* All page routes simply have 'Colony'

![dynamic-page-titles](https://user-images.githubusercontent.com/33682027/146014295-7fe46c85-3e4b-4afe-9ca1-0b6a324023d3.png)

## Suggestions

* Use this page title format: "<ROUTE_TITLE> | Colony - <COLONY_NAME>"
* On pages like motion and transaction pages use: "<ACTION/MOTION_TITLE> | Colony -  <COLONY_NAME>"

**Comment by rdig** [comment]
Where is this coming from? This product ask for this ?

**Comment by arrenv** [comment]
@rdig this is just a suggestion at the moment, within the maintenance Inbox. I have not raised with Product yet as there were other priorities at the time.

**Comment by danbr** [comment]
Using forward/back button in Chrome to navigate Colony pages could be improved. The page title is missing, making navigation difficult. 

<img width="393" alt="Screenshot 2022-01-21 at 16 19 51" src="https://user-images.githubusercontent.com/582700/150609806-c5254431-98f9-43a7-b54b-5648fc8a29e4.png">

<img width="995" alt="Screenshot 2022-01-21 at 16 23 10" src="https://user-images.githubusercontent.com/582700/150609810-104fbf35-0dc0-43b9-8f47-4acbeba80131.png">

I think resolving this issue would provide the details for the browser to use in the history.

Also, as you can see, I use a dark theme in Chrome, making the Colony (fav)icon difficult to identify. Perhaps we can support both light & dark themes (in theory as a goal, as resources allow) - or use a (fav)icon that is identifiable in both themes.
