### ISSUE TITLE
Option to transfer funds out of CoinMachine

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3037]
## Steps to reproduce

1. Add funds to CoinMachine, 'Deprecate' CoinMachine.
2. Funds are essentially lost from within the Dapp UI.

## Expected behaviour

* Should be a prompt to allow user to transfer funds out of CoinMachine before depreciating.

## Actual behaviour

* You can depreciate a CoinMachine contract with funds still withheld in it.

## Suggestions

* Could include a prompt to transfer funds out of CoinMachine, back into colony.

![transfer-funds-in-coinmachine](https://user-images.githubusercontent.com/33682027/146029513-32656886-210c-4f03-9a99-3f16e25a1775.png)

* Could add in a row within the CoinMachine extension page with totals funds currently in the contract.

![total-funds-coinmachine](https://user-images.githubusercontent.com/33682027/146029543-be8e9e15-70e2-444a-92a7-a14b1f69dfbb.png)

**Comment by rdig** [comment]
I'm closing this for now, as there will be some refactoring around the Coin Machine controls part, which will most likely encompass this
