### ISSUE TITLE
Missing number formatting in various locations

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3040]
## Steps to reproduce

1. Refer to screenshots below.
2. Utilise the CoinMachine.
3. Perform a payment action.

## Expected behaviour

* Number formatting could be added to various locations.

## Actual behaviour

* Lack of number formatting makes readability difficulty in some locations.

![number-formatting-2](https://user-images.githubusercontent.com/33682027/146037908-008235fa-343b-406b-921b-6090f74afdca.jpg)

![number-formatting](https://user-images.githubusercontent.com/33682027/146037912-507d5c6c-892f-4433-bbe4-b0602d95ce9c.jpg)

**Comment by rdig** [comment]
Don't start work on this as we'll have a proper maintenace feature that will solve this. 

Closing.
