### ISSUE TITLE
Easily add the token of a colony to a users wallet

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3042]
### Story

A user joins a colony and wants to add a colony's tokens to their wallet. It would be great to have a button that easily adds the token to their wallet.

### Description

This functionality should already be within the Dapp as mentioned by @rdig, it should only require a button that hooks into this functionality. This will likely require a design that incorporates this functionality.

EDIT: Please see @rdig's comment below for context on current implementation.

Some location suggestions:

![add-token-to-wallet](https://user-images.githubusercontent.com/33682027/146042443-205bdc6f-d6f9-4f10-997b-46fdeddf0dd2.png)

![add-token-to-wallet-2](https://user-images.githubusercontent.com/33682027/146042447-ee5143df-d5b7-4c55-9036-e9287f237c3b.png)

### Design 

Needs to be done.

**Comment by rdig** [comment]
For the wallets we use within the dapp, we currently use the `@purser` library _(ours)_ so please don't link directly to the metamask docs as it causes confusion.

If any metamask related features needs to be used in the dapp, it first needs to be added to `purser`, then that linked within the dapp.

This is the commit I've added that adds that functionality to the Token `InfoPopover` component: https://github.com/JoinColony/colonyDapp/commit/3bce9c534b897edf7ab3fd1e4634f8146719c73d

However, there's more places than this that we would need this functionality added _(basically everywhere we list tokens)_, so please check with product and come up with a proper solution for all places we would need this.
