### ISSUE TITLE
Duplicate events appearing on Events page.

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3045]
## Steps to reproduce

1. Go to the events page of the live MetaColony page and leave it loaded for long enough (a couple of minutes should be fine).
2. You should see events being duplicated.

## Expected behaviour

* Only one of each event should be visible on the event page.

## Actual behaviour

* Event items are being duplicated several times.
* Eventually the page crashes from too many duplicated events.

![duplicate-events-appearing](https://user-images.githubusercontent.com/33682027/146156506-4a49f49a-a86d-4d78-ac64-fe927dacc029.jpg)

![duplicate-events-appearing](https://user-images.githubusercontent.com/33682027/146156509-cb25d0aa-af24-4e05-84f4-33eeb24e68d3.gif)

## Suggestions

* It may be a good idea to have an option to load more events for the user manually.
For example, sitting above the events list, if there are new events, could be a call to action with the text:
'There are 11 new events... Load events'.

![example-load-more-option](https://user-images.githubusercontent.com/33682027/146171462-70dfdf38-ed0d-4d67-aff0-df3a08504d10.png)

**Comment by rdig** [comment]
This is coming from the way do pagination, and storing the events in the state.

First "chunk" of events that the websocket pulls in is what causes this. It can be solved, just that it needs a lot of trial and error to get right
