### ISSUE TITLE
Max button does not work if max value is a decimal

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3046]
## Steps to reproduce

1. Ensure CoinMachine is enabled and funded.
2. Ensure your wallet balance is low enough so that you are buying less then 1 token.
3. Click the 'Max' button under the amount to buy input.

## Expected behaviour

* Max button should allow decimal values.

## Actual behaviour

* Clicking max causes an error when the maximum purchasable is a decimal value.

![max-button-decimals](https://user-images.githubusercontent.com/33682027/146174870-3ea1dd77-2292-4cd3-92b0-16019d79137a.gif)

**Comment by rdig** [comment]
Fixed already

**Comment by arrenv** [comment]
Thanks for the update, I will close this.

**Comment by rdig** [comment]
Sure, but this still needs to make it's way into master, as it's just on the branch I was using for the Token Sale.

This is the change I've added: https://github.com/JoinColony/colonyDapp/commit/f60ba7ae27138285237ff53b65f7b8ca869b8af2

Please have a look at it, clean it up _(I think I have some hard coded values in there)_ and then open a PR for it

**Comment by arrenv** [comment]
Potentially solvable with #3065

**Comment by chinins** [comment]
I've checked on master with different numbers and also on Dan's machine and I couldn't replicate... Maybe it was already fixed...

**Comment by arrenv** [comment]
@chinins what have you been getting? There definitely seems to be an issue here.

The below gif is from two different colonies, the first with a high value (1000ETH/CLO) to simulate enough funds to only purchase a decimal amount. The other with a low cost of (0.1ETH/CLO) to simulate enough funds to buy whole integer amounts.

![max-button-with-decimals](https://user-images.githubusercontent.com/33682027/150779406-08913818-07d8-4241-ba9d-37a8425677a2.gif)
