### ISSUE TITLE
Total time/batches left or indication of final batches

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3047]
### Story

Based on the comments in the MetaColony sale, it seems as though it would be good to have an indication of how long a token sale is going to last for. Or, better yet, appear when there are only a couple of batches left or that this is the final batch.

### Description

Add a UI element to indicate either the total time of the sale, or have an indication that these are the last few batches.

### Design

Not yet done.

### Suggestions

* There following screenshot provides one example of how this could look.

![batches-time-left](https://user-images.githubusercontent.com/33682027/146176170-9abd44ab-ebb7-4ef2-8293-5b22aace3e14.png)

**Comment by rdig** [comment]
Batches are not a fixed number, the coin machine generates batches until it runs out of coins. And if you fund it again after, it would start the batches again.

So there isn't any proper way of knowing the total number of batches

**Comment by arrenv** [comment]
Yes, true. I will close this.
