### ISSUE TITLE
Better way to handle long strings in comments

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3048]
## Description

To fix the broken comment boxes, due to large strings, comments have been wrapped which currently breaks words within comments.

## Expected behaviour

* Whole words should be visible.
* Long strings should be accomodated.

## Actual behaviour

* Words are currently broken within the comments.

### Current

![broken-words-2](https://user-images.githubusercontent.com/33682027/146224456-39349536-2112-4574-91b8-62d0c95def3e.png)

### Previously

![broken-words](https://user-images.githubusercontent.com/33682027/146224466-46128c8b-e83e-4b29-a5a0-0fab40295e7f.png)

## Suggestion

* We could break by whole words and break strings up that are over a certain number of characters

**Comment by rdig** [comment]
This fixes yet, but it's still on the live production branch: https://github.com/JoinColony/colonyDapp/commit/c8ee23a421dfafc38c6cbb4b3508ee5d89c8c130

**Comment by agustif** [comment]
We could move it to use word-break and hyphens

```diff
- line-break: anywhere;
+ word-break: break-word;
+ hyphens: auto;
```
![image](https://user-images.githubusercontent.com/6601142/146244061-6afd167e-631d-4ff4-ad51-f92973887fca.png)

Does that look like a better solution to you?

**Comment by arrenv** [comment]
@agustif it is a workable solution, my biggest hesitation in using the hyphens would be in creating broken URLs.
