### ISSUE TITLE
Passed motions from within a team, don't appear in the team filtered view

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3056]
## Steps to reproduce

1. Create a motion (expenditure) in a team
2. Stake, finalize, claim, the motion
3. View the motion from root
4. View the team's view

![image](https://user-images.githubusercontent.com/89165465/146454703-3346a5b6-9757-4b3f-82f5-b84c25d5de3b.png)

**Example**

1. Go to https://xdai.colony.io/colony/shapeshift
2. Load more actions until you get to Dec 11, 2021
3. See `Pay Diggy Smalls 2,212.907 FOX` motion
4. Click the motion
5. Note the motion was created in `Product` from `Product`
6. Go back and view the `Product` drop down
7. Scroll to Dec 11th, look for `Pay Diggy Smalls 2,212.907 FOX` motion

You'll notice that it's not visible. 

## Expected behaviour

* Motions completed within a team are shown within the team filtered view

## Actual behaviour

* The internal team motion is not visible from the team filtered view

**Comment by thycommodore** [comment]
From Shapeshift:

"We were hoping to reconcile all of the deposits and payments from product workstream asap and it would definitely be easier if we could filter. Certainly would be nice to have

Alternatively, if you guys have another suggestion for how we can easily get a complete "tx history" for the product workstream (all incoming and outgoing transfers), this would be much less urgent."

**Comment by arrenv** [comment]
From my understanding, this is due to the max query limit of the SubGraph.

I will look into the possibility of access to a hosted SubGraph explorer, search functionality, or maybe a CSV export for them.

**Comment by rdig** [comment]
@arrenv 

This might actually be a bug with how we filter motions, something from Dec 11th shouldn't trigger the 1000 items limit.

An another note:

> access to a hosted SubGraph explorer,

Valid idea, but not possible currently

> maybe a CSV export for them

Not possible directly, unless you manually (or via a script) create that CSV file

**Comment by arrenv** [comment]
@rdig Thank you for clarification, I will look into the filtering.

**Comment by arrenv** [comment]
I've been able to reliably replicate this locally, looking into a resolution now.
