### ISSUE TITLE
Motion created in a team shows as being created in Root from the All Teams view

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3057]
## Steps to reproduce

1. Go to https://xdai.colony.io/colony/shapeshift
2. Load more actions until you get to Dec 11, 2021
3. Note `Pay Diggy Smalls 2,212.907 FOX` motion
4. Note it says `11 Dec | Root`
5. Click into the motion ([link](https://xdai.colony.io/colony/shapeshift/tx/0xec7120def67d1fa9831d1346978a2081756631918a21a278f140f26e9daa67f1))

## Expected behaviour

* Motion is shown from Product

## Actual behaviour

![image](https://user-images.githubusercontent.com/89165465/146455948-b1bf93ab-b714-41c7-ac09-2a50afb20b50.png)

**Comment by arrenv** [comment]
This should be resolved by #3077
