### ISSUE TITLE
Coin Machine Paused State

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#3060]
Since we had to pause the Token Sale, we had to implement a quick interface for it, since our default behavior for when the extension is deprecated is just to hide the Coin Machine page.

![Screenshot from 2021-12-20 11-47-53](https://user-images.githubusercontent.com/1193222/146748222-4e1c2ab0-f228-4c67-93ab-99b3445df4f8.png)

This will most likely prove useful in the future, both for us, and for others.

As such, talk to product about this, and what improvements they want to include, after that, see my changes that produced the above interface: https://github.com/JoinColony/colonyDapp/commit/e61dcfbd5dde1c1f7f32ecbc23a2c8463f201f8a

Things to note:
- currently it's impossible to re-start the sale, as the interface doesn't support it _(the resolver will create entries for all the periods in which the coin machine was "paused")_
- need to find a better way to detect that the coin machine is paused (based on time), rather than just using the `deprecate` check from the contracts

**Comment by arrenv** [comment]
I have raised this with Karol, as he is currently working on a couple of revisions to CoinMachine.

**Comment by arrenv** [comment]
Being handled by CoinMachine project.
