### ISSUE TITLE
Motions within team are being presented as Forced

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3070]
## Steps to reproduce

1. Submit an expenditure as a motion from within a team
2. Finalize the motion
3. View the All Teams Action view

## Expected behaviour

* The expenditure motion is shown as a successfully executed motion

## Actual behaviour

* The expenditure motion appears at the root level
* There's an additional forced expenditure at the team level

![image](https://user-images.githubusercontent.com/89165465/146990281-d01d7608-f9ac-48e3-b6f4-8d3d6963bfc1.png)

https://xdai.colony.io/colony/test-kh

---

Shapeshift first reported this. In their situation, there are only two users that have the permissions to force an expenditure (willy & diggy smalls). Here's their report:

> We're also noticing that recently passed motions are showing up as forced in the Actions list.
> 
> Example of passed motion being shown as forced: https://xdai.colony.io/colony/shapeshift/tx/0xfb5c700dace17487cfd2da5d5b5b558a4fcdc7efe04552e3f18b41c221aaf20f
> 
> Link to motion: https://xdai.colony.io/colony/shapeshift/tx/0x944f762154e19fa30ba971c4d976ca24bcd84e8d93b07581c8c9081f6c645733

**Comment by agustif** [comment]
I think this could come from here

[DefaultAction.tsx](https://github.com/JoinColony/colonyDapp/blob/b82b9d386dd11f3be8eee178c281302000015ee2/src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx#L170-L188)
