### ISSUE TITLE
Creating a new team doesn't appear as a new team

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3076]
## Steps to reproduce

1. Go to https://xdai.colony.io/colony/swashbuckle
2. Create a new team either as a motion or via permissions
3. Attempt to view the newly created team via the dropdown

## Expected behaviour

* A new team is created and visible

## Actual behaviour

* No new team is visible

**Comment by arrenv** [comment]
@thycommodore there seems to be an issue with getting events from the SubGraph at the moment. We are currently looking into getting this resolved.

**Comment by arrenv** [comment]
This should be resolved now, with the syncing of the SubGraph.
