### ISSUE TITLE
Handling Fraud/Malicious Accounts in a Colony

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3084]
### Story

When a member joins a Colony they become listed within the listed addresses. This can pose a number of issues, with one recently being demonstrated within the Shapeshift Colony, where new users where able to spoof the username and avatar of a notable member in the colony. This could then lead to a false payment being made or incorrect permissions being allocated.

### Description

We need a better way to handle spam/spoof/fraudulent accounts that are created within a colony, such as having the banning of an address having various levels of severity. For example, comment banning, payment banning, action creation banning, and complete removal from and banning from the colony.

We will also need a better way to identify these potential addresses in the address list. Such as having reputation appear within the list of addresses along side the username or having an info box of the selected users appear underneath the selection box with info about the user, such as reputation and joining date.

**NOTE:** This will need to be discussed further to determine a suitable solution. 

**UPDATE** This is currently being spec'd out, broken into staged levels of functionality & implementation.

**Comment by rdig** [comment]
I'm closing this until we get the spec from product
