### ISSUE TITLE
Minting large number of tokens results into display of wrong amount

### ISSUE THREAD

**Issue by dit7ya** [JoinColony/colonyDapp#3095]
## Steps to reproduce

1. Create a colony
2. Mint `9007199254740991000000` native tokens (this is `Number.MAX_SAFE_INTEGER * 100000` in JavaScript)

![Screenshot 2022-01-12 at 16-09-46 Colony](https://user-images.githubusercontent.com/14034137/149124993-b973b274-04af-44f7-9745-282e9f01f36d.png)

3. Check All Teams actions view 

## Expected behaviour

Should display the correct amount minted

## Actual behaviour

Shows `9` token minted

![Screenshot 2022-01-12 at 16-09-03 Colony](https://user-images.githubusercontent.com/14034137/149124874-6484be4a-cc5e-48c9-b745-f6fac7c5223d.png)

**Comment by dit7ya** [comment]
This seems to be due to https://github.com/JoinColony/colonyDapp/blob/f09f84ca4c54cc4ae59e00fd0089bdb439230bf0/src/utils/numbers/formatTokenValue.ts#L49

The `formatNumber` function expects a number but `parseFloat` loses precision if the number is too big. 

I will investigate more tomorrow and report here.

**Comment by rdig** [comment]
I think we can use `BigDecimal` to solve this. Please investigate and let me know

**Comment by arrenv** [comment]
This appears to be getting resolved by the `Standardized Numbers Display` project - https://github.com/JoinColony/colonyDapp/projects/22
