### ISSUE TITLE
Improve alignment of avatar in notifications popover

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3098]
## Steps to reproduce

1. Create a first transaction in the dapp
2. Check the notifications popover
3. Notice the misalignment of the icon in the notifications

## Expected behaviour

* Icon should be vertically centered with the text

See spec here - https://www.figma.com/file/OD53CoZpRKVqDdKsMYGldko8/Inbox?node-id=194%3A0

## Actual behaviour

* Icon is aligned below the inline text.

![alignment-of-avatar-notification](https://user-images.githubusercontent.com/33682027/149309198-b4cd8b62-7c58-4192-8ef9-4fbf3aeaebb2.png)

**Comment by rdig** [comment]
Reserved for @dit7ya

**Comment by Krish-bhardwaj** [comment]
Hi i am fresher i would like to contribute to your opensource project i have exp in Js , nodejs , docker if you can assign me this issue and share contribution details i can solve this
