### ISSUE TITLE
Update motion logic for Unlock token dialog

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyDapp#3118]
Should be done once Armando merges #2985 and the unlock token feature branch is rebased on master to include Armando's changes.

**Comment by arrenv** [comment]
@chinins I rebased and added a commit to fix some clashes with the branch and Armando's changes. Could you please confirm that the current state of https://github.com/JoinColony/colonyDapp/pull/2993 resolves this issue.

**Comment by chinins** [comment]
> @chinins I rebased and added a commit to fix some clashes with the branch and Armando's changes. Could you please confirm that the current state of #2993 resolves this issue.

@arrenv , the current state of #2993 doesn't resolve this. But worry not, it's a quick one :)
