### ISSUE TITLE
Availabe Funds Not Updating

### ISSUE THREAD

**Issue by Mentors4EDU** [JoinColony/colonyDapp#3127]
For DAOs that have their own ERC20 token made, whenever you send tokens from an altcoin and then try to add that address in (on the XDAI) network, it doesn't show up under the available funds. This is true even after doing a claim and so forth. This doesn't happen for DAOs that don't have a token created, and this is very problematic.

**Comment by arrenv** [comment]
Hey @Mentors4EDU I have been testing this one and have not been able to replicate. Funds are showing up correctly.

**Are you able to provide any more details?** Such as, the address of the DAO this is for, the token contract address you are adding.

For context, this is what I have been testing based on what I understand from your raised issue:

1. Create a Colony with an existing ERC-20 token.
2. Send an amount of that ERC-20 token to the Colony.
3. Claim the funds under Events
4. Funds appear correctly in the available funds area.

![013d200a-ff22-4d2f-9d8a-0ec246b9a458](https://user-images.githubusercontent.com/33682027/150754080-b8fe6153-1856-4309-aaf7-1b90c19f4ceb.png)

**Comment by Mentors4EDU** [comment]
Hi @arrenv 
The problem arrives when you create a Colony with a new ERC-20 token (rather then existing) and then send other ERC-20 tokens to that colony. Even if you import the contract address and claim it, it still doesn't recognize new tokens or altcoins.

**Comment by arrenv** [comment]
Hi @Mentors4EDU,

Have you added the token to your Colony, via the Funds page?

![adding-tokens](https://user-images.githubusercontent.com/33682027/150838029-4d12b885-e65d-44d3-ba20-41d517d1e9ee.gif)

**Comment by Mentors4EDU** [comment]
Yes I have. The issue have been fixed yesterday which is weird because the UI page didn't update for like an hour after the blocks were confirmed. Could have been a problem with internet cache, that I'm not sure of. My last question is how do you add members if you have a list of addresses you want to add or do you have to get then to each click join individually?

**Comment by arrenv** [comment]
@Mentors4EDU great to hear you were able to resolve it.

Sure, happy to help.

Yes, you will need to get them to join manually, so they can connect their wallet and create a username.

You may also like to put your issues and questions in the Colony Discord, so, more of the team can see it and help out.

I will close this issue now.
