### ISSUE TITLE
Update Reputation styling, hover state, and add Tooltip in header

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3129]
## Description

To ensure the Dapp matches the design, the styling of the reputation value in the header needs to be updated.

There also needs to be a tooltip added to help provide more context to what the value represents.

1. You will need to ensure the Motions & Reputation extension is installed.
2. You will need to double check the appearance with and without a value for reputation.

## Expected behaviour

* The design should match the spec
* There should be a hover state
* There should be a tooltip with the copy "You have {REPUTATION_VALUE}% of the reputation in this colony."

[DESIGN] - https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Style-Guide?node-id=2905%3A0

![reputation-star-hover-state](https://user-images.githubusercontent.com/33682027/150817196-55832295-926b-42ef-bc5d-e4a027d8d372.jpg)

## Actual behaviour

* The star is in the wrong location, there is no hover state, and no tooltip.

![reputation-star](https://user-images.githubusercontent.com/33682027/150817226-56d413d6-cbda-4025-9418-6cbbd57ef86d.jpg)

**Comment by dit7ya** [comment]
@arrenv Turns out there is a hover state on the star icon only (via the `title` property). We should be removing that before adding a tooltip to the whole button, right?

**Comment by arrenv** [comment]
@dit7ya Yes, the title tag can be removed and replaced with the tooltip.
