### ISSUE TITLE
Wrong token displayed in Events log after Claiming

### ISSUE THREAD

**Issue by lightnode** [JoinColony/colonyDapp#3148]
## Steps to reproduce

1. Send CLNY (in this case) to a colony (note: CLNY had not been added through the Manage tokens flow yet)
2. Claim on Events page
3. The output in the Events log displays that the native token for that colony is what got claimed

## Expected behaviour

"<user> claimed <amount>CLNY for colony" displayed in Events log

## Actual behaviour

<user> claimed <amount><nativeColonyToken> for colony" displayed in Events log

**Comment by lightnode** [comment]
This is related to #3149 

When the tokens are successfully added as an option in the colony, the name in the Events log updates to the correct token name

**Comment by arrenv** [comment]
@lightnode Thank you for reporting this one. I will look into it.
