### ISSUE TITLE
Change Numbro abbreviations to use uppercase.

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3168]
Currently, the abbreviations used within Numbro are based on locale files. For most, if not all locales for English speaking countries use lowercase abbreviations.

https://github.com/BenjaminVanRyseghem/numbro/tree/develop/languages

Confirm with Product that they require English language locales to use uppercase abbreviations. 

For example:

  abbreviations: {
        thousand: "K,
        million: "M,
        billion: "B",
        trillion: "T"
    },

If confirmed, create Colony locale file, and update the code to utilise.

Please branch off refactor/3126-numeral-component

**Comment by arrenv** [comment]
I have scheduled this to be discussed for the Product Sync, as there are varying opinions on this.

**Comment by danbr** [comment]
> 

@arrenv Ok - thanks for the update. When will the discussion take place?
