### ISSUE TITLE
Search out unformatted numbers, and format with `Numbro` based formatter

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3169]
We are moving to standardise the number display within the Dapp.

Some number displays have been updated to use the new formatter, but there are holes, and some unformatted displays still exist.

Search out the unformatted numbers, and format.

**Comment by ArmandoGraterol** [comment]
From what I've been testing, it seems like every instance where the tokens are displayed is using Numbro in any way or another already, which makes sense because we normally only use the old formatted function and `Numeral` to display them,

**Comment by danbr** [comment]
> From what I've been testing, it seems like every instance where the tokens are displayed is using Numbro in any way or another already, which makes sense because we normally only use the old formatted function and `Numeral` to display them,

@ArmandoGraterol - OK well thats good news. I propose that we close the issue, do you agree?

**Comment by ArmandoGraterol** [comment]
I agree! Closing now
