### ISSUE TITLE
Claim funds button does not deactivate after claiming. 

### ISSUE THREAD

**Issue by vgururao** [JoinColony/colonyDapp#3170]
Hello, I think there is a bug in the incoming funds claim workflow in the Events stream. Once an incoming transfer has been claimed, the Claim button remains active and can be pressed again, causing a wasteful xDai transaction. In the example shown, I sent 0.035 WETH to our colony yesterday, claimed it on the colony end last night, and it is still active and can be pressed, and pops up a metamask tx. I unnecessarily "claimed" it twice yesterday.
![ClaimsWorkflowBug](https://user-images.githubusercontent.com/836315/152700456-4cb4841d-fa45-4c51-a08e-92ab4de0798d.png)

## Steps to reproduce

1. Send funds to a colony and claim from events tab

## Expected behaviour

* The claim button is deactivated after the funds are claimed and the tx is confirmed

## Actual behaviour

* The claim button remains active even long after the funds have been claimed and show up in the colony's funds and if clicked, it triggers useless additional transactions that waste xDai. The example in the screenshot is still live, 18h after we did it. 

## Suggestions (optional)

* Put in UI text to not claim multiple times until it is fixed.

**Comment by chinins** [comment]
Thank you for reporting the bug! I'll have a look into it.
