### ISSUE TITLE
Implement display/remove whitelisted addresses logic

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#3180]
## Specification
* Fetch and display colony whitelisted addresses 
* Implement logic of removing addresses from whitelist

### Design (optional, might not be applicable)
https://www.figma.com/file/Phby7kEYihhvGgQn69A314/Verified-Recipients?node-id=81%3A24210

**Comment by alicjakujawa** [comment]
Blocked by https://github.com/JoinColony/colonyDapp/issues/3178

**Comment by alicjakujawa** [comment]
@chinins this one is still blocked

**Comment by alicjakujawa** [comment]
@chinins removing blocked label

**Comment by chinins** [comment]
> @chinins removing blocked label

cool! Thank you!

**Comment by alicjakujawa** [comment]
@chinins How is going progress on that one? Did you start already?

**Comment by chinins** [comment]
> @chinins How is going progress on that one? Did you start already?

@alicjakujawa, I have started on it already (it's also `in progress` to show that)

**Comment by alicjakujawa** [comment]
@chinins Just didint see draft PR for that, so wasn't sure, thank you for update!
