### ISSUE TITLE
[UI] Add tick with tooltip to whitelisted addresses on Members page

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#3183]
## Specification
* Add tick with popover to item on members page
* It should be displayed if user is whitelisted [Logic will be implemented in different tasks, so just add bool]

### Design (optional, might not be applicable)
https://www.figma.com/file/Phby7kEYihhvGgQn69A314/Verified-Recipients?node-id=79%3A15782

**Comment by dit7ya** [comment]
Should this be closed now since #3189 is merged?
