### ISSUE TITLE
Implement logic for displaying whitelisted tick on members page

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#3184]
## Specification
* Fetch whitelisted addresses from IPFS
* Display tick for users which address is on whitelist

### Design (optional, might not be applicable)
https://www.figma.com/file/Phby7kEYihhvGgQn69A314/Verified-Recipients?node-id=79%3A15782

**Comment by alicjakujawa** [comment]
Blocked by
https://github.com/JoinColony/colonyDapp/issues/3183
https://github.com/JoinColony/colonyDapp/issues/3179

**Comment by arrenv** [comment]
Duplicate issue with https://github.com/JoinColony/colonyDapp/issues/3301 resolved by https://github.com/JoinColony/colonyDapp/pull/3305.
