### ISSUE TITLE
Number placement issue inside of dot

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3232]
I noticed an issue with the placement of numbers inside of dots. It seems to occur in multiple locations. I presume it's an CSS issue.

Easy to reproduce, create an action such as minting new tokens........

<img width="524" alt="Screenshot 2022-03-09 at 22 26 29" src="https://user-images.githubusercontent.com/582700/157476795-9d3e3979-de69-435c-bc8a-e06d8ab35552.png">

**Comment by arrenv** [comment]
@danbr I have fixed this issue in the `feature/claiming-all-stakes` branch https://github.com/JoinColony/colonyDapp/pull/3158

**Comment by danbr** [comment]
@arrenv - ah you wiley fox!!! I'll close this...... thank you
