### ISSUE TITLE
Manage whitelist dialog UI updates

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#3245]
## Things to fix

1. Tabs border alignment 
<img width="478" alt="Screenshot 2022-03-16 at 11 52 47" src="https://user-images.githubusercontent.com/13069555/158574393-0fea5490-aaca-4897-8f6b-3cc906d1ecfa.png">

1. Modal content (we should be able to scroll content)
<img width="619" alt="Screenshot 2022-03-16 at 11 52 58" src="https://user-images.githubusercontent.com/13069555/158574625-e2230a5c-b936-40bb-b008-afb9029b1f73.png">

**Comment by dit7ya** [comment]
Closing this since #3248 was merged.
