### ISSUE TITLE
It seems that there is no scroll on the dialog and the confirm button disappears in some cases

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyDapp#3264]
When you inactivate the whitelist it pushes the contents down and you can't see the button if the screen is not too big.

When 100% zoom, my max screen
<img width="601" alt="Screenshot 2022-03-25 at 16 50 48" src="https://user-images.githubusercontent.com/34057551/160133390-1911c16d-cfa2-4279-bbc3-4fe249ba292c.png">

when zoomed out  a bit
<img width="593" alt="Screenshot 2022-03-25 at 16 51 05" src="https://user-images.githubusercontent.com/34057551/160133434-ed1ef517-c2db-4cc4-9de4-8ce2d74ddaf9.png">

**Comment by danbr** [comment]
@chinins Is this the same issue that was tackled in #3248? (although it was merged)

**Comment by chinins** [comment]
That has been fixed in #3248. I can confirm after a rebase
