### ISSUE TITLE
[verified recipents] `m` is being treated as a confusable character 

### ISSUE THREAD

**Issue by dit7ya** [JoinColony/colonyDapp#3268]
## Steps to reproduce

While creating your username, use any word that has the English letter `m` in it. 

Though `m` does look like `rn`, I don't think that is enough reason to shun it.

![Screenshot 2022-03-28 at 10-07-56 Colony](https://user-images.githubusercontent.com/14034137/160327498-8cf16478-be60-4e90-8ffe-5fcea54eb451.png)
![Screenshot 2022-03-28 at 10-08-22 Colony](https://user-images.githubusercontent.com/14034137/160327504-2d9799c9-5886-4bc8-86c6-c03109be6dd0.png)

**Comment by danbr** [comment]
@dit7ya @arrenv @ArmandoGraterol 

Indeed the warning is generated.
(https://www.unicode.org/Public/security/10.0.0/confusables.txt)
24A8 ;	0028 0072 006E 0029 ;	MA	#* ( ⒨ → (rn) ) PARENTHESIZED LATIN SMALL LETTER M → LEFT PARENTHESIS, LATIN SMALL LETTER R, LATIN SMALL LETTER N, RIGHT PARENTHESIS	# →(m)→

Which begs the question: 
Is this warning appropriate?, and if not, then what is appropriate?
unicode-confusables doesn't have a flexible interface to deviate from Unicode's understanding of what is confusing.

**Comment by arrenv** [comment]
It does seem a little excessive. By looking at the package 'https://www.npmjs.com/package/unicode-confusables', it seems you could use `confusables` to return an array of the detected confusable characters. Which, we could use as a way to customise the detection.

**Comment by danbr** [comment]
> It does seem a little excessive. By looking at the package 'https://www.npmjs.com/package/unicode-confusables', it seems you could use `confusables` to return an array of the detected confusable characters. Which, we could use as a way to customise the detection.

Very excessive. Its banning the letter 'm'!! (I hear 'z' is currently having some issues also)
The package is very limited. Without being very 'hacky' it doesn't offer a way to mitigate its assessment. You cannot pass an amended object 'to customise the detection.', nor change the validation rules.
https://github.com/lastcanal/unicode-confusables/blob/develop/index.js
<img width="1111" alt="Screenshot 2022-04-08 at 16 32 10" src="https://user-images.githubusercontent.com/582700/162409790-7346f352-04d1-487c-bb1b-5a0b4d47699b.png">

I have not searched, but i assume there must be a better package out there in the big bad world?

**Comment by arrenv** [comment]
> Without being very 'hacky' it doesn't offer a way to mitigate its assessment. You cannot pass an amended object 'to customise the detection.', nor change the validation rules.

@danbr My thoughts were more in line with the hacky approach of using some custom second level detection on the `confusables` array if it included `point` "m". There does seem to be a few other libraries out there, but I was not able to find any yet that allowed for customising the character detection.

**Comment by danbr** [comment]
> > Without being very 'hacky' it doesn't offer a way to mitigate its assessment. You cannot pass an amended object 'to customise the detection.', nor change the validation rules.
> 
> @danbr My thoughts were more in line with the hacky approach of using some custom second level detection on the `confusables` array if it included `point` "m". There does seem to be a few other libraries out there, but I was not able to find any yet that allowed for customising the character detection.

@arrenv The authors of the package were notified  last year about the issue......  unsurprisingly by a user called 'Mark"!!
https://github.com/lastcanal/unicode-confusables/pull/1
Looks like they dont plan to make an update.

**Comment by danbr** [comment]
> > > Without being very 'hacky' it doesn't offer a way to mitigate its assessment. You cannot pass an amended object 'to customise the detection.', nor change the validation rules.
> > 
> > 
> > @danbr My thoughts were more in line with the hacky approach of using some custom second level detection on the `confusables` array if it included `point` "m". There does seem to be a few other libraries out there, but I was not able to find any yet that allowed for customising the character detection.
> 
> @arrenv The authors of the package were notified last year about the issue...... unsurprisingly by a user called 'Mark"!! [lastcanal/unicode-confusables#1](https://github.com/lastcanal/unicode-confusables/pull/1) Looks like they dont plan to make an update.

Also a user called 'Ian' may complain in the future!!!!! (yep also a problem)

**Comment by danbr** [comment]
> Had another ambiguous case today.
> 
> I'm not sure what the issue is with??? 0xEaBE562C979679DC4023dD23e8C6aa782448c2E7
> 
> Did you spot the problem..... its point: "0" similarTo: "O"
> 
> I am inclined to think that we should search for another package. But it's not clear to me what confusions we trying to catch?
> 
> Do we really want to check addresses? The warning message makes me think that the checking should be targeting usernames only.
> 
> <img alt="Screenshot 2022-04-12 at 13 43 13" width="515" src="https://user-images.githubusercontent.com/582700/162913440-01190387-bf4a-4901-9e2b-e1906d328ab1.png">

@arrenv Actually on review - this message is not appropriate as an address was supplied, and not a username.

**Comment by arrenv** [comment]
I agree with you here. I am leaning more and more to just scrapping it. Up for debate though.

**Comment by arrenv** [comment]
After raising this during the product sync and discussing possible options. The decision was made to explore creating our own confusable characters list within the DApp.

**Comment by sambacha** [comment]
> After raising this during the product sync and discussing possible options. The decision was made to explore creating our own confusable characters list within the DApp.

You should look into the phishing detection solution metamask uses, it solves a very similar problem for flagging potential phishing domain names by doing a levenshtein analysis to estimate how similar they are
