### ISSUE TITLE
Implement success state in ManageWhitelistedModal

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#3281]
## Specification
* no specs for it yet - please talk with Karol

### Description 

* Fix error which is displaying while doing upload
* For removal we probably just need to refresh list to show proper addresses

### TODO 
- [x] Get rid of incorrect error while uploading csv file
- [x] Refresh list of whitelisted addresses when only some of them was removed (currently nothing is happening)

**Comment by alicjakujawa** [comment]
Blocked by https://github.com/JoinColony/colonyDapp/pull/3258

**Comment by Karol-colony** [comment]
Alicja, here goes my suggestion: "Partial success. Review the list of addresses or add them manually."
