### ISSUE TITLE
Fix search functionality in ManageWhitelist modal

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#3300]
## Steps to reproduce

1. Try to use search for whitelisted addresses in ManageWhitelist modal

## Expected behaviour

* Addresses are correctly filtered (by address or username)

## Actual behaviour

* Addresses are not filtered

**Comment by arrenv** [comment]
I have been testing this on the main feature branch and the search is working fine. It definitely was not working on your other PR yesterday https://github.com/JoinColony/colonyDapp/pull/3295
