### ISSUE TITLE
Loader in GasStation not vertically centered

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3329]
## Steps to reproduce

1. Perform a transaction and watch the alignment of the loader in a transaction item.

## Expected behaviour

* Loader should be vertically centered

## Actual behaviour

* Loader is not vertically centered

![download (36)](https://user-images.githubusercontent.com/33682027/165050098-c1b8166d-4bac-45a9-a32c-a7191ae0836d.png)

**Comment by dit7ya** [comment]
I cannot reproduce it in master?

![2022-04-25_21-26](https://user-images.githubusercontent.com/14034137/165127542-3c28ee44-fa5c-465e-a525-3a7c69ec8fdf.png)

**Comment by arrenv** [comment]
Good to hear, do you see it on QA @dit7ya

**Comment by dit7ya** [comment]
Yes, it is there, I just checked.

**Comment by arrenv** [comment]
@dit7ya Confirming, it is centered correctly (i.e. I can close this), or showing off centered as of my initial issue?

**Comment by dit7ya** [comment]
It is working incorrectly in QA (not centered). Sorry for the confusion.

**Comment by ArmandoGraterol** [comment]
FYI, I found this bug specifically in #3190. So it's not in `master` yet it seems
