### ISSUE TITLE
Cannot modify form when transaction has failed or is rejected

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3330]
## Steps to reproduce

1. Create a transaction and reject it.
2. Try to modify the form or resubmit it.

## Expected behaviour

* You should be able to modify the form again or resubmit if it fails or is rejected.

## Actual behaviour

* Form is disabled and no longer able to be modified when transaction is rejected.

![download (37)](https://user-images.githubusercontent.com/33682027/165050638-b0cd8438-e1ec-45a8-b186-7ad2967bad14.png)

**Comment by rdig** [comment]
I'm actually not sure this is possible, or at least possible in a sensible fashion.

This is a side effect of the operation of `ActionForm`, and unless we refactor both it and the redux transactions system this cannot be fixed _(basically we need to introduce a middle state -- transaction failed, but salvageable. Currently we only have failed, retry with the same params)_

Unless there are any strong arguments against, I vote we close this issue

**Comment by arrenv** [comment]
Yeah, I remember raising it previously. But don't recall what happened with it. Thanks for clarifying, I will close for now.
