### ISSUE TITLE
Reputation on members page is wrapping

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3331]
## Steps to reproduce

1. Visit the RoadRunner colony on QA - https://qaxdai.colony.io/colony/roadrunner/members
2. Notice the wrapping of the reputation

## Expected behaviour

* Reputation should not be wrapped to a new line.

## Actual behaviour

* Reputation is wrapping to a new line.

![download (38)](https://user-images.githubusercontent.com/33682027/165051188-6eb43650-9b6c-403a-bffa-c8f4e6b0b983.png)

## Suggestions

* The width of the column needs to be increased.

**Comment by dit7ya** [comment]
Isn't this a duplicate of #3279 ?

**Comment by arrenv** [comment]
Thank you @dit7ya, it appears to be. Closing this one.
