### ISSUE TITLE
Investigate MemberInfoPopover's reputation section

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3334]
## Steps to reproduce

1. Create a colony and generate reputation for any amount of users
2. Check the popover that shows information about the user

## Expected behaviour

* The reputation section should show the rep that the user has over the domains of the colony

## Actual behaviour

* The reputation section is empty, as if the user didn't have any rep.

![FireShot Capture 580 - Members - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/165184309-e2b9f6fb-72e6-4ec8-a64d-89c776dcdb0c.png)

**Comment by dit7ya** [comment]
I did some investigation and seems like it is resulting from https://github.com/joincolony/colonyDapp/blob/8d8e76e36b570a5956dc480c30b961e49d9f97af/src/data/resolvers/user.ts#L237 which does not return the reputationAmounts. 

I was trying to do a bisect on this to find a commit where this feature worked as expected but seems like I could not compile old commits.

**Comment by ArmandoGraterol** [comment]
@dit7ya I think you forgot to assign the issue to you, seeing that you found the problem and talked with Chris about it. I'll be re-assigning this to you so that you can decide what to do with the issue

**Comment by rdig** [comment]
What's the state of this? Or maybe at least an update ?

**Comment by dit7ya** [comment]
@rdig It is a problem only on the dev server (not on QA) and @chmanie told me to just wait for it since it is going to be fixed in ColonyJS 5.1.

**Comment by rdig** [comment]
What does that have to do with anything ? We're not using the `5.x.x` branch of `colonyJS` in the Dapp, we're using the `4.x.x` branch.

Currently `colonyJS` version `5` is only used for the Colony SDK and CDapp

**Comment by ArmandoGraterol** [comment]
Closing this as reputation is showing as expected on the dev env and QA env
