### ISSUE TITLE
Cannot motion to add an address to the whitelist. It's always forced.

### ISSUE THREAD

**Issue by alicjakujawa** [JoinColony/colonyDapp#3335]

**Comment by alicjakujawa** [comment]
@jakzilla There is no motion support yet. It will be handle in separate epic so closing this issue for now

**Comment by area** [comment]
While this is possible, there is an issue here in terms of expected vs actual functionality, based on how I understand this feature has been implemented, which is by using the colony metadata blob.

If you make a proposal to update that metadata blob, that's fine in principle, and will work. However, let's say I make a proposal to change the blob from:

```
{key1: A}
```
to 
```
{key1: B}
```
If nothing else passes, and it happens, hunky dory. However, let's say someone with admin permission updates the blob in the interim:

```
{
key1: A,
key2: B
}
```

Now if the original proposal passes, `key2` will be deleted.

**Comment by arrenv** [comment]
The way Krono proposed for this to work, was to make the blobs add and subtract based and not complete object based.

`i.e. Add {key1: B}`

Then if there is a change that is forced in between, it won't matter as it will take the current state and either add or subtract the one from the motion.

After further discussion, this will require a new function on the contract though. So, a separate issue will be raised for that.
