### ISSUE TITLE
Estimation error: revert when attempting to upgrade colony network version from 8 to 9.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#3339]
<img width="1380" alt="Screenshot 2022-04-26 at 14 44 44" src="https://user-images.githubusercontent.com/4774274/165316669-c250b63a-0315-4887-bffe-bd2df4659478.png">

**Comment by rdig** [comment]
Closing. We mentioned in QA to not do this until we investigate.

This is unrelated to Verified Recipients and it's related to:
- colonyJS not knowing about v9
- there's some check in the dapp preventing this upgrade, that seems to be broken.

As I mentioned in the QA channel, I will investigate.
