### ISSUE TITLE
Inconsistent terminology for verified recipients

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3369]
@arrenv @alicjakujawa @Karol-colony @rdig 
I'm not sure if this is an issue? but i want to open the door to it being an issue......

Within the verified addresses dialog, 3 different terms are used to identify the same feature/functionality.

1. Verified addresses
2. Whitelist
3. Verified address list

<img width="739" alt="Screenshot 2022-05-09 at 10 59 28" src="https://user-images.githubusercontent.com/582700/167380346-ccd9e6e9-fac3-4e1c-8a65-c1ebcfa5cc8c.png">
<img width="512" alt="Screenshot 2022-05-09 at 11 01 21" src="https://user-images.githubusercontent.com/582700/167380374-4d095a11-e825-4427-8fb7-f1556fb0a37f.png">

(Personally, i like the term 'Verified addresses' the least, its a mouthful)

**Comment by arrenv** [comment]
@danbr Happy to go through this one with you.

**Comment by rdig** [comment]
Good catch @danbr :+1:

**Comment by rdig** [comment]
What's the state of this

**Comment by dit7ya** [comment]
Closing via #3375.
