### ISSUE TITLE
Change UAC title, subtitle, and position.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#3371]
Change Title from `Manage verified addresses` to `Manage Address Book`.

Change Subtitle from `Get warned when taking an action to addresses not on the verified list` to `Add addresses you trust to your colony’s address book`

Move Address book UAC item to under the “Manage Teams” section as it doesn't seem appropriate under advanced.

Change the words `Verified addresses` to `address book` here:
![Screenshot 2022-05-09 at 14 50 17](https://user-images.githubusercontent.com/4774274/167425467-a1cbca3a-4454-4530-8d7c-c7d08cde686c.png)

Change copy next to switch from `Verified addresses` to `Only show address book contacts as recipients`
![Screenshot 2022-05-09 at 15 00 11](https://user-images.githubusercontent.com/4774274/167426819-15499125-55a9-49bd-968e-239ed9cb3e3d.png)

**Comment by rdig** [comment]
What's the state of this ?

**Comment by dit7ya** [comment]
Closing via #3375.
