### ISSUE TITLE
Change warning upon deactivating verified recipients

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#3372]
Change this:
![Screenshot 2022-05-09 at 14 48 16](https://user-images.githubusercontent.com/4774274/167424267-656de2d2-d280-4972-8f5a-2c02fb6527c8.png)

to

`Warning. You are deactivating your colony’s address book. This is a list of addresses your colony has flagged as “safe”. Now, instead, all addresses watching your colony will appear in recipient selection menus. Be vigilant against spoof accounts.`

**Comment by rdig** [comment]
What's the state of this?

**Comment by dit7ya** [comment]
Closing via #3375.
