### ISSUE TITLE
Issue with adding new team button icon on scroll

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3373]
## Steps to reproduce

1. Go to https://xdai.colony.io/colony/shapeshift and click on the teams drop down
2. Check to see if the plus icon on the 'add new team' button is in the right place

Please confirm if you can see the same on production or QA, I am yet to replicate in local dev.

## Expected behaviour

* The icon should be in the right place

## Actual behaviour

* The icon is showing displaced.

![a1f8bb52-ca07-445a-9100-5bde4edd8391](https://user-images.githubusercontent.com/33682027/167478242-d3811cd3-dae3-46a2-9e91-3886b1046ba7.png)

**Comment by ArmandoGraterol** [comment]
Managed to reproduce it in `master` on local:
![FireShot Capture 589 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/167497686-1a07da51-c0ce-4faf-8b17-d2a0fee82e4b.png)

I will proceed to fix it
