### ISSUE TITLE
Updates to member items on members page

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3385]
### Description

Update the members item with the following:
- Move reputation value from the start to the end as of the design
- Add the value of reputation points (Numeral formatted) to `MemberReputation` component. Have this as a conditional element based on newly added boolean prop.
- Add the kebab menu item and menu with actions as of the design
    - The "Add to Address Book" would open the dialog box for the "Address book" with the users address pre-filled. https://github.com/JoinColony/colonyDapp/issues/3371

The kebab menu should allow for

### Design
[Figma link: Members items](https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=6736%3A93430)
[Figma link: Kebab menu](https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=6739%3A94092)

![Screenshot 2022-05-10 210035](https://user-images.githubusercontent.com/33682027/167702717-b9eba642-b34d-4125-ae62-fc83da4729d3.png)

![Screenshot 2022-05-10 210014](https://user-images.githubusercontent.com/33682027/167702715-0468bcb5-8882-4b7f-bba8-8fb37d799fc2.png)

**Comment by rdig** [comment]
What does "Add to Address Book" do ?

**Comment by arrenv** [comment]
@rdig The latest rename for Verified Recipients is "Address book" - https://github.com/JoinColony/colonyDapp/issues/3371
This would ideally open the dialog box for the "Address book" with the users address pre-entered.

**Comment by rdig** [comment]
Right, that's what I missed. Never mind. Forget I said anything :)

**Comment by arrenv** [comment]
You were on top of it, your comment prompted me to update the description, thank you. :)
