### ISSUE TITLE
Collision in Motions made between v3 and v4

### ISSUE THREAD

**Issue by lightnode** [JoinColony/colonyDapp#3386]
## Steps to reproduce

1. Complete a Motion cycle on v3 Motions and Rep Extension in Root
2. Upgrade to v4
3. Initiate a Motion in v4

## Expected behaviour

After the minimum stake is received, Motion appears in Actions Tab

## Actual behaviour

- Motion doesn't appear. 
- Direct link works, but comments from the Motion with the same index number (1 in this case) appear alongside the newly created Motion.
- After both sides are staked, it is unclear if Voting works as nothing happens in the UI after signing and sending the commit transaction.

### Old and New Comments:
![motionscomments](https://user-images.githubusercontent.com/44594862/167705859-e4a21ed3-5271-4d23-a67c-9b2ca1ad3262.PNG)

### Transactions Tab shows Motion 1:
![motion1](https://user-images.githubusercontent.com/44594862/167705521-7cdad715-ab76-4dc5-80e3-4029e4d5c57e.PNG)

**Comment by lightnode** [comment]
I was able to recreate the issue in a different Team

![motiontest](https://user-images.githubusercontent.com/44594862/167706553-4cd292c0-e682-4e5b-80b3-bb0dbbb7f670.PNG)

**Comment by rdig** [comment]
Sounds like some events got mixed up. We'll look into this.

Thanks for the report.
