### ISSUE TITLE
Wrong counter dot showing up when executing transacitons

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#3435]
![bug-verified-recipients-tx-icon](https://user-images.githubusercontent.com/1193222/172610819-8cde2ac7-a8b1-4849-a19b-68a156d1e813.gif)

That dot element shouldn't show up in individual transactions lines at all, it's a top level element that should just be visible on the group.

This is only tested on the #3190 branch, so most likely it's affected by something in it

**Comment by dit7ya** [comment]
I cannot reproduce this on the latest verified-recipients branch - I see no counter dot but just green checks.
