### ISSUE TITLE
Search icon size is incorrect

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3461]
## Steps to reproduce

1. Go to Members page on Watchers and Contributors

## Expected behaviour

* Icon should match design - https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=6736%3A93022

## Actual behaviour

* Size of icon is incorrect

![download (13)](https://user-images.githubusercontent.com/33682027/173018120-b28c3294-6d90-4819-93cb-8c170fd353e8.png)

**Comment by willm30** [comment]
MERGED #3470.
