### ISSUE TITLE
Account for "@" in User searches

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3462]
This has been reported by a user as a confusing aspect of our search.

## Steps to reproduce

1. Use the UserPicker to search for a user starting with `@`

## Expected behaviour

* Including `@` at the start of the search should still work, as this is how all users are displayed in the DApp and is common on other platforms as well.
* This should also be addressed in the Members page search.

## Actual behaviour

* When starting a search with `@`, it does not match any users.

![at-in-search](https://user-images.githubusercontent.com/33682027/173013699-1b3bd886-dc93-4680-bd4c-e077c4649394.gif)

![at-in-search-members](https://user-images.githubusercontent.com/33682027/173018551-ec9b959e-c7d8-4d15-a49e-9c07037345a4.gif)

**Comment by willm30** [comment]
@arrenv Your GIF reveals what appears to be another bug, which is that whatever you type, the first list item is an error message: "Address format is wrong!"

Am I right in thinking this is also a bug? And would it make sense to include it in this issue?

![address-wrong](https://user-images.githubusercontent.com/64402732/173088349-b7f0f3cd-eef1-4d49-bbcf-f6b72463a4fb.gif)

**Comment by arrenv** [comment]
@willm30 this was implemented before my time, so, I'm not 100% of the intended behaviour. However, I think this is fine, as the field allows you to also enter in an address.
