### ISSUE TITLE
DApp Mobile Responsiveness

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3474]
### Story

As a Colony user, I would like to be able to access and effectively use Colony on my mobile phone.

### Description

Many users on multiple different occasions have requested that the DApp be mobile responsive for themselves, for their DAO contributors and their investors. While, a lot of work can be done to make the DApp fully functional and native on mobile devices, in the short-term we can implement fairly simple UI improvements to make it at least functional.

This feature will require using media-queries to make the UI more responsive and the re-organising of some elements for the mobile view, it will also require two new dropdowns that should only be shown on the mobile sizing, an expanded mobile menu and a dropdown for user's colony details.

The designs only account for key screens, you will also need to ensure modals, and pages not included are also optimised in a similar way to the designed screens.

The breakpoint for mobile should be max `768px`

### Design

[Figma Link to 7 mobile screens](https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Style-Guide?node-id=6641%3A9676)

![iPhone 8 - 2](https://user-images.githubusercontent.com/33682027/173367776-ccb679bd-6ca7-4081-87ea-8c807ce9628b.png)
![iPhone 8 - 3](https://user-images.githubusercontent.com/33682027/173367778-6f22224e-f3a3-4ea0-b3a0-09a73f4fddb3.png)
![iPhone 8 - 4](https://user-images.githubusercontent.com/33682027/173367780-7e081526-2764-4144-b705-a6b12470719f.png)
![iPhone 8 - 5](https://user-images.githubusercontent.com/33682027/173367782-123405e8-e02f-4077-b74a-7bd2596b1410.png)
![iPhone 8 - 6](https://user-images.githubusercontent.com/33682027/173367784-3e39d5e3-d2cc-4110-8198-6f77be260332.png)
![iPhone 8 - 7](https://user-images.githubusercontent.com/33682027/173367787-7f2a1372-c398-4956-bcba-bacc50f75714.png)
![iPhone 8 - 1](https://user-images.githubusercontent.com/33682027/173367790-013bddca-bb90-4d4a-96a6-3732b19569a4.png)

## Related Issues

**Work is being tracked here**: #3481

**Comment by willm30** [comment]
I have set up this project to track this work: https://github.com/JoinColony/colonyDapp/projects/29

**Comment by willm30** [comment]
> > I have set up this project to track this work: https://github.com/JoinColony/colonyDapp/projects/29
> 
> Will you be owning this project then @willm30 ?

Yes, I'd like to be in charge of this one.

**Comment by willm30** [comment]
@rdig Ok will do, thanks.
