### ISSUE TITLE
Adapt Colony Home page popovers and menus to mobile

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3499]
## Specification

Relates to #3475 

### Description

This issue tracks the work involved in ensuring all menus and popovers accesible from the Colony Home screen are mobile responsive. 

### Design 

See #3475 

### This issue is complete when the following are mobile responsive:

- [x] Connect wallet button and menu
- [x] New actions menu
- [x] Funds summary menu
- [x] Colony summary menu
- [x] Teams summary menu
- [x] Create new team menu
- [x] User avatar menu

**Comment by willm30** [comment]
DONE. Popovers and menus are mobile responsive.

**Comment by arrenv** [comment]
@willm30 You don't need to manually close these, as they should close automatically when you merge the PR if linked correctly.

Also, closing before they are merged is not the right workflow. If your PR is never merged this issue would no longer be open but the issue would still remain.

**Comment by willm30** [comment]
@arrenv Ok thanks, have reopened and will sync with correct PR.

**Comment by willm30** [comment]
https://github.com/JoinColony/colonyDapp/pull/3485 MERGED.
