### ISSUE TITLE
Contributors are being shown as Watchers

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3507]
## Steps to reproduce

1. Create a colony.
2. Generate reputation for the root user.
3. Join the colony with a fresh user.
4. Generate reputation for the second user.
5. Take a look at the contributors vs watchers section in the aside or the Members page.

## Expected behaviour

* The second, newer member with reputation, should appear along with the first user on the contributor's side.

## Actual behaviour

* The second user appears on the watcher's side even though it has reputation, and this is the case for any other user that doesn't have domain roles but has reputation.

![FireShot Capture 627 - Members - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/174179006-4c2e3a22-b55b-4eb7-8900-ac5e2b62b07b.png)

## Suggestions

* Tried to find the source of this bug, managed to track it down to the `colonyMembersWithReputation` resolver in the `colony` file. The resolver is _always_ returning an empty array as if there were no members with reputation, including the root user.

**Comment by chinins** [comment]
Closing as merged #3514 (not sure why not closed automatically)
