### ISSUE TITLE
Joining and Leaving a Colony not updating in UI

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3533]
## Steps to reproduce

1. Checkout the `feature/contributors-vs-watchers` branch.
2. `Join` a colony and `Leave` a colony.
3. Take note of your avatar in the Watchers list.

## Expected behaviour

* The list of Watchers and Contributors should update in the UI like it does in `master` when joining and leaving a colony.

## Actual behaviour

* The list of Watchers and Contributors does not update in real time when joining and leaving a colony in the UI like it does in `master`, it requires a refresh.

![subscriptions-not-updating](https://user-images.githubusercontent.com/33682027/175348602-5e2b7fae-80e4-4896-aa5b-013dcce445a9.gif)

**Comment by chinins** [comment]
@arrenv, this is not a bug - it's a feature :) When refactoring the page and introducing extra logic @rdig and I discovered that with extra requirements it's no longer worth to have it as a subscription and it's now a query. Please, let me know if you want to discuss  it further.

**Comment by rdig** [comment]
Yeah, I can attest to this.

It's what we'll have to deal with until CDapp

**Comment by arrenv** [comment]
> @arrenv, this is not a bug - it's a feature :) When refactoring the page and introducing extra logic @rdig and I discovered that with extra requirements it's no longer worth to have it as a subscription and it's now a query. Please, let me know if you want to discuss it further.

Yeah, makes sense. Thanks for the clarification.
