### ISSUE TITLE
Bug: Links are Inactive on Funds Page

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3550]
## Steps to reproduce

1. Make sure you have a colony created and are connected to a wallet as normal. Make sure the `governance` extension is enabled.
2. Signout and join the same colony with a different wallet.
Bug1: The "Available Funds" heading in the right aside should link to the funds page, but is inactive.
3. Go to funds page (click "manage funds")
Bug2: The three links in the right aside should all be active.

## Expected behaviour

1. Available funds link on home page should be active
2. "Move", "mint" and "manage" links should all be active 

## Actual behaviour

1. Link is inactive
2. Only the "mint" link is active

## Screenshot

**_Bug 1 (highlighting is mine)_**
![available-funds-link](https://user-images.githubusercontent.com/64402732/176230014-f624b6a0-d0a2-4544-bbc3-83a8bf96a1f0.png)

**_Bug 2_**
![image](https://user-images.githubusercontent.com/64402732/176229570-1a2fbaad-c317-49c6-b700-3e1de95ac1ea.png)

**Comment by arrenv** [comment]
> @arrenv Can you confirm that what I've listed as the first bug in the description is indeed a bug? I don't follow the rationale of disabling the link in any case given you can still access the funds page by clicking "manage funds".
> 
> This is the code snippet:
> 
> ![funds-heading](https://user-images.githubusercontent.com/64402732/176232888-a4acbef6-042a-4409-8917-1aa7583c37ad.png) .

Yes, I think this is also a bug. Especially, like as you said, you can access funds via the `Manage funds` button.

**Comment by Julianahlk** [comment]
@willm30 I tested following your steps and I noticed that:

bug 1: if I give the second user the Funding permission, then the "Available Funds" link will be active for that user. Are you saying it's a bug that this link should still be active without the Funding permission? I am thinking an alternative is to make it so that the "Manage Funds" link is only active if the user has the Funding permission to make it match the "Available Funds" link.

bug 2: when I test with a user with the Funding permission, the "Move funds" link is active and when that user has the Administrative permission, the "Manage Tokens" link is active. Is this what you are expecting or are the required permissions not correct?

**Comment by willm30** [comment]
@Julianahlk

Bug 1: The bug is that the link is conditionally active. It should just be active, no matter what permissions you have because you can access that page anyway by clicking "manage funds". It's just a case of the removing the conditional logic in the code snippet above and keeping the `<NavLink>` part. 

Bug 2: I will defer to @arrenv to answer this one

**Comment by Julianahlk** [comment]
@willm30 ok got it, so you are sure that the "Manage Funds" link should be available for everyone regardless of permissions?

**Comment by arrenv** [comment]
> @willm30 ok got it, so you are sure that the "Manage Funds" link should be available for everyone regardless of permissions?

Yes, the page is accessible anyway, so, that is correct.

The 'Move funds' and 'Manage tokens' should have the same state as the mint tokens. i.e. if you have the correct permissions or the 'Governance' extension is active, i.e. users can create a Motion for them.

**Comment by Julianahlk** [comment]
> Bug 1: Yes, the page is accessible anyway, so, that is correct.
> 
> Bug 2: The 'Move funds' and 'Manage tokens' should have the same state as the mint tokens. i.e. if you have the correct permissions or the 'Governance' extension is active, i.e. users can create a Motion for them.

Thanks Arren, all clear now 😊
