### ISSUE TITLE
Bug: Too much ETH in Wallet

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3551]
## Steps to reproduce
I'm not sure of the extent to which this is reproducible  but documenting here anyway just in case:

1. Ensure you have no ETH in your account
2. Go to the Wallet page
3. Wallet says I have 99 ETH.

## Expected behaviour

* Wallet should say I have no ETH.

## Actual behaviour

* Wallet says I have 99 ETH.

## Screenshots

**_Funds: No eth_**
![no-eth](https://user-images.githubusercontent.com/64402732/176235526-bb976903-f342-46c3-baa9-d5e19a3e41bb.png)

**_Wallet: 99 Eth_**
![wallet-99](https://user-images.githubusercontent.com/64402732/176235311-f5077c96-6e12-4884-a195-302800716767.png)

**Comment by arrenv** [comment]
This is correct, the Wallet page you are on is your Ganache wallet, which should have about 99 ETH in it.

The Funds screen is the funds you have in the Colony, which is also correct at 0. Unless you send funds to it.

Hot tip, you can add these Ganache Wallets to your MetaMask for testing by going to the `colonyNetwork` submodule and go to `ganaache-accounts.json`. In the screenshot (1.) is the wallet address, (2.) the wallet's private key, used for importing into MetaMask. In MetaMask, you need to be on the localhost network though.

![Screenshot 2022-06-28 190629](https://user-images.githubusercontent.com/33682027/176242057-5b348a41-b352-4954-b4fd-f6681a7b3441.png)

**Comment by willm30** [comment]
@arrenv Thanks for the explanation. It's clear now that you've explained it to me, but a new user may also initially find the distinction confusing. To help explain the difference maybe we could include something simple like the text "in your wallet" after the number of wallet ETH, and the text "(colony)" after the "Available funds" heading, so it would read, respectively:

_wallet popover_
**In your wallet**
![wallet-text](https://user-images.githubusercontent.com/64402732/176405289-65128c18-bf84-4f0f-b4ff-b4c28a50f4f2.png)

_home page_
**Available funds (colony)**
![available-funds-text](https://user-images.githubusercontent.com/64402732/176405272-c90a332b-a687-4b6b-b1e4-61d500e70866.png)


Thoughts on this?

**Comment by arrenv** [comment]
@willm30 That is good feedback. We are working on a refresh to a lot of the DApp, so, I will add this to the list.
