### ISSUE TITLE
Create mobile responsive `ConnectWallet` page 

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3577]
## Specification

Relates to https://github.com/JoinColony/colonyDapp/issues/3481

### Story

When I sign out, and click Create a Colony, I want the Connect Wallet page to be mobile responsive.

### Description

Following the style of the designs (linked in other issues in this project), this issue tracks the work required to make the Connect Wallet screen mobile responsive.

### Design

No design for this specific screen but should follow style of other designs in this project.

[Image](!https://inline-image-from-figma-for-quick-reference-or-posterity)

### This issue is complete when...

- [ ] The Connect Wallet screen is mobile responsive (localhost/connect)

**Comment by rdig** [comment]
Shouldn't this be closed by #3580 ?

**Comment by willm30** [comment]
MERGED #3580
