### ISSUE TITLE
Bug: Can only have one verified address at once

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3588]
## Steps to reproduce

1. Switch to base feature branch from master, ensure you have no members verified to start with
2. Add a member to the address book and refresh so you can see the tick confirming they're verified
3. Add another member to the address book and refresh
4. The first member has lost their tick. 

## Expected behaviour

* Should be able to verify multiple members

## Actual behaviour

* Can only verify one member at any given time

## GIF

![losing-verification](https://user-images.githubusercontent.com/64402732/177736379-42281078-f34d-4b59-b4c7-ed560f30a08a.gif)

**Comment by chinins** [comment]
It's a maintenance project, not members.

**Comment by willm30** [comment]
@chinins I put it there because it's not happening for me on `master` so wanted to be clear about which branch it's addressing

**Comment by arrenv** [comment]
> @chinins I put it there because it's not happening for me on `master` so wanted to be clear about which branch it's addressing

What happens after you refresh the page? For me it seems to fix it.

**Comment by chinins** [comment]
It's only one person that can reproduce the bug. So I think it's worth putting it on hold and if we don't see it happening in QA then we will assume it's local to that dev environment and won't invest time to investigate further.

@willm30, you can also try restarting you dev environment. Sometimes, this helps with ipfs stuff.
