### ISSUE TITLE
Add responsive styles for `/{colony_home}/buy-tokens` (Coin Machine)

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3597]
## Specification

Coin machine at `${COLONY_HOME_ROUTE}/buy-tokens` should be mobile responsive.

**Comment by rdig** [comment]
No this should be not. Coin Machine is to be removed. See #3531

**Comment by willm30** [comment]
WONTFIX. Coin machine being removed from dapp.
