### ISSUE TITLE
Add: `/wallet`, `/inbox/`, and `/buy-tokens` to mobile navigation

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3603]
## Specification

Currently the following routes can only be accessed by their URL on mobile: `/wallet`, `/inbox/`, and `/buy-tokens`. 
This issue is to add them to the hamburger menu. Wallet and Inbox with My Profile and Settings, and Buy tokens beneath extensions.

**Comment by rdig** [comment]
Closed by #3605 ?

**Comment by willm30** [comment]
MERGED #3605
