### ISSUE TITLE
Connect `Add Gnosis Safe` dialog

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3622]
### Story

As a user, I want to be able to add my Gnosis Safe to the Colony and know if the safe is available.

### Description

This is done by storing the safe with IPFS, in the colony's metadata, in a similar way to how we edit the colony's details in the `editColony` action. The metadata should now have an array of safes where each item has the name, contract address, and chain of the stored safe.

Also, now an info message should appear below the `Add Safe contract` input that indicates if the safe exists or not in the Gnosis chain (Done by consulting this API: https://safe-transaction.mainnet.gnosis.io/)

### Design

[Figma link](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=839%3A19935)

![FireShot Capture 661 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/178809298-582e94a4-3aa9-48a7-9df2-b4c464fc320c.png)

### This issue is complete when...

- [x] The availability of the safe in the Gnosis chain is established by the info message.
- [x] You can click submit and upload the safe to the colony's metadata.

**Comment by willm30** [comment]
I'll pick this one up. Good chance to learn some more about IPFS!

**Comment by ArmandoGraterol** [comment]
Happy hunting Will!

**Comment by willm30** [comment]
MERGED #3643
