### ISSUE TITLE
Implement "Add Gnosis Safe" action page

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3657]
### Story

As a user, I want to be able to add my Gnosis Safe to the Colony and see an action page detailing the action after doing it.

### Description

After adding a safe, the user should be redirected to a corresponding action page showing the correct title, action details, and action events.

### Design

[Figma link](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=727%3A15054)

![FireShot Capture 667 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/179864306-a887d60e-940b-4d73-b044-2a6c918b8d10.png)

### This issue is complete when...

- [ ] The action page title shows the "Add Gnosis Safe" variant.
- [ ] The action page event list shows a corresponding event for the "Add Gnosis Safe" action.
- [ ] The action details section shows the relevant data for the "Add Gnosis Safe" action.

**Comment by willm30** [comment]
MERGED #3660
