### ISSUE TITLE
Horizontal scroll moves page over Colony list

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3658]
## Steps to reproduce

1. (mac)F12 to bring up dev console or reduce window size to make horizontal scroll necessary
2. Scroll horizontal

The page will move over the Colony list on the left side.

![Jul-20-2022 08-06-20](https://user-images.githubusercontent.com/582700/179902028-e8d52ff2-e7da-476f-a7e4-8ad56af8ed41.gif)

**Comment by jakubcolony** [comment]
Hey @danbr, do you still experience this issue? I can't reproduce it

**Comment by chinins** [comment]
> Hey @danbr, do you still experience this issue? I can't reproduce it

I've just noticed this one as well, so I can take it.
