### ISSUE TITLE
Decisions: Create Decisions details modal (UI Only)

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3708]
### Story

As a user when creating a Simple Decision, I want to be presented with a dialog that allows me to enter the decision details.

A similar component has already been implement in CoinMachine (using https://tiptap.dev/):
https://github.com/JoinColony/coinMachine/pull/125

### Design
Figma: https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=1018%3A54646

<img width="951" alt="Screenshot 2022-08-02 at 12 40 42" src="https://user-images.githubusercontent.com/582700/182344308-aadea59b-5a41-4e18-9632-4e31f65e865f.png">

**Comment by willm30** [comment]
@danbr Do you know what the water-droplet icon is intended to do in the rich text editor toolbar? The icon on the end? It's not included in the coin machine version of the component and haven't seen it before.

**Comment by danbr** [comment]
@willm30 Its a good question, the answer is certainly not obvious.
i'll guess that its a 'colour picker pipette' to select the text colour?... 

Perhaps @arrenv knows???? Is it 'dropable'?

**Comment by arrenv** [comment]
Haha, we had the same conversation in Coin Machine the other week. It is just the WYSIWYG toolbar that Karol added in.

@willm30 Use the exact same implementation as the Coin Machine one for now.

**Comment by willm30** [comment]
@arrenv Ok thanks 🙂

**Comment by willm30** [comment]
MERGED #3719
