### ISSUE TITLE
Decisions: Create Edit Decisions details modal (UI Only)

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3710]
### Story

As a user, after reviewing the Decision details i would like to be able to edit the details.

### Description

Based upon the Decisions details modal, open the modal with the previously entered information, change confirmation button text.

This should be based upon #3708
### Design 

Figma:https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=1018%3A56046

<img width="769" alt="Screenshot 2022-08-02 at 13 12 58" src="https://user-images.githubusercontent.com/582700/182350719-24e6b02b-b7a5-47eb-804b-5af275c13ba6.png">

**Comment by willm30** [comment]
MERGED #3756
