### ISSUE TITLE
Connect "Transfer NFT" transaction type action

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3722]
### Description

This issue corresponds to the `Transfer NFT` transaction type inside the "Control safe" dialog. In order to make the transaction, we are going to use a bridge to execute the transactions across chains.

The transaction is expected to work for cross-chain safes/contracts.

**NOTE**: 
1. This interaction has the lowest priority of the 4.
2. As long as #3765 is not merged, this issue can be worked on by branching out of that PR.

## Implementation

* Steps to get the dev env ready for testing transactions:
```
0. Have your normal dev env already running.
1. cd src/lib/colonyNetwork 
2. git fetch
3. git checkout maint/cross-chain-safe 
4. git submodule update --init
5. yarn
6. yarn provision:safe:contracts
7. cd lib/safe-contracts then yarn
8. cd ../.. (back into colonyNetwork)
9. bash scripts/start-bridging-environment.sh
10. node scripts/start-bridging-environment.js
```
You'll see this in the console if the steps were run successfully:
```
Bridge Monitor running
Home bridge address: 0xE0EeC1f1d5Cc344206710Ad526E180e5CeEE5B1c
Foreign bridge address: 0x312787b78BA0A2C4e9092a7871E49c421c24e7Fa
Gnosis Safe address: 0xC33533885f666baB63243b9E0B8432602d8dDb52
Zodiac Bridge module address: 0x0a72DCB0584A80cada11cC95aB2386f23225C63d
```

### This issue is complete when...

- [x] Selecting a safe populates the NFT selector with the NFT stored in the safe. #3835 
- [x] The NFT displays the NFT image, contract, and id. #3835
- [x] Submitting the form creates a correct transaction/many transactions (in the case of a multi transaction) that can be viewed, approved, rejected, executed, etc.

### Suggestions

* These links could be helpful for testing/development:
How to find the emitted events if needed: https://docs.ethers.io/v4/api-contract.html?highlight=events#filtering-events
Example of how to make the transactions (In the context of Network, however): https://github.com/JoinColony/colonyNetwork/commit/e4484246889a4d24b19e58e9a496330e00a77f0f

**Comment by willm30** [comment]
Merged #3875
