### ISSUE TITLE
Add "Transfer NFT" transaction type to preview dialog

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3729]
### Story

As a user creating a "Transfer NFT" transaction from the Gnosis control dialog, I want to see a preview of the transaction before sending it.

### Description

When the user chooses the "Transfer NFT", and fills the form of the Gnosis control dialog, after confirming the form and before sending the transaction, they should see a preview of what transactions they are going to send, along with the preview of other transactions (in the case of the user doing a multi transaction).

### Design

[Figma link](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=5418%3A22229)
![FireShot Capture 687 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/183501383-ea50ccf4-9e9a-4fee-b234-2c5510115543.png)

### This issue is complete when...

- [ ] You click on the submit button of the previous Gnosis Safe Control dialog screen with a "Transfer NFT" transaction added and it takes you to the preview with a summary of that transaction.
- [ ] The summary includes the transfer request and approval of the request. So, a "Transfer NFT" is a multi transaction by default.

**Comment by willm30** [comment]
@ArmandoGraterol I would like to take on this one but have a question. It in the issue description it says:

>  The summary includes the transfer request and approval of the request. So, a "Transfer NFT" is a multi transaction by default.

But this screen would suggest you can submit a "Transfer NFT" as a single transaction, i.e. without the "approve" section: 

![transferNFTprev](https://user-images.githubusercontent.com/64402732/185109003-34767199-a328-48fa-8f7e-e315c42477fd.png)

Should I ignore this screen and use the one you include in the issue? Or are there two possible preview types?

**Comment by willm30** [comment]
MERGED #3772
