### ISSUE TITLE
Improving Number Formatting

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3733]
### Description

Since we have been using Numeral formatting in the DApp for awhile now, we have had a chance to see how it works in different cases and also receive some feedback on how numbers are presented. The following is a list of number formatting rules we would like to implement.

1. Abbreviate only above 1 million, i.e. we should not see thousands abbreviated anywhere like the screenshot [IMAGE 1].
2. Anything over 1,000 should not have more then 2 decimal places.
3. Numbers below 1 can have up to 5 decimals.
4.  Ensure consistency with spacing for e.g. [IMAGE 2] should have a space.
5. The main Colony balance should not be abbreviated
6. All abbreviated numbers should show the full number on hover, like addresses, or using a tooltip.
7. Use engineering notation above 1 trillion and numbers less then 0.00001

IMAGE 1:

![download (67)](https://user-images.githubusercontent.com/33682027/183733991-b723c238-1d0b-4335-8380-9fae7e270bd0.png)

IMAGE 2: 

![Screenshot 2022-08-09 202820](https://user-images.githubusercontent.com/33682027/183734273-2a1e4f92-2176-4789-9b31-a2ccdd86db75.png)

**Comment by jakubcolony** [comment]
Closing this as it'll now be addressed in the CDapp [issue #53](https://github.com/JoinColony/colonyCDapp/issues/53)

**Comment by arrenv** [comment]
@jakubcolony Can something be included in the DApp now to fix the abbreviation of numbers less then 7 digits, at least?

This is a one that has come up a few times and users have been keeping an eye on this update. It would be good to have it included in the next release of DApp, as opposed to have a seemingly minor thing still be existent many months after we introduced it.
