### ISSUE TITLE
Implement action page for Safe transactions

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3778]
### Story

As a user, after making a safe transaction, I have to be redirected to the corresponding action page.

### Description

After making a transaction, or several transactions, related to safes, the user should be redirected to our good ol' action page, where the title, description, and data previously inputted by the user will be displayed. 

**NOTE**: This issue should address ALL the transaction types and whether the user did single or multiple transactions. There's going to be a lot of shared code between the transactions, better to get them all in 1 issue to avoid code repetition and stepping on each other foot situations.

### Design

[Figma link](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=126%3A9670)

![FireShot Capture 704 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/187005448-83909700-9487-427a-868f-37a2ab3433ba.png)
![FireShot Capture 705 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/187005452-86d67044-70e8-4b23-942c-b3d89a28dfc3.png)
![FireShot Capture 706 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/187005455-332a08e0-03bf-4cd2-beb3-d29326308c47.png)
![FireShot Capture 707 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/187005458-66b7bbbb-eead-4619-8633-151f7d88c7a9.png)
![FireShot Capture 708 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/187005459-9eb25011-7af5-45fa-a30a-932834233970.png)

### This issue is complete when...

- [ ] The user is redirected to the action page after making any number of safe transactions
- [ ] The action page shows the title as the title inputted by the user in the dialog
- [ ] The action page shows the annotation as the description inputted by the user in the dialog
- [ ] The details widget shows the relevant info of the action, if multiple transactions are made, it also shows them all.
- [ ] The action is shown in the action list with the corresponding title

**Comment by willm30** [comment]
Merged #3821
