### ISSUE TITLE
Horizontal overflow when clicking from user profile to address dropdown on first clicks

### ISSUE THREAD

**Issue by thomassdk** [JoinColony/colonyDapp#3781]
## Steps to reproduce

1. Load the colony Dapp
2. Click on the user profile to view the dropdown
3. Click on the address dropdown 

## Expected behaviour

* There is no horizontal overflow

## Actual behaviour

* Horizontal overflow occurs when clicking between these 2 dropdowns, the profile dropdown has to be clicked first otherwise this doesnt happen, this happens regardless of the dropdown being closed or not.

https://user-images.githubusercontent.com/32598350/187181342-126aad81-f15c-46bb-905f-db1cd781790a.mp4

**Comment by jakubcolony** [comment]
Hey @thomassdk, I can't replicate this issue. Would you be able to confirm if you're still experiencing it?

**Comment by thomassdk** [comment]
Yep still experiencing this issue, although it only seems to happen if these are my very first actions on the page.

My browser is:
```
Chromium 105.0.5195.125
```

However when I tested it with `Mozilla Firefox 104.0.2` and the issue didnt show up.

**Comment by jakubcolony** [comment]
Thanks! 
I was finally able to reproduce this, in production, and only after claiming a username
