### ISSUE TITLE
Annotations aren't showing up.

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3843]
## Steps to reproduce

Add an annotation message after publishing a decision.

## Expected behaviour

Should be seen in the feed.

## Actual behaviour
Annotation doesn't show up, even after refreshing.
![annotation-broken](https://user-images.githubusercontent.com/64402732/189862679-f15c54dd-532f-463a-9ebe-b85f4c0dbe66.gif)

**Comment by chinins** [comment]
It is a known issue that needs to be fixed but it's comments, not annotaitons

**Comment by willm30** [comment]
@chinins It's a known issue as in there's already an issue open and I should close this one?

**Comment by chinins** [comment]
> @chinins It's a known issue as in there's already an issue open and I should close this one?

Yes, please, close. Sorry, I wasn't clear. It will be worked on as part of the refactoring issue that Dan has already created.

**Comment by willm30** [comment]
DUPLICATE.
