### ISSUE TITLE
Refactor AddExistingSafe dialog

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyDapp#3849]
### Story

As a user, when adding a safe to the colony, I need to go through a multistep process inside the dialog.

### Description

Due to the requirements of creating a cross-chain transaction, the `AddExistingSafeDialog` should now include 3 steps to link a safe to the colony. 

- In the 1st step, the user should input the chain and address of the safe, and this stage should check that the safe exists in the chain, as we are currently doing. 

- In the 2nd step, the user should see a warning, a description explaining this step, and 3 **read-only** inputs with data that we are going to provide:
  1. The AMB field should display a corresponding AMB address for the chain of the safe. _(It is my understanding that this should be the HOME bridge address)_
  2. The controller address field is just the colony's address.
  3. The chain id field should be `100` as we are deployed on the Gnosis chain after all.

- The final step should include a summary of the details in the first step and 3 more inputs: 
  1. The Zodiac module address input, which should also check that the module is added to the safe. 
  2. The safe's name input.
  3. The annotation text field.

### Design

[Figma link](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=7108%3A22501)

![FireShot Capture 716 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/189939993-cd41bf7f-39a9-43e4-9e4a-bfde13e18be2.png)

![FireShot Capture 717 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/189939997-45f3fea1-4eb3-43bf-9fc2-67ca2d21ba08.png)

![FireShot Capture 718 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/189940003-9b3b1bb7-0802-495e-a25e-599177735965.png)

### This issue is complete when...

- [ ] The steps are implemented as per the specs and have all the required inputs with corresponding validation.
- [ ] Submitting the form adds the safe as we did before, but now includes the Zodiac Module Address (The rest of the new fields like AMB address, controller address, and chain id are things that we can deduce and should know already, and are only there for the user to input when installing the zodiac module).
- [ ] The action page shows in the details widget the zodiac bridge address along with the other details that we have.

Link for the 2nd step's description: https://colony.gitbook.io/colony/advanced-features/safe-control-gnosis-safe
Link for the 3rd step's "Where to find this": https://colony.gitbook.io/colony/advanced-features/safe-control-gnosis-safe#finding-module-contract-address

**Comment by willm30** [comment]
@arrenv What should I show in step 2 for chains without a bridge? We've currently only got bridge data for mainnet, rinkeby and binance smart chain (from https://docs.tokenbridge.net/.

**Comment by willm30** [comment]
@ArmandoGraterol I think it should be the foreign address as the AMB. Using their setup guide as a reference, where it says:
> An example for this on Rinkeby would be:
It uses the AMB address for Rinkeby(`0xD4075FB57fCf038bFc702c915Ef9592534bED5c1`), which is the foreign amb if gnosis chain is the home chain.

**Comment by ArmandoGraterol** [comment]
@willm30 Yeah that's what I had in mind, but I was interpreting it as the Home Bridge being the bridge native to the safe we are trying to communicate with, and the Foreign bridge being the one we use to communicate.

So what I was trying to say is that if the Safe is in Rinkeby then we show the Rinkeby home bridge, so based on that I'm considering us the foreigners as we are the ones communicating with the safe, "going" to its chain so to speak, instead of the safe coming to us.

Semantics, am I right?

**Comment by willm30** [comment]
> Semantics, am I right?

@ArmandoGraterol Haha yeah, lotsa new terminology in this one.

**Comment by willm30** [comment]
MERGED #3858
