### ISSUE TITLE
Decisions:Add time & tags to Decision header - staking pages

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyDapp#3869]
### Story

As a user, when on the motions staking page i would like to see the time showing the age of the Decision.

### Description 

Following the designs, use existing components.

<img width="782" alt="Screenshot 2022-09-19 at 17 04 03" src="https://user-images.githubusercontent.com/582700/191052191-5fa334be-e7f5-4e7d-a599-b61f327975ca.png">

### Design 

Figma: https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=1386%3A57367

**Comment by jakubcolony** [comment]
Arren has kindly pointed me at https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=1386%3A57367 for the most up-to-date designs
