### ISSUE TITLE
Team for decision creation is always root

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyDapp#3880]
If you create a decision in a team other than root, it will still show that it was created in root. Despite the parameter that's passed to saga being correct.

**Comment by danbr** [comment]
<img width="1038" alt="Screenshot 2022-09-22 at 18 30 57" src="https://user-images.githubusercontent.com/582700/191803211-1ac28c4c-3f29-4411-b579-272cd8536af9.png">
<img width="1034" alt="Screenshot 2022-09-22 at 18 31 32" src="https://user-images.githubusercontent.com/582700/191803217-e2dd69a4-66c2-477b-853c-84a826f6adfa.png">
