### ISSUE TITLE
"Contract not verified" should be an error, not status

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3923]
## Steps to reproduce

In Safe Control, under contract interaction, add a contract address that is on a different network to the selected safe.

## Expected behaviour

The "Contract not verified" message is an error message, and so I would expect it to show up as an error. 

## Actual behaviour

But it's currently appearing as a status.

![contract-not-verified](https://user-images.githubusercontent.com/64402732/192978543-14741a29-5b9f-423b-9b14-594772b03499.png)

**Comment by ArmandoGraterol** [comment]
Why do you not agree? This isn't a bug, I purposely implemented it like this. According to Formik:

> status?: any
> A top-level status object that you can use to represent form state that can't otherwise be expressed/stored with other methods. This is useful for capturing and passing through API responses to your inner component.

**Comment by willm30** [comment]
@ArmandoGraterol Sorry, didn't mean "bug" in the sense of it being an unintentional oversight, meant more like: is this correct? 

My thinking is that if the contract is not verified, this is an error in the contract verification process and should display as an error. 
Also, the API responds with `status: 0, message: NOTOK` when you get this repsonse, which also suggests to me that it should be displayed in the ui as an error.
 
Then, relatedly, it would appear like the following if #3926 is merged: 

![not-verified](https://user-images.githubusercontent.com/64402732/194281787-34643439-d018-4b81-9eb6-81a67d68f47c.png)

**Comment by willm30** [comment]
MERGED #3926
