### ISSUE TITLE
Vote is not being detected, allowing me to vote multiple times

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3931]
## Steps to reproduce

1. Have at least two members in a Colony with reputation. No one should have over the voting threshold in reputation(default is 70%),
2. Disable the Reputation monitor so that it does not fast forward you through the Motion on each transaction - http://localhost:3001/reputation/monitor/toggle
3. Create a Motion
4. Fully stake with one member and fully object with the other member on the Motion to get to a Vote.
5. Vote on the Motion.

This may take a couple of tries to get, as it was not happening every time. It was first reported by DAO Club on mainnet and I have replicated it locally following this process.

Note: I have noticed that this seems to fix it self once all people have voted. i.e. the vote is being detected, however, the reveal option is visible one all people have voted.

The same issue seems to also happen with the "Reveal" button, i.e. all people need to reveal, before it is update in the UI for each person that they clicked the reveal button.

## Expected behaviour

* The vote should be detected, let the user know their vote, but also allow them to change their vote.
* Clicking the reveal button should notify the user that they have successfully revealed their vote.

## Actual behaviour

* Voting was not detected, and user can vote multiple times.
* Reveal button does not notify the user that they successfully clicked the reveal button.

![vote-not-saving](https://user-images.githubusercontent.com/33682027/193401969-a74a4ae6-89a0-4ca3-b121-0eac9a1dcac1.gif)

**Comment by arrenv** [comment]
@chinins I have added this screen to show a state for a user that has voted - https://www.figma.com/file/CCgGsBzhX3BUENS1IvgP7N/Motions-%26-Disputes?node-id=6878%3A157037

Also, here is one for a user who has clicked the "Reveal" button - https://www.figma.com/file/CCgGsBzhX3BUENS1IvgP7N/Motions-%26-Disputes?node-id=6878%3A158120

**Comment by chinins** [comment]
> @chinins I have added this screen to show a state for a user that has voted - https://www.figma.com/file/CCgGsBzhX3BUENS1IvgP7N/Motions-%26-Disputes?node-id=6878%3A157037
> 
> Also, here is one for a user who has clicked the "Reveal" button - https://www.figma.com/file/CCgGsBzhX3BUENS1IvgP7N/Motions-%26-Disputes?node-id=6878%3A158120

great, thank you!
