### ISSUE TITLE
Scroll to selected option in Select component

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3943]
### Story

As a user ~~interacting with a contract~~, I would like ~~the functions~~ any dropdown in the ~~control safe form~~ dapp to display the currently selected ~~function~~ option, if there is one, instead of always beginning at the top. 

## Current Behaviour

List always begins from top

![scroll function selector](https://user-images.githubusercontent.com/64402732/193998737-9e12973a-54e9-446b-8ac7-01aab3e504cf.gif)

### This issue is complete when...

- [ ] Opening the function selector displays the currently selected function

**Comment by jakubcolony** [comment]
Having discussed this with @arrenv, it makes sense to apply this fix to all selects in the dapp. I've updated the issue accordingly and will open a new PR into master
