### ISSUE TITLE
Implement fallback for Avatar url

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3973]
## Steps to reproduce

Now that Rinkeby's been deprecated, I believe the safe api has forbidden requsts to get NFT logo. (This behaviour wasn't happening before Rinkeby was deprecated, hence my suspicion)
![403](https://user-images.githubusercontent.com/64402732/195133921-070f8590-b760-42db-b394-370248cc5bbb.png)

Logo should be present next to "Creature 4"
![fallbackurl](https://user-images.githubusercontent.com/64402732/195133937-3023a6ec-2721-4f76-88cd-49b03be01315.png)

Screenshot is from https://github.com/JoinColony/colonyDapp/pull/3821

In any case, the Avatar component should have a fallback in case the url can't be fetched. I'm opening in safe control because I noticed it here but could always be moved to `maintenance`.

## Expected behaviour

Avatar  component shows blockie as fallback if url image can't be fetched

## Actual behaviour

Currently shows nothing

## Suggestions 

Fetch the url in a try catch. If receive an error code ([403, 404...](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)), show blockie. Else, use css url-fetching as currently exists in component.

**Comment by danbr** [comment]
Hey @willm30  - could you give me the necessary safe & contract details to allow me to recreate the issue described with NFTs & Avatars?

I've been playing generally with Avatar & notSet prop, and i can get a blockie when there is an empty avatarURL. So i'd like to try to recreate the issue so i understand better.

The data fetching happens outside of Avatar, usually from fetching from IPFS. Of course blockies is called from with Avatar where necessary. I dont know where we look for the NFT avatar data?

thank you

**Comment by willm30** [comment]
@danbr Yes sure. To recreate the issue exactly, you'll need to checkout https://github.com/JoinColony/colonyDapp/pull/3821 andset up the local bridging environment (instructions below). Then add the following safe on Rinkeby:

Safe: 0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A
Module: 0xa838Bd5B1e66fE90fbCb5264D3fd88f2E4e245bB

Then, go to Safe Control and transfer the NFT. In the consequent action page, you'll be able to see the screenshot I posted above. 


### Setting up Briding Env

0. have your normal dev env running with webpack running in a separate terminal.
1. `cd src/lib/colonyNetwork` 
2. `git fetch` 
3. `git checkout maint/cross-chain-safe` 
4. `git submodule update --init` 
5. `yarn` 
6. `yarn provision:safe:contracts` 
7. `cd lib/safe-contracts` then `yarn`  (you will see errors, ignore them)
8. `cd ../..` (back into colonyNetwork) 
9. `bash scripts/start-bridging-environment.sh` 
10. `node scripts/start-bridging-environment.js` 
11. Copy over the addresses in the terminal into your .env file:

LOCAL_HOME_BRIDGE_ADDRESS=
LOCAL_FOREIGN_BRIDGE_ADDRESS=
LOCAL_SAFE_ADDRESS=
ZODIAC_BRIDGE_MODULE_ADDRESS=
LOCAL_ERC721_ADDRESS=
LOCAL_SAFE_TOKEN_ADDRESS=

12. restart webpack.

**Comment by danbr** [comment]
> @danbr Yes sure.
> 
> To recreate the issue exactly, you'll need to checkout #3821 and set up the local bridging environment (instructions below). Then add the following safe on Rinkeby:
> 
> Safe: 0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A Module: 0xa838Bd5B1e66fE90fbCb5264D3fd88f2E4e245bB
> 
> Then, go to Safe Control and transfer the NFT. In the consequent action page, you'll be able to see the screenshot I posted above.
> 
> I think the problem is that when you give the css url property a url that doesn't return the desired resource (e.g. because of a 403), it has nothing to show. Which is why I think it'd be good to catch this and show a backdrop like a blockie if the fetching fails.
> 
> ### Setting up Briding Env
> 0. have your normal dev env running with webpack running in a separate terminal.
> 1. `cd src/lib/colonyNetwork`
> 2. `git fetch`
> 3. `git checkout maint/cross-chain-safe`
> 4. `git submodule update --init`
> 5. `yarn`
> 6. `yarn provision:safe:contracts`
> 7. `cd lib/safe-contracts` then `yarn`  (you will see errors, ignore them)
> 8. `cd ../..` (back into colonyNetwork)
> 9. `bash scripts/start-bridging-environment.sh`
> 10. `node scripts/start-bridging-environment.js`
> 11. Copy over the addresses in the terminal into your .env file:
> 
> LOCAL_HOME_BRIDGE_ADDRESS= LOCAL_FOREIGN_BRIDGE_ADDRESS= LOCAL_SAFE_ADDRESS= ZODIAC_BRIDGE_MODULE_ADDRESS= LOCAL_ERC721_ADDRESS= LOCAL_SAFE_TOKEN_ADDRESS=
> 
> 12. restart webpack.

@willm30 thanks for the clear instructions..... so far the config has worked as expected. (It might be worth storing this somewhere, it could be useful to others)

**Comment by willm30** [comment]
MERGED #4031
