### ISSUE TITLE
Handle long strings in Select 

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyDapp#3991]
This issue generalises one of the cases mentioned by @willm30 in #3972 related to handling long strings in Select. Similarly to #3943, I think the fix should be apply to all Select instances. 

![image](https://user-images.githubusercontent.com/112586815/195683483-357a1150-5f64-4a14-ae07-38670f258575.png)

**Comment by jakubcolony** [comment]
It looks like the behaviour of Select is to "stretch" as much as needed for the content so in order for any truncation to work we'd need to set a maximum width.
@arrenv could you suggest what that should be set to?

**Comment by arrenv** [comment]
> It looks like the behaviour of Select is to "stretch" as much as needed for the content so in order for any truncation to work we'd need to set a maximum width. @arrenv could you suggest what that should be set to?

My initial thinking here is to max width to 100% of the width of the select (which should be the container), then use the ellipsis overflow that is already being used. Then use the title for the full value.

Here is an example:

![33734270-9f9b660f4d8aed48b208dd77a8d0b07c](https://user-images.githubusercontent.com/33682027/197746824-2b9d5c89-c450-4f56-82d6-c70dd624dd80.png)

![Screenshot 2022-10-25 121111](https://user-images.githubusercontent.com/33682027/197746886-0e344b81-af3c-4844-9ef3-a3f89a6c5375.png)
