### ISSUE TITLE
Safe Tx Preview in Contract Interaction not showing contract address

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3996]
See imgs below. to(address) and token aren't showing in preview. Using: `0x5F29Eced9CD9b2B0F10dd81B8E63Bb1982E4c845` as contract and address arg

![contractint](https://user-images.githubusercontent.com/64402732/195833337-6a7c961b-89f0-42bd-aa74-59da74c2a34a.png)
![contractin2](https://user-images.githubusercontent.com/64402732/195833340-993188de-3a1c-4e94-869b-168f09dc1640.png)

**Comment by ArmandoGraterol** [comment]
@willm30 I can't reproduce this with the latest feature branch commit:
![FireShot Capture 729 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/195952588-198d4c86-b832-4a0f-9705-c355d5c844df.png)
![FireShot Capture 728 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/195952595-3a7b3c10-5780-4e5c-96cb-c153338438d4.png)

Can you check again just in case?

**Comment by willm30** [comment]
@ArmandoGraterol Looks to have fixed itself. My favourite kind of bugs do this.  😄
