### ISSUE TITLE
The Max button in Transfer Funds has an odd behaviour when clicked twice

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyDapp#4011]
## Steps to reproduce

It doesn't seem to happen for all safes and tokens but I've already seen it happen a few times.

1. Add a safe, e.g.:
```
Safe address: 0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A
Zodiac module address: 0xa838Bd5B1e66fE90fbCb5264D3fd88f2E4e245bB
```
2. Select Transfer Funds and choose a token (for the safe above, select `WILL`).
3. Click on Max twice

## Expected behaviour

The amount is set to and stays at the maximum allowable

## Actual behaviour

The amount is set to the maximum after the first click, then it changes to some other value:

https://user-images.githubusercontent.com/112586815/196544353-44d0a360-e91c-4eb7-8978-8012b0bd3c62.mov

https://user-images.githubusercontent.com/112586815/196544362-5b3f96fb-fdbf-4603-9017-77f2a9331eda.mov

**Comment by willm30** [comment]
MERGED #4016
