### ISSUE TITLE
Safe control pickers styling breaks if safe transaction fails

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyDapp#4027]
I've seen this issue before but I wasn't sure how to reproduce it. I don't know if it's relevant since the transaction failed most likely because there was something wrong with my bridging environment so I'll let @ArmandoGraterol or @willm30 decide and picko or close this issue.

## Steps to reproduce

1. Create any safe transaction.
2. Make it fail after clicking submit (you'll probably know better what can cause that)
3. Go back and click on any of the pickers

## Expected behaviour

* Nothing happens

## Actual behaviour

* The styling of the clicked picker breaks:

https://user-images.githubusercontent.com/112586815/197875751-daa7628b-88b9-4c9f-b512-b02f76263299.mov

<img width="513" alt="Screenshot 2022-10-25 at 21 26 15" src="https://user-images.githubusercontent.com/112586815/197876007-c8db29a7-3043-42cf-a1b7-c42cca533e60.png">

**Comment by willm30** [comment]
@jakubcolony I am indeed well versed in having transactions fail 😂 Although in production we shouldn't have transactions failing, I agree that it shouldn't break the ui if it does happen. Good spot! I'll take a look into it.

**Comment by willm30** [comment]
Setting this to blocked until we have an alternative safe set up for testing. Rinkeby has been deprecated, so transfer funds section not working and my attempts to comment out various other pieces to code to try and initiate the saga aren't working.

**Comment by willm30** [comment]
Have put in a pr to fix this here: https://github.com/JoinColony/colonyDapp/pull/4036

**Comment by willm30** [comment]
Basically, the touch state wasn't being set after the component had been interacted with. But, it was being set after the form submission. So, when the form submission failed, and you click back to the Preview, the inputInvalid class was being applied to the component, and this class was not inheriting correctly from the input class, hence the weird styling.
