### ISSUE TITLE
Update Crowdfund Stakes tooltip

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#4055]
## Steps to reproduce

Create a motion
Stake partially
Object partially
"Crowdfund Stakes" section should appear. Hover over tooltip.

![motions](https://user-images.githubusercontent.com/64402732/199748373-cc1f8573-3f17-42c6-a846-d090ec4c830d.png)

**Comment by willm30** [comment]
@arrenv I had a quick look but I don't believe there's another issue currently tracking this. What should the tooltip text say?

**Comment by arrenv** [comment]
> @arrenv I had a quick look but I don't believe there's another issue currently tracking this. What should the tooltip text say?

That is very odd, I feel like I had discussed this recently, or it was in another issue. Either way, the copy for this is here - https://www.figma.com/file/CCgGsBzhX3BUENS1IvgP7N/Motions-%26-Disputes?node-id=3510%3A9410

`The total staked amount and weight for each side of the Motion.`

![Screenshot 2022-11-03 195129](https://user-images.githubusercontent.com/33682027/199809286-66bb7f35-5fcf-468a-bbda-b24b75a6f10c.png)
