### ISSUE TITLE
Ensure there is validation on the recipient address

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#4086]
## Steps to reproduce

1. With a Safe added on Colony, go to create a transaction request
2. Go to create a transaction and add in an address that is not on the Safe's chain. e.g. use a Gnosis Chain address, like a Colony address.
3. You will notice that it allows you to do this transaction without validation. This would result in lost funds.

## Expected behaviour

* The recipient field should validate that the address entered exists on the same chain as the Safe.
* This should be the case for all transaction types.

## Actual behaviour

* There is no validation on the recipient address.

![34847489-7b474ad040cd1109b20a00c8ca0389c6](https://user-images.githubusercontent.com/33682027/204548329-74863209-ebc0-4bac-8fc0-0f3d6bc4cbc3.png)

**Comment by ArmandoGraterol** [comment]
@arrenv I think this is not possible, all the addresses as long as they have a valid format count as existing in the chains (I don't know the full technical details of why this is the case tho).

For example, if I search your colony's address in Etherscan it technically exists: https://etherscan.io/address/0x079c2d8217CfFB006fC4F1B73e3E77194A8BC58e

Same when I search it in the Binance chain. Thoughts? Am I missing something?

**Comment by arrenv** [comment]
> Same when I search it in the Binance chain. Thoughts? Am I missing something?

I'm pretty sure you are correct, I may have been mixing up some thinking in regards to how we check for token addresses in the Colony creation flow, but we are using for 'tokenSupply' in that I believe. Then I was remembering about a trick to use `estimateGas` to see if it fails or not.

Eitherway, if there is no way to do it, what I think we need to do is at least put a note in like with the other updates. There is a design here for it:

https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=8198%3A23691&t=0tPMrXoN383cJxhi-1

![Screenshot 2022-12-02 125857](https://user-images.githubusercontent.com/33682027/205288054-4b0cedd2-c093-45a2-bf4e-946e8c2d0dd8.png)
