### ISSUE TITLE
Deployment permissions failure

### ISSUE THREAD

**Issue by linkelei9** [JoinColony/colonyDapp#4113]
## Steps to reproduce

1. Log in with a MetaMask wallet. Create a colony. Deploy colony and sign transactions on metamask. 7th transaction (Give permission to OneTx PaymentExtension) doesn't execute.

## Expected behaviour

MetaMask should present "sign" for this transaction.

## Actual behaviour

Wheel continues spinning and MetaMask doesn't activate.

## Suggestions (optional)

I don't know what OneTx is. But perhaps it's trying to connect with something in my wallet and not finding it.

**Comment by arrenv** [comment]
@linkelei9 Thank you for reporting this one, this has now been resolved in production.
