### ISSUE TITLE
Join users by KYC

### ISSUE THREAD

**Issue by vporton** [JoinColony/colonyDapp#4171]
### Story

My colony has only one user and I want more.

I want to add option to give X tokens to anyone who passes KYC.

### This issue is complete when...

- [ ] KYC is added
- [ ] An action to give X tokens to everybody passed KYC is added

**Comment by arrenv** [comment]
@vporton Thanks for the suggestions, we are adding token bootstrapping to the DApp in an upcoming feature.

In regards to adding KYC to the DApp, we have discussed this previously, but I have also added it to our feature requests here - https://news.colony.io/requests/en/add-kyc-functionality

Which, FYI you can also access within the DApp directly:

![adding-feedback](https://user-images.githubusercontent.com/33682027/216590953-8a113c9b-d348-4be7-92e6-450a8e36883d.gif)

I am closing this as an issue for now though.
