### ISSUE TITLE
Example: Show activity indicator for all async activity related to transactions (Colony Creation Wizard)

### ISSUE THREAD

**Issue by vporton** [JoinColony/colonyDapp#4172]
### Story

My colony has only one user and I want more.

I want to add option to exchange CLNY or WCLNY tokens to my colony's tokens.

### Description (optional, but useful!)

Allow my colony to do action allowing to lock CLNY (or WCLNY?) token, issuing to the locker X*Y my tokens where X is the amount of CLNY tokens, Y is the coefficient decided by my colony.

On locking CLNY mint my token to the locker.

### This issue is complete when...

- [ ] Allow to edit Y using a colony action
- [ ] Implement the locking of CLNY (or WCLNY?)

**Comment by arrenv** [comment]
@vporton another interesting idea. We will be enabling this through our standalone Coin Machine app. However, there could be a simplified version of this within the DApp, I have added the suggestion here - https://news.colony.io/requests/en/allow-people-to-exchange-my-colonys-native-tokens-within-colony

Closing this as an issue for now.

**Comment by vporton** [comment]
It is probably better to use xDai than CLNY.
