### ISSUE TITLE
Update colony onboarding

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyDapp#737]
This epic covers the update of the colony onboard process. This involves:

- Extract the gas station component / it’s subcomponent so that we can show it in another context
- Adjust Create Colony wizard
- Adjust the Claim User Profile flow
- Adjust / add to get username workflow
- Wire up the extracted gas station

All of these changes will be split up into different issues under the umbrella of this epic.

For reference here the link to the workflow in figma: https://www.figma.com/file/CGSZdfl2KbfKvG30jnoKSmtn/Onboarding?node-id=1373%3A20969

**Comment by rdig** [comment]
Closing this seeing as it's done
