### ISSUE TITLE
Add snackbar success notification component

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#868]
We have designs for a snackbar success notification that's triggered on certain events (event list will be handled in another issue).

There are two:

1. Success (with green shadow)
2. Failure (with red shadow)

Both are positioned **bottom left**.

**Success**
![snackbar-white-success](https://user-images.githubusercontent.com/15755488/53127618-bd6bf680-3517-11e9-9a2d-d4925fd1c169.png)

**Error**
![snackbar-error](https://user-images.githubusercontent.com/15755488/53127620-c066e700-3517-11e9-920b-7ea051b367a9.png)

## Disappear behavior
The timeout should be set to 4s.

The user can also dismiss these by clicking the `X`.

## Animation
These should fade in and fade out from the left.

## Only show one snackbar at a time
Only one snackbar should appear at a time. When multiple snackbar updates are necessary, they should appear one at a time.

See this video for a demo: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Ox5qX5je_tUiv8P9V9tTfGRTd3RTsvxh%2F02-appearconsecutive.mp4

**Comment by Karol-colony** [comment]
If we can do it simple way, I am ok with suggestion of doing generic message to listen to any error or success. I am not sure if we need it always, probably not - @collinvine  where is list of events? (see first post) 

It is certainly hard to know if changes were saved in settings or not.
